import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Loader2, RefreshCw, RotateCcw } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { invokeSecureFunction } from '@/lib/secureInvoke';
import { toast } from 'sonner';
interface PendingEvent { id:string; event_type:string; aggregate_type:string; attempts:number; occurred_at:string; last_error:string|null }
interface DeadLetter { id:string; event_type:string; attempts:number; failed_at:string; last_error:string }
interface Checkpoint { consumer_name:string; last_occurred_at:string|null; updated_at:string }
export function IntegrationHealthPanel(){
 const [pending,setPending]=useState<PendingEvent[]>([]),[dead,setDead]=useState<DeadLetter[]>([]),[checkpoints,setCheckpoints]=useState<Checkpoint[]>([]),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);const {data,error}=await invokeSecureFunction('legal-matters-admin',{operation:'list_integration_health'});if(error||data?.error)toast.error(data?.error||error?.message||'Unable to load integration health');setPending(data?.pending||[]);setDead(data?.dead_letters||[]);setCheckpoints(data?.checkpoints||[]);setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const replay=async(id:string)=>{const {data,error}=await invokeSecureFunction('legal-matters-admin',{operation:'replay_integration_dead_letter',dead_letter_id:id});if(error||data?.error)return toast.error(data?.error||error?.message||'Replay failed');toast.success('Event queued for replay');await load()};
 return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Pending events</p><p className="text-2xl font-semibold">{pending.length}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Dead letters</p><p className="text-2xl font-semibold">{dead.length}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Consumers</p><p className="text-2xl font-semibold">{checkpoints.length}</p></CardContent></Card></div><Card><CardHeader className="flex flex-row items-start justify-between space-y-0"><div><CardTitle className="text-base">Cross-portal delivery</CardTitle><CardDescription>Durable events remain visible until projection and delivery succeed.</CardDescription></div><Button variant="outline" size="sm" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></CardHeader><CardContent>{loading?<div className="flex justify-center py-10"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground"/></div>:pending.length===0?<p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No pending events. New legal and transaction-case changes will appear here until processed.</p>:<div className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead>Event</TableHead><TableHead>Aggregate</TableHead><TableHead>Attempts</TableHead><TableHead>Last error</TableHead></TableRow></TableHeader><TableBody>{pending.map(event=><TableRow key={event.id}><TableCell><div className="font-medium">{event.event_type}</div><div className="text-xs text-muted-foreground">{new Date(event.occurred_at).toLocaleString('en-AU')}</div></TableCell><TableCell>{event.aggregate_type}</TableCell><TableCell><Badge variant="outline">{event.attempts}</Badge></TableCell><TableCell className="max-w-sm truncate text-xs text-muted-foreground">{event.last_error||'—'}</TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card>{dead.length>0&&<Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><AlertTriangle className="h-4 w-4 text-destructive"/>Dead letters</CardTitle><CardDescription>Review the failure before manually replaying an event.</CardDescription></CardHeader><CardContent className="space-y-2">{dead.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><p className="font-medium">{item.event_type}</p><p className="max-w-xl text-xs text-muted-foreground">{item.last_error}</p></div><Button variant="outline" size="sm" onClick={()=>void replay(item.id)}><RotateCcw className="mr-2 h-4 w-4"/>Replay</Button></div>)}</CardContent></Card>}</div>
}
