/**
 * The date a person reads on the library, drawn — not scanned.
 *
 * 25 Sep 2026: 60 Lawley Street was regenerated that afternoon and the card
 * still said "Latest Sep 24, 2026, 11:46 AM", because it printed the row's
 * `created_at`. These render the package card and the report card as the
 * library does, from a row shaped like the library projection's answer. It
 * lives here rather than beside the component because CI runs this folder.
 */
import { render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { ReactNode } from 'react';
import { describe, expect, it, vi } from 'vitest';

import { PropertyReportPackageCard } from '@/components/reports/library/PropertyReportPackageCard';
import type { InvestmentReport } from '@/components/reports/library/types';

vi.mock('@/lib/secureInvoke', () => ({ invokeSecureFunction: vi.fn(async () => ({ data: null, error: null })) }));
vi.mock('@/contexts/NotificationsContext', () => ({
  useNotifications: () => ({ addNotification: vi.fn() }),
  useNotificationsOptional: () => null,
}));

const LAWLEY: InvestmentReport = {
  id: '5d8bc97e-9305-49a4-bb3d-5cd2a7a0d82d',
  property_address: '60 Lawley Street, Spalding WA 6530',
  property_listing_id: null,
  canonical_property_key: 'address:60-lawley-street-spalding-wa-6530',
  // Local noon so the rendered day is the same in any test time zone.
  created_at: '2026-09-24T12:00:00',
  generated_at: '2026-09-25T16:29:35',
  generated_at_basis: 'generation',
  current_version: 8,
  report_tier: 'compass',
  report_variant: 'compass',
  status: 'completed',
};

const noop = () => {};
const wrap = (node: ReactNode) => (
  <QueryClientProvider client={new QueryClient()}>
    <MemoryRouter>{node}</MemoryRouter>
  </QueryClientProvider>
);

describe('the library prints when a report was generated', () => {
  it('names the regeneration, not the row', () => {
    render(wrap(
      <PropertyReportPackageCard
        reports={[LAWLEY]}
        isSelected={() => false}
        generatingTier={null}
        activeComparisonType={null}
        canSelectReport={() => true}
        canAddMore
        isAutoGenerated={false}
        canEditReports={false}
        generatorLabel={() => 'Rugesh'}
        getGradeColor={() => ''}
        getScoreColor={() => ''}
        onToggleSelection={noop}
        onView={noop}
        onDownload={noop}
        onRegenerated={noop}
        onViewHistory={noop}
        onToggleArchive={noop}
        onGenerateTier={noop}
      />,
    ));
    expect(screen.getByText(/^Latest Sep 25, 2026, 4:29 PM · completed$/)).toBeInTheDocument();
    expect(screen.queryByText(/Sep 24, 2026/)).toBeNull();
  });
});
