import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AlertTriangle, Briefcase, CalendarClock, ChevronLeft, ChevronRight, Loader2, RefreshCw, Search } from 'lucide-react';
import { Badge } from '@/components/ui/badge';import { Button } from '@/components/ui/button';import { Card,CardContent,CardDescription,CardHeader,CardTitle } from '@/components/ui/card';import { Input } from '@/components/ui/input';import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { cn } from '@/lib/utils';import { SolicitorEmptyState } from '@/components/solicitor-portal/SolicitorEmptyState';import { SolicitorPortalShell } from '@/components/solicitor-portal/SolicitorPortalShell';import { useDebounce } from '@/hooks/useDebounce';import { useSolicitorMatters } from '@/lib/solicitorQueries';
import { MATTER_STATUS_CLASSES,MATTER_STATUS_LABELS,MATTER_STATUS_ORDER,MATTER_TYPE_LABELS,countdownLabel,formatMatterDate,formatPropertyAddress,type LegalMatterStatus } from '@/lib/legalMatters';

export default function SolicitorMatters(){const navigate=useNavigate();const [search,setSearch]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1);const debounced=useDebounce(search,300);useEffect(()=>setPage(1),[debounced,status]);const query=useSolicitorMatters({search:debounced.trim(),status,page,pageSize:25});const records=query.data?.records||[],pagination=query.data?.pagination;
const summary=[{label:'Visible matters',value:pagination?.total||0,icon:Briefcase},{label:'Page',value:pagination?.page||page,icon:CalendarClock},{label:'At risk on page',value:records.filter(m=>m.risk_flag).length,icon:AlertTriangle}];
return <SolicitorPortalShell title="Matters" description="Matter-scoped files with server-side search and pagination." actions={<Button variant="outline" size="sm" onClick={()=>void query.refetch()} disabled={query.isFetching}><RefreshCw className={cn('mr-2 h-4 w-4',query.isFetching&&'animate-spin')}/>Refresh</Button>}>
<div className="grid gap-3 sm:grid-cols-3">{summary.map(({label,value,icon:Icon})=><Card key={label} className="solicitor-portal-stat-card"><div className="absolute inset-x-0 top-0 h-[2px] bg-gradient-to-r from-transparent via-primary/30 to-transparent"/><CardContent className="flex items-center gap-3 pt-6"><span className="flex h-11 w-11 items-center justify-center rounded-xl border border-primary/25 bg-primary/10"><Icon className="h-5 w-5 text-primary" aria-hidden/></span><div><p className="text-2xl font-semibold tabular-nums">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>)}</div>
<Card><CardHeader className="gap-3"><div><CardTitle className="text-base">Matter list</CardTitle><CardDescription>Search requests are debounced and cancelled when filters change.</CardDescription></div><div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" aria-hidden/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search matter reference or property" className="pl-9" aria-label="Search matters"/></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="sm:w-56" aria-label="Filter by status"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{MATTER_STATUS_ORDER.map(s=><SelectItem key={s} value={s}>{MATTER_STATUS_LABELS[s]}</SelectItem>)}</SelectContent></Select></div></CardHeader><CardContent>
{query.isLoading?<div className="flex justify-center py-14"><Loader2 className="h-6 w-6 animate-spin text-primary" aria-label="Loading matters"/></div>:query.isError?<div role="alert" className="rounded-lg border border-destructive/40 p-6 text-center"><p className="font-medium">Matters could not be loaded</p><p className="mt-1 text-sm text-muted-foreground">Check your connection and try again.</p><Button className="mt-4" variant="outline" onClick={()=>void query.refetch()}>Try again</Button></div>:!records.length?<SolicitorEmptyState className="border-0 shadow-none" icon={<Briefcase className="h-6 w-6" aria-hidden/>} title="No matters to show" description="Clear the filters, or ask your practice administrator to confirm matter access." actionLabel={search||status!=='all'?'Clear filters':undefined} onAction={search||status!=='all'?()=>{setSearch('');setStatus('all')}:undefined} secondaryLabel="Back to dashboard" onSecondaryAction={()=>navigate('/solicitor')} hint="Matter access is granted per file"/>:<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Matter</TableHead><TableHead className="hidden md:table-cell">Client</TableHead><TableHead className="hidden lg:table-cell">Type</TableHead><TableHead>Status</TableHead><TableHead>Settlement</TableHead></TableRow></TableHeader><TableBody>{records.map(m=>{const countdown=countdownLabel(m.settlement_date);return <TableRow key={m.id}><TableCell><Link to={`/solicitor/matters/${m.id}`} className="block rounded-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="flex items-center gap-2 font-medium">{m.title}{m.risk_flag?<AlertTriangle className="h-3.5 w-3.5 text-destructive" aria-label="At risk"/>:null}</span><span className="block max-w-80 truncate text-xs text-muted-foreground">{m.matter_reference?`${m.matter_reference} · `:''}{formatPropertyAddress(m)}</span></Link></TableCell><TableCell className="hidden md:table-cell">{m.client_name||'—'}</TableCell><TableCell className="hidden lg:table-cell">{MATTER_TYPE_LABELS[m.matter_type]}</TableCell><TableCell><Badge variant="outline" className={MATTER_STATUS_CLASSES[m.status as LegalMatterStatus]}>{MATTER_STATUS_LABELS[m.status as LegalMatterStatus]}</Badge></TableCell><TableCell>{formatMatterDate(m.settlement_date)}{countdown?<span className="block text-xs text-muted-foreground">{countdown}</span>:null}</TableCell></TableRow>})}</TableBody></Table></div>}
{pagination&&pagination.total_pages>1?<nav aria-label="Matter pages" className="mt-4 flex items-center justify-between"><p className="text-sm text-muted-foreground">Page {pagination.page} of {pagination.total_pages} · {pagination.total} matters</p><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page<=1||query.isFetching} onClick={()=>setPage(v=>v-1)}><ChevronLeft className="mr-1 h-4 w-4"/>Previous</Button><Button variant="outline" size="sm" disabled={page>=pagination.total_pages||query.isFetching} onClick={()=>setPage(v=>v+1)}>Next<ChevronRight className="ml-1 h-4 w-4"/></Button></div></nav>:null}
</CardContent></Card></SolicitorPortalShell>}
