/**
 * The schema the column-name gate judges against.
 *
 * `check-edge-column-names.mjs` reports a column as missing when it is in
 * neither the generated types nor the migrations. That makes the resolver the
 * gate's eyesight, and a resolver that quietly returns nothing is worse than no
 * gate at all: every call site passes, the file exists, the concern looks
 * handled. Two ways it could go blind have already happened while this was
 * being written —
 *
 *  - reading only `types.ts`, which is regenerated by hand and predates
 *    `builder_stock_items.image_work_stage`, so seven real columns read as
 *    absent and would have been "fixed" into columns that do not exist;
 *  - stripping SQL comments with a regex, which paired an opening block
 *    marker in one migration with a closing one in another and deleted the
 *    `ALTER TABLE` line that the following `ADD COLUMN`s belonged to.
 *
 * So this asserts the union is really a union, that a genuinely absent column
 * is still absent, and that an unknown table is skipped rather than judged.
 */
import { describe, expect, it } from 'vitest';

import {
  knownColumns,
  migrationColumns,
  stripSqlComments,
  typedColumns,
} from '../../../scripts/security/lib/supabaseSchema.mjs';

describe('the resolver can see', () => {
  it('reads the generated types', () => {
    const clients = typedColumns('clients');
    expect(clients).not.toBeNull();
    expect(clients!.length).toBeGreaterThan(20);
    expect(clients).toContain('primary_first_name');
  });

  it('reads the migrations', () => {
    // If this comes back empty the gate is blind to everything added since the
    // types were last regenerated, and it would pass on any of it.
    expect(migrationColumns('builder_stock_items').length).toBeGreaterThan(0);
  });
});

describe('a column is known when EITHER source has it', () => {
  it('accepts one the migrations add and the types predate', () => {
    // Added by `20261019000000_builder_stock_item_work_claim.sql`; the types
    // were last regenerated before it.
    expect(typedColumns('builder_stock_items')).not.toContain('image_work_stage');
    expect(migrationColumns('builder_stock_items')).toContain('image_work_stage');
    expect(knownColumns('builder_stock_items')).toContain('image_work_stage');
  });

  it('accepts one the types carry', () => {
    expect(knownColumns('clients')).toContain('primary_surname');
  });
});

describe('a column is absent only when BOTH sources agree', () => {
  it.each([
    ['investment_reports', 'client_id'],
    ['investment_reports', 'created_by'],
    ['investment_reports', 'quality_score'],
    ['custom_users', 'role_display'],
    ['market_updates', 'summary'],
    ['client_deals', 'deal_name'],
    ['client_deals', 'lender'],
    ['purchase_files', 'loan_amount'],
    ['ghl_client_opportunities', 'contact_email'],
  ])('%s.%s does not exist', (table, column) => {
    expect(knownColumns(table)).not.toContain(column);
  });

  it.each([
    ['investment_reports', 'client_property_id'],
    ['investment_reports', 'generated_by'],
    ['custom_users', 'role'],
    ['market_updates', 'ai_summary'],
    ['client_deals', 'property_address'],
    ['purchase_files', 'max_approved_budget'],
    ['finance_partner_commissions', 'net_amount'],
    ['purchase_file_status_history', 'from_value'],
  ])('and %s.%s — the column the fix uses — does', (table, column) => {
    expect(knownColumns(table)).toContain(column);
  });
});

describe('an unknown table is skipped, never judged', () => {
  it('answers null rather than an empty list', () => {
    // An empty list would report every column of a view or another schema's
    // table as missing; null is what makes the gate skip it.
    expect(knownColumns('a_table_that_does_not_exist_anywhere')).toBeNull();
  });
});

describe('stripping SQL comments', () => {
  it('keeps every offset', () => {
    const sql = "select 1 -- a note\nfrom t;";
    expect(stripSqlComments(sql)).toHaveLength(sql.length);
  });

  it('does not let a comment marker inside a string open a comment', () => {
    const sql = "insert into t values ('/*'); alter table t add column real_one text;";
    expect(stripSqlComments(sql)).toContain('real_one');
  });

  it('handles a nested block comment', () => {
    const sql = '/* outer /* inner */ still comment */ alter table t add column kept text;';
    const out = stripSqlComments(sql);
    expect(out).toContain('kept');
    expect(out).not.toContain('still comment');
  });

  it('skips a dollar-quoted body wholesale', () => {
    const sql = "create function f() returns void as $$ -- not a real comment\n select 1; $$ language sql;";
    expect(stripSqlComments(sql)).toContain('language sql');
  });
});
