/**
 * Reading a property listing out of a fetched page.
 *
 * This is where the missing data actually is. Mining the text the intake
 * pipeline stored recovers almost nothing — measured over 120 real records, of
 * the 60 with no price *none* had a dollar figure anywhere in their stored text,
 * and of the 75 with no bedroom count exactly one mentioned a bedroom. The
 * upstream extractor already took everything those snippets contained.
 *
 * The listing page is a different story. One real record — 13 Larundel Road,
 * which the dashboard currently shows as "Unknown / – / – / – / Price on
 * request" — has a source page carrying **62 property photographs**, six
 * bedrooms, four bathrooms, two car spaces and an 809 m² land size. That is the
 * gap, and 77% of records carry a link to it.
 *
 * No DOM parser is available in the edge runtime and pulling one in for this
 * would be disproportionate, so extraction is regex over the markup. That is
 * fragile in general but sound here, because the shapes being matched are
 * machine-generated by a handful of agency CRM templates rather than hand-written.
 *
 * Pure: no Deno, Supabase, network, DOM or clock.
 */

import { orderImagesPhotosFirst } from './listingImageOrder.pure.ts';
import { looksLikeChromeUrl } from './listingImageChrome.pure.ts';

export interface ScrapedListing {
  imageUrls: string[];
  beds?: number;
  baths?: number;
  carSpaces?: number;
  landSizeSqm?: number;
  buildingAreaSqm?: number;
  priceDisplay?: string;
  priceNumeric?: number;
  title?: string;
  description?: string;
  agentName?: string;
  agentEmail?: string;
  agentPhone?: string;
}

/**
 * Extra hosts that serve property photos without a file extension in the path.
 *
 * `lh3.googleusercontent.com/d/<id>=w1200` is the one that matters most: a real
 * agency site was found serving its entire 62-image gallery from it, and an
 * extension-only test rejected every single one.
 */
const EXTENSIONLESS_IMAGE_HOSTS = [
  'googleusercontent.com',
  'agentboxcdn.com.au',
  'agentbox',
  'vaultre',
  'rexsoftware',
  'reastatic',
  'domainstatic',
  'campaigntrack',
  'consolecloud',
  'cloudinary.com',
  'imgix.net',
  'cloudfront.net',
  'akamaized.net',
  // Reapit/AgentPoint, the platform behind a large slice of Australian agency
  // sites. Photographs are served as `phimg.reapit.website/<sha1>` with no
  // extension at all, so without this entry a page with fourteen photographs
  // yields zero and the listing looks like it has none.
  'reapit.website',
  // Aro, Console, iDashboard and Push Creative — the remaining extension-less
  // property CDNs observed while seeding this corpus.
  'arosoftware.com',
  'idashboard.com.au',
  'pushcreative.com.au',
];

const IMAGE_EXTENSION = /\.(?:jpe?g|png|webp|avif)(?:$|[?#])/i;

/** Whether a URL looks like a photograph of the property rather than page chrome. */
export function isPropertyImageUrl(url: string): boolean {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return false;
  }
  if (parsed.protocol !== 'https:' && parsed.protocol !== 'http:') return false;

  // The furniture list moved to `listingImageChrome.pure.ts`, because filtering
  // here protected only what this scraper produced. Images reaching the library
  // from Airtable or replayed by the browser never passed through it, which is
  // how a 680-byte bed glyph became the hero image on 44 listings.
  if (looksLikeChromeUrl(url)) return false;

  const haystack = `${parsed.hostname}${parsed.pathname}`.toLowerCase();

  // SVGs are icons and logos on these sites, never photographs.
  if (/\.svg(?:$|[?#])/i.test(parsed.pathname)) return false;

  if (IMAGE_EXTENSION.test(parsed.pathname)) return true;
  return EXTENSIONLESS_IMAGE_HOSTS.some((host) => haystack.includes(host));
}

/** Resolves a possibly-relative URL against the page it came from. */
function absolute(url: string, baseUrl: string): string | null {
  const trimmed = url.trim().replace(/^['"]|['"]$/g, '');
  if (!trimmed || trimmed.startsWith('data:')) return null;
  try {
    return new URL(trimmed, baseUrl).toString();
  } catch {
    return null;
  }
}

/**
 * Every image URL on the page, in the order the page presents them.
 *
 * Order matters: the first photograph in a gallery is the one the agent chose as
 * the hero shot, and it becomes the card thumbnail.
 *
 * The attributes are searched in the order galleries actually use them.
 * `data-thumb` and `data-fancybox` come first because lightbox galleries put the
 * full-size image there while `<img src>` holds a low-resolution placeholder —
 * on the real page that was the difference between 62 photographs and 2 logos.
 */
export function extractPageImages(html: string, baseUrl: string, limit = 24): string[] {
  const found: string[] = [];
  const seen = new Set<string>();

  const push = (raw: string | undefined) => {
    if (!raw || found.length >= limit) return;
    const url = absolute(raw, baseUrl);
    if (!url || seen.has(url) || !isPropertyImageUrl(url)) return;
    seen.add(url);
    found.push(url);
  };

  const patterns: RegExp[] = [
    /data-(?:thumb|large_image|full|zoom-image|lazy|original)\s*=\s*["']([^"']+)["']/gi,
    /<a[^>]+data-fancybox[^>]+href\s*=\s*["']([^"']+)["']/gi,
    /<meta[^>]+(?:property|name)\s*=\s*["'](?:og:image(?::secure_url)?|twitter:image)["'][^>]+content\s*=\s*["']([^"']+)["']/gi,
    /<meta[^>]+content\s*=\s*["']([^"']+)["'][^>]+(?:property|name)\s*=\s*["'](?:og:image(?::secure_url)?|twitter:image)["']/gi,
    /background-image\s*:\s*url\(\s*['"]?([^'")]+)['"]?\s*\)/gi,
    /<img[^>]+(?:data-src|src)\s*=\s*["']([^"']+)["']/gi,
    /<source[^>]+srcset\s*=\s*["']([^"'\s,]+)/gi,
  ];

  for (const pattern of patterns) {
    for (const match of html.matchAll(pattern)) push(match[1]);
    if (found.length >= limit) break;
  }

  // Agency galleries frequently lead with the floor plan — the first asset the
  // agent uploaded. Stored order becomes display order downstream, so demote
  // plans here at the source: the hero slot belongs to a photograph.
  return orderImagesPhotosFirst(found, (url) => url);
}

/* -------------------------------------------------------------------------- */
/* Specs                                                                       */
/* -------------------------------------------------------------------------- */

function textOf(html: string): string {
  return html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function firstInt(value: string | undefined, max = 99): number | undefined {
  if (!value) return undefined;
  const match = value.match(/\d{1,3}/);
  if (!match) return undefined;
  const n = Number(match[0]);
  return Number.isFinite(n) && n >= 0 && n <= max ? n : undefined;
}

/**
 * A count read from an element whose class names it.
 *
 * Agency CRM templates mark these up semantically — `<li class="no-of-bed">6`,
 * `<span class="property-beds">4` — and the number is the element's own text.
 * That is far more reliable than looking for "6 bed" in prose, because the same
 * page will also say "bedrooms" in a paragraph about the neighbourhood.
 */
export function extractClassCount(html: string, keywords: string[]): number | undefined {
  for (const keyword of keywords) {
    const pattern = new RegExp(
      `<(\\w+)[^>]*class="[^"]*\\b[\\w-]*${keyword}[\\w-]*\\b[^"]*"[^>]*>([\\s\\S]{0,160}?)</\\1>`,
      'i',
    );
    const match = html.match(pattern);
    const value = firstInt(textOf(match?.[2] ?? ''));
    if (value !== undefined) return value;
  }
  return undefined;
}

/** An area in square metres, from a classed element or labelled prose. */
export function extractArea(html: string, keywords: string[]): number | undefined {
  for (const keyword of keywords) {
    const pattern = new RegExp(
      `<(\\w+)[^>]*class="[^"]*\\b[\\w-]*${keyword}[\\w-]*\\b[^"]*"[^>]*>([\\s\\S]{0,200}?)</\\1>`,
      'i',
    );
    const match = html.match(pattern);
    const area = parseArea(textOf(match?.[2] ?? ''));
    if (area !== undefined) return area;
  }
  return undefined;
}

/** "809 Square Meters", "801sqm", "0.4 ha", "1 acre" → square metres. */
export function parseArea(text: string): number | undefined {
  const match = text.match(
    /(\d[\d,]*(?:\.\d+)?)\s*(sqm|m2|m²|square\s*met(?:re|er)s?|ha\b|hectares?|acres?)/i,
  );
  if (!match) return undefined;
  const amount = Number(match[1].replace(/,/g, ''));
  if (!Number.isFinite(amount) || amount <= 0) return undefined;
  const unit = match[2].toLowerCase();
  if (unit.startsWith('h')) return Math.round(amount * 10_000);
  if (unit.startsWith('ac')) return Math.round(amount * 4046.86);
  return Math.round(amount);
}

/** JSON-LD blocks, flattened — `@graph` is unwrapped so callers see plain nodes. */
export function extractJsonLd(html: string): Array<Record<string, unknown>> {
  const nodes: Array<Record<string, unknown>> = [];
  for (const match of html.matchAll(
    /<script[^>]+type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi,
  )) {
    try {
      const parsed = JSON.parse(match[1].trim());
      const list = Array.isArray(parsed) ? parsed : [parsed];
      for (const entry of list) {
        if (!entry || typeof entry !== 'object') continue;
        const graph = (entry as { '@graph'?: unknown })['@graph'];
        if (Array.isArray(graph)) nodes.push(...(graph as Array<Record<string, unknown>>));
        else nodes.push(entry as Record<string, unknown>);
      }
    } catch {
      // A malformed block is common and not worth failing the whole scrape over.
    }
  }
  return nodes;
}

const PRICE_PATTERN =
  /((?:from|offers?\s+(?:above|over|from)|price\s*guide|guide|starting(?:\s+from)?)\s*)?\$\s?\d[\d,]*(?:\.\d+)?\s*(?:k|m|million)?(?:\s*(?:-|–|to)\s*\$?\s?\d[\d,]*(?:\.\d+)?\s*(?:k|m|million)?)?/i;

/** "$1.59m", "$850k", "$1,599,000" → a number, or undefined. */
export function parseAudAmount(text: string): number | undefined {
  const match = text.match(/\$\s?([\d,]+(?:\.\d+)?)\s*(k|m|million)?/i);
  if (!match) return undefined;
  let amount = Number(match[1].replace(/,/g, ''));
  if (!Number.isFinite(amount)) return undefined;
  const suffix = (match[2] ?? '').toLowerCase();
  if (suffix === 'k') amount *= 1_000;
  else if (suffix === 'm' || suffix === 'million') amount *= 1_000_000;
  return amount > 0 && amount < 50_000_000 ? amount : undefined;
}

/**
 * The agent's own contact details, from the listing page.
 *
 * This is the field with the largest gap after images: only 451 of 1,441
 * records (31%) carry any reachable address, so "email the agent" is unavailable
 * on two thirds of the marketplace. An agency listing page almost always
 * publishes the selling agent's email and mobile, because that is the entire
 * purpose of the page.
 *
 * `mailto:` links are the reliable signal. A bare address in body text is as
 * likely to belong to the office, the webmaster or a franchise footer as to the
 * agent, so only mailto hrefs are read, and the site's own generic inboxes are
 * skipped in favour of a named one where both appear.
 */
export function extractContact(html: string, pageUrl?: string): {
  email?: string;
  phone?: string;
  name?: string;
} {
  const shape = /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/;
  const emails: string[] = [];
  for (const match of html.matchAll(/href\s*=\s*["']mailto:([^"'?]+)/gi)) {
    const email = decodeURIComponent(match[1]).trim().toLowerCase();
    if (shape.test(email)) emails.push(email);
  }

  // Many agency sites route enquiries through a form and publish no mailto at
  // all. An address in the body text is a weaker signal — it could be the
  // webmaster, a franchise footer, or a partner — so it is only accepted when
  // its domain matches the site being read, which is the case that makes it the
  // agency's own.
  if (emails.length === 0 && pageUrl) {
    let host = '';
    try {
      host = new URL(pageUrl).hostname.toLowerCase().replace(/^www\./, '');
    } catch {
      host = '';
    }
    const root = host.split('.').slice(-3).join('.');
    if (root) {
      for (const match of html.matchAll(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g)) {
        const email = match[0].toLowerCase();
        if (!shape.test(email)) continue;
        if (!email.endsWith(`@${root}`) && !email.endsWith(`.${root}`)) continue;
        emails.push(email);
      }
    }
  }

  // A named mailbox is more likely to be the agent than `info@` or `sales@`.
  const generic = /^(info|sales|admin|enquiries|enquiry|contact|office|reception|hello|mail|rentals?|property|web|webmaster|support|accounts|careers)@/i;
  const email = emails.find((candidate) => !generic.test(candidate)) ?? emails[0];

  let phone: string | undefined;
  for (const match of html.matchAll(/href\s*=\s*["']tel:([^"']+)/gi)) {
    const digits = decodeURIComponent(match[1]).replace(/[^\d+]/g, '');
    const national = digits.replace(/^\+?61/, '0').replace(/\D/g, '');
    // A mobile is the useful number; keep looking past a switchboard.
    if (national.length === 10 && national.startsWith('04')) {
      phone = national;
      break;
    }
    if (!phone && national.length >= 8 && national.length <= 10) phone = national;
  }

  return { email, phone };
}

/**
 * The whole listing, read from one fetched page.
 *
 * Everything is optional. A page that yields only photographs is still a good
 * outcome — images are the single largest gap — and a stage that returns
 * nothing must leave the record exactly as it found it.
 */
export function scrapeListingPage(html: string, baseUrl: string): ScrapedListing {
  const result: ScrapedListing = { imageUrls: extractPageImages(html, baseUrl) };

  result.beds = extractClassCount(html, ['no-of-bed', 'bed']);
  result.baths = extractClassCount(html, ['no-of-bath', 'bath']);
  result.carSpaces = extractClassCount(html, ['no-of-car', 'car', 'garage', 'parking']);
  result.landSizeSqm = extractArea(html, ['land-area', 'land-size', 'landsize', 'land']);
  result.buildingAreaSqm = extractArea(html, ['floor-area', 'building-area', 'house-size']);

  // Structured data wins where a site publishes it: it is the site's own
  // assertion rather than our reading of its markup.
  for (const node of extractJsonLd(html)) {
    const offers = node.offers as { price?: unknown; priceCurrency?: unknown } | undefined;
    const price = Number(offers?.price);
    if (Number.isFinite(price) && price > 0 && price < 50_000_000) {
      result.priceNumeric = price;
    }
    const rooms = Number(node.numberOfRooms);
    if (result.beds === undefined && Number.isFinite(rooms) && rooms > 0 && rooms < 50) {
      result.beds = rooms;
    }
    const floorSize = (node.floorSize as { value?: unknown } | undefined)?.value;
    if (result.buildingAreaSqm === undefined && Number.isFinite(Number(floorSize))) {
      result.buildingAreaSqm = Math.round(Number(floorSize));
    }
    if (!result.title && typeof node.name === 'string') result.title = node.name.slice(0, 200);
    if (!result.description && typeof node.description === 'string') {
      result.description = node.description.slice(0, 2000);
    }
  }

  if (result.priceNumeric === undefined || !result.priceDisplay) {
    // Look only inside elements the page itself calls a price, so a "$0 deposit"
    // banner or a stamp-duty figure in the footer cannot be mistaken for one.
    const priceBlock = html.match(
      /<(\w+)[^>]*class="[^"]*\b[\w-]*price[\w-]*\b[^"]*"[^>]*>([\s\S]{0,220}?)<\/\1>/i,
    );
    const text = textOf(priceBlock?.[2] ?? '');
    const match = text.match(PRICE_PATTERN);
    if (match) {
      result.priceDisplay ??= match[0].trim().replace(/\s+/g, ' ');
      result.priceNumeric ??= parseAudAmount(match[0]);
    }
  }

  const contact = extractContact(html, baseUrl);
  if (contact.email) result.agentEmail = contact.email;
  if (contact.phone) result.agentPhone = contact.phone;

  if (!result.description) {
    const meta = html.match(
      /<meta[^>]+(?:property|name)\s*=\s*["'](?:og:description|description)["'][^>]+content\s*=\s*["']([^"']+)["']/i,
    );
    if (meta) result.description = meta[1].slice(0, 2000);
  }

  return result;
}
