import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import {
  AUSTRALIAN_STATES,
  DUTY_SCHEDULES,
  calculateStampDuty,
  validateSchedule,
  type AustralianState,
  type DutySchedule,
} from '@/utils/stampDutyCalculator';

/**
 * The migration seeds `stamp_duty_rates_cache` with the shipped schedules, and
 * the cache is served in preference to them. If the two ever disagree, the
 * product quotes one set of numbers in the browser and another in the Edge
 * Function — which is exactly the class of bug this whole change removes.
 *
 * The seed is generated by `scripts/stampDuty/generate-seed.ts`, so this test is
 * really checking that somebody regenerated it after editing the rates.
 */

const MIGRATION = resolve(
  __dirname,
  '../../../supabase/migrations/20260810000000_stamp_duty_schedule_cache.sql',
);

function seededSchedules(): Map<AustralianState, DutySchedule> {
  const sql = readFileSync(MIGRATION, 'utf8');
  const seeded = new Map<AustralianState, DutySchedule>();

  // Rows look like:  ('NSW', '{...}'::jsonb, 'built_in', 'https://…', '…'::date)
  for (const match of sql.matchAll(/\('([A-Z]{2,3})',\s*'(\{.*?\})'::jsonb/gs)) {
    const [, state, json] = match;
    seeded.set(state as AustralianState, JSON.parse(json.replace(/''/g, "'")) as DutySchedule);
  }

  return seeded;
}

describe('seeded cache parity', () => {
  const seeded = seededSchedules();

  it('seeds every jurisdiction', () => {
    expect([...seeded.keys()].sort()).toEqual([...AUSTRALIAN_STATES].sort());
  });

  it.each(AUSTRALIAN_STATES)('%s seed matches the shipped schedule exactly', (state) => {
    // Round-tripped through JSON so `undefined` optional fields compare equal to
    // absent ones, which is what the database will actually hold.
    const shipped = JSON.parse(JSON.stringify(DUTY_SCHEDULES[state]));
    expect(seeded.get(state)).toEqual(shipped);
  });

  it.each(AUSTRALIAN_STATES)('%s seed passes the same validation as the shipped schedule', (state) => {
    const schedule = seeded.get(state);
    expect(schedule).toBeDefined();
    expect(validateSchedule(schedule as DutySchedule)).toEqual([]);
  });

  it.each(AUSTRALIAN_STATES)('%s seed assesses identical duty across the price range', (state) => {
    const schedule = seeded.get(state) as DutySchedule;
    for (const propertyValue of [350_000, 650_000, 900_000, 1_400_000, 2_500_000, 4_200_000]) {
      for (const intent of ['owner_occupier', 'investor'] as const) {
        const fromSeed = calculateStampDuty({ propertyValue, state, intent, schedule });
        const fromCode = calculateStampDuty({ propertyValue, state, intent });
        expect(fromSeed.totalDuty, `${state} ${intent} at $${propertyValue}`).toBe(fromCode.totalDuty);
      }
    }
  });

  it('marks every seeded row as built_in rather than as a served override', () => {
    const sql = readFileSync(MIGRATION, 'utf8');
    // An override is a deliberate human act; the seed must never create one.
    expect(sql).not.toMatch(/'override'\s*,\s*'https/);
    expect((sql.match(/::jsonb,\s*'built_in'/g) ?? []).length).toBe(AUSTRALIAN_STATES.length);
  });
});
