import { fireEvent,render,screen,waitFor,within } from '@testing-library/react';
import { QueryClient,QueryClientProvider } from '@tanstack/react-query';
import { beforeEach,describe,expect,it,vi } from 'vitest';
import * as XLSX from 'xlsx';
import { toast } from 'sonner';
import { AddClientModal } from '../AddClientModal';
import { LIVING_EXPENSE_ITEMS } from '@/lib/client-fact-find/fieldDefinitions';
import { secureStorageUpload } from '@/hooks/useSecureStorage';
class TestResizeObserver { observe() {} unobserve() {} disconnect() {} }
Object.defineProperty(globalThis,'ResizeObserver',{writable:true,value:TestResizeObserver});
const invoke=vi.fn();
vi.mock('@/lib/secureInvoke',()=>({invokeSecureFunction:(...args:unknown[])=>invoke(...args)}));
vi.mock('@/hooks/useActivityLogger',()=>({logActivityDirect:vi.fn()}));
vi.mock('@/hooks/useSecureStorage',()=>({secureStorageUpload:vi.fn().mockResolvedValue({success:true,path:'client-1/import.xlsx'})}));
vi.mock('sonner',()=>({toast:{success:vi.fn(),warning:vi.fn(),error:vi.fn()}}));
vi.mock('@/branding/useBrand',()=>({useBrand:()=>({settings:{id:'11111111-1111-4111-8111-111111111111',companyName:'Aurixa Test',primaryColor:'#' + '12345B',accentColor:'#' + 'C9A227',sidebarLogo:null,authLogo:null,emailSignature:{email:'hello@aurixa.test',phone:'0400 000 000',website:'aurixa.test',address:'Sydney'}}})}));
function setup(props:{open?:boolean;onOpenChange?:(v:boolean)=>void}={}){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});const onOpenChange=props.onOpenChange??vi.fn();const view=render(<QueryClientProvider client={client}><AddClientModal open={props.open??true} onOpenChange={onOpenChange}/></QueryClientProvider>);return {...view,client,onOpenChange}}
function clickTab(name:string){const tab=screen.getByRole('tab',{name});fireEvent.click(tab);fireEvent.mouseDown(tab,{button:0,ctrlKey:false})}
function advanced(){clickTab('Advanced')}
function factSection(name:string){clickTab(name)}
function activePanel(){return within(document.querySelector<HTMLElement>('[role=tabpanel][data-visible=true]')!)}
function input(label:string,value:string){fireEvent.change(activePanel().getByLabelText(label),{target:{value}})}
function advancedField(name:string){return document.querySelector<HTMLInputElement>(`[name="${name}"]`)!}
function completedWorkbookFile(){
 const book=XLSX.utils.book_new(),fact=XLSX.utils.aoa_to_sheet([]),expenses=XLSX.utils.aoa_to_sheet([]);
 const put=(address:string,value:string|number,format?:string)=>{fact[address]={t:typeof value==='number'?'n':'s',v:value,...format?{z:format}:{}} as XLSX.CellObject};
 const applicants=[['Ms','Avery','Louise','Nguyen','15/04/1987','Female','Married','Citizen',2,'0412345678','avery@example.test'],['Mr','Jordan','Kai','Nguyen','20 Aug 1985','Male','Married','Permanent Resident',1,'0498765432','jordan@example.test']] as const;
 applicants.forEach((values,index)=>values.forEach((value,row)=>put(`${index?'H':'C'}${row+6}`,value)));
 Object.entries({C19:'11 Harbour Street',C20:'Owned',C22:'9 Former Road',C23:'Renting',C24:'05/06/2018',H19:'22 Garden Avenue',H20:'Mortgaged',H21:'01 Sep 2020',H22:'7 Previous Parade',H23:'Boarding',C27:'Permanent',C28:'Aurixa Systems',C29:'Director',C30:'100 Business Boulevard',C31:'12/03/2019',C32:'$140,000.50',C33:'$12,500',C34:3200.25,C35:1750,C36:900,H27:'Self-employed',H28:'Nguyen Studio',H29:'Designer',H30:'200 Creative Crescent',H32:'$95,000',H33:4500,H34:2750,H35:1250,H36:600}).forEach(([address,value])=>put(address,value));
 put('C21',44927,'dd/mm/yyyy');put('H24',43101,'dd/mm/yyyy');put('H31',43831,'dd/mm/yyyy');
 for(let index=0;index<10;index++){const row=40+index;put(`A${row}`,`Imported Asset ${index+1}`);put(`B${row}`,`${index+1} Asset Avenue`);put(`C${row}`,index%2?'Jordan':'Avery');put(`D${row}`,index===0?'$100,000.25':(index+1)*100000);put(`E${row}`,(index+1)*500.5);put(`F${row}`,`Asset Bank ${index+1}`);put(`G${row}`,(index+1)*25000);put(`H${row}`,(index+1)*750.25);put(`I${row}`,0.05+index/1000,'0.0%');put(`J${row}`,`${String(index+1).padStart(2,'0')}/12/203${index}`)}
 for(let index=0;index<8;index++){const row=53+index;put(`A${row}`,`Imported Liability ${index+1}`);put(`B${row}`,`Lender ${index+1}`);put(`C${row}`,`Account 00${index+1}`);put(`D${row}`,index%2?'Jordan':'Avery');put(`E${row}`,index===0?'$20,000.75':(index+1)*20000);put(`F${row}`,(index+1)*1000.5);put(`G${row}`,(index+1)*125.25);put(`H${row}`,0.12+index/100,'0.0%');put(`I${row}`,`${index+2} years`);put(`J${row}`,`Liability note ${index+1}`)}
 fact['!ref']='A1:J60';
 LIVING_EXPENSE_ITEMS.forEach((item,index)=>{const row=index+5;expenses[`A${row}`]={t:'s',v:item.category};expenses[`B${row}`]={t:'s',v:item.itemLabel};expenses[`C${row}`]={t:'n',v:index+1};expenses[`D${row}`]={t:'s',v:`Imported note ${index+1}`};});expenses['!ref']='A1:D55';
 XLSX.utils.book_append_sheet(book,fact,'Client Fact Find');XLSX.utils.book_append_sheet(book,expenses,'Living Expenses');
 const bytes=XLSX.write(book,{type:'array',bookType:'xlsx'}) as ArrayBuffer,file=new File([bytes],'completed-client-fact-find.xlsx',{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});Object.defineProperty(file,'arrayBuffer',{value:async()=>bytes});return file;
}
function dropWorkbook(file:File){fireEvent.drop(screen.getByTestId('excel-dropzone'),{dataTransfer:{files:[file],items:[{kind:'file',type:file.type,getAsFile:()=>file}],types:['Files']}})}
beforeEach(()=>{invoke.mockReset();vi.mocked(secureStorageUpload).mockClear();vi.mocked(toast.success).mockClear();vi.mocked(toast.warning).mockClear();vi.mocked(toast.error).mockClear();invoke.mockImplementation(async(name:string)=>name==='manage-automation-settings'?{data:{success:true,pipelines:[],stages:[]},error:null}:{data:{success:true},error:null})});
describe('Add Client modes',()=>{
 it('defaults to Standard and retains all legacy fields',()=>{setup();expect(screen.getByRole('tab',{name:'Standard'})).toHaveAttribute('aria-selected','true');for(const label of ['First Name *','Surname *','Current Address','Sync to GoHighLevel after creating'])expect(activePanel().getByLabelText(label)).toBeInTheDocument()});
 it('keeps Standard creation on manage-client-data and the existing GHL sequence',async()=>{const calls:string[]=[];invoke.mockImplementation(async(name:string)=>{calls.push(name);if(name==='manage-automation-settings')return {data:{success:true,pipelines:[],stages:[]},error:null};if(name==='manage-client-data')return {data:{success:true,result:{id:'standard-1'}},error:null};if(name==='sync-client-to-ghl')return {data:{success:true},error:null};return {data:{},error:null}});setup();fireEvent.change(screen.getByLabelText('First Name *'),{target:{value:'Alex'}});fireEvent.change(screen.getByLabelText('Surname *'),{target:{value:'Smith'}});fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(calls).toContain('sync-client-to-ghl'));expect(calls).toContain('manage-client-data');expect(calls).not.toContain('create-advanced-client');expect(calls.indexOf('manage-client-data')).toBeLessThan(calls.indexOf('sync-client-to-ghl'))});
 it('renders exactly four Advanced sections and removes White Label Setup',()=>{setup();advanced();expect(screen.getAllByRole('tab').filter(tab=>['Excel Import','Client Fact Find','Living Expenses','Client Form Output'].includes(tab.textContent||'')).map(tab=>tab.textContent)).toEqual(['Excel Import','Client Fact Find','Living Expenses','Client Form Output']);expect(screen.queryByRole('tab',{name:'White Label Setup'})).not.toBeInTheDocument()});
 it('resets Advanced state after close and reopen',()=>{const onOpenChange=vi.fn();const view=setup({onOpenChange});advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText('First Name')[0],{target:{value:'Temporary'}});fireEvent.click(screen.getByRole('button',{name:'Cancel'}));view.rerender(<QueryClientProvider client={view.client}><AddClientModal open={false} onOpenChange={onOpenChange}/></QueryClientProvider>);view.rerender(<QueryClientProvider client={view.client}><AddClientModal open onOpenChange={onOpenChange}/></QueryClientProvider>);advanced();clickTab('Client Fact Find');expect(activePanel().getAllByLabelText('First Name')[0]).toHaveValue('')});
 it('renders one initial asset, one initial liability, and one continuous 50-row expense worksheet',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Assets');expect(screen.getAllByTestId('asset-card')).toHaveLength(1);factSection('Liabilities');expect(screen.queryAllByTestId('asset-card')).toHaveLength(0);expect(screen.getAllByTestId('liability-card')).toHaveLength(1);clickTab('Living Expenses');expect(screen.getAllByTestId('expense-row')).toHaveLength(50);const list=screen.getByTestId('expense-continuous-list');expect(list).toBeInTheDocument();expect(list).toHaveClass('overflow-hidden');expect(list).not.toHaveClass('overflow-x-auto');expect(screen.getAllByTestId('expense-list-header')).toHaveLength(1);for(const heading of ['Category','Expense Item','Monthly Amount','Notes'])expect(screen.getByTestId('expense-list-header')).toHaveTextContent(heading);expect(activePanel().getByLabelText('Higher Education / Vocational Training monthly amount')).toHaveValue(0)});
 it('updates asset, debt, applicant income, expense, and output totals from live state',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Employment & Income');fireEvent.change(activePanel().getAllByLabelText('Base Salary — Annual')[0],{target:{value:'50000'}});factSection('Assets');input('Asset 1 Current Value','1000');input('Asset 1 Loan Balance','400');factSection('Liabilities');input('Liability 1 Current Balance','100');expect(screen.getAllByText('$1,000.00').length).toBeGreaterThan(0);expect(screen.getAllByText('$50,000.00').length).toBeGreaterThan(0);clickTab('Living Expenses');input('Childcare monthly amount','250');expect(screen.getAllByText('$250.00').length).toBeGreaterThan(0);clickTab('Client Form Output');expect(screen.getByTestId('output-living-expenses')).toHaveTextContent('$250.00');expect(screen.getAllByText('$500.00').length).toBeGreaterThan(0)});
 it('shows a negative net position with the shared formatter',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Liabilities');input('Liability 1 Current Balance','10');clickTab('Client Form Output');expect(screen.getAllByText('-$10.00').length).toBeGreaterThan(0)});
 it('opens incomplete current values directly in output and returns to the previous form tab',()=>{setup();advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText('Email')[1],{target:{value:'second@example.com'}});fireEvent.click(screen.getByRole('button',{name:'Review Output'}));expect(screen.getByTestId('client-output-preview')).toHaveTextContent('second@example.com');expect(screen.getByTestId('client-output-preview')).toHaveTextContent('—');fireEvent.click(screen.getByRole('button',{name:'Back to Form'}));expect(screen.getByRole('tab',{name:'Client Fact Find'})).toHaveAttribute('data-state','active')});
 it('reviews a valid local form in the read-only output without making requests',async()=>{setup();advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText(/First Name/)[0],{target:{value:'Alex'}});fireEvent.change(activePanel().getAllByLabelText(/Surname/)[0],{target:{value:'Smith'}});invoke.mockClear();fireEvent.click(screen.getByRole('button',{name:'Review Output'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Client Form Output'})).toHaveAttribute('data-state','active'));expect(screen.getByTestId('client-output-preview')).toHaveTextContent('Alex Smith');expect(screen.getByTestId('client-output-preview').querySelectorAll('input,select,textarea')).toHaveLength(0);expect(invoke).not.toHaveBeenCalled()});
 it('does not render document colour controls or colour output text',()=>{setup();advanced();expect(activePanel().queryByText('Primary Colour')).not.toBeInTheDocument();expect(activePanel().queryByText('Accent Colour')).not.toBeInTheDocument();expect(activePanel().queryByLabelText(/picker/i)).not.toBeInTheDocument();expect(activePanel().queryByLabelText(/hex value/i)).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Review Output'}));expect(screen.getByTestId('client-output-preview')).not.toHaveTextContent(/Primary|Accent/)});
 it('renders the output as exactly five ordered unbranded sections from Portfolio Summary to Declaration',()=>{setup();advanced();fireEvent.click(screen.getByRole('button',{name:'Review Output'}));const output=screen.getByTestId('client-output-preview'),sections=Array.from(output.querySelectorAll<HTMLElement>('[data-output-section]'));expect(sections.map(section=>section.dataset.outputSection)).toEqual(['Portfolio Summary','Applicant Details','Employment & Income','Financial Summary','Declaration']);expect(sections[0]).toHaveTextContent(/^Portfolio Summary/);expect(sections.at(-1)).toHaveTextContent(/^Declaration/);for(const branding of ['Organisation','Trading Name','Confidentiality','Document Title','Prepared By','Version','Website','Business Address','Logo'])expect(output).not.toHaveTextContent(branding)});
 it('ends the Declaration after its wording with no signature or date placeholders',()=>{setup();advanced();fireEvent.click(screen.getByRole('button',{name:'Review Output'}));const declaration=screen.getByTestId('client-output-preview').querySelector<HTMLElement>('[data-output-section="Declaration"]')!;expect(declaration).not.toHaveTextContent('Client Signature');expect(declaration).not.toHaveTextContent('Date:');expect(declaration).not.toHaveTextContent('__________________________');expect(declaration).not.toHaveTextContent('____ / ____ / ______');expect(declaration.lastElementChild?.tagName).toBe('P')});
 it('exposes Advanced Create Client without GHL controls',()=>{setup();advanced();expect(screen.getByRole('button',{name:'Create Client'})).toBeInTheDocument();expect(activePanel().queryByLabelText(/GoHighLevel/i)).not.toBeInTheDocument()});
 it('renders the local Excel import surface and Vite-managed template download',()=>{setup();advanced();expect(screen.getByTestId('excel-import-tab')).toBeInTheDocument();expect(screen.getByTestId('excel-dropzone')).toHaveTextContent('.xlsx or .xls');const link=screen.getByRole('link',{name:/Download Template/});expect(link.getAttribute('href')?.startsWith('data:')).toBe(true);expect(link.getAttribute('href')).not.toContain('/assets/');expect(link).toHaveAttribute('download','Aurixa-Systems-Client-Fact-Find-Template.xlsx')});
 it('parses, applies and visibly exposes every mapped workbook column across the editable Advanced form',async()=>{
  setup();advanced();invoke.mockClear();dropWorkbook(completedWorkbookFile());await screen.findByText('completed-client-fact-find.xlsx');expect(screen.queryByText('Import successful')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Review Imported Data'})).not.toBeInTheDocument();expect(invoke).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Parse Excel Sheet'}));await screen.findByText('Import successful');for(const summary of ['Applicants found','Address records found','Employment records found','Assets populated','Liabilities populated','Living expenses populated','Warning count'])expect(screen.getByText(summary)).toBeInTheDocument();expect(invoke).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Review Imported Data'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Client Fact Find'})).toHaveAttribute('data-state','active'));
  expect(screen.getByTestId('applicant-card-1')).toHaveTextContent('Ms');expect(screen.getByTestId('applicant-card-2')).toHaveTextContent('Mr');
  const applicants:Record<string,string|number>={'applicants.0.firstName':'Avery','applicants.0.middleName':'Louise','applicants.0.surname':'Nguyen','applicants.0.dateOfBirth':'1987-04-15','applicants.0.gender':'Female','applicants.0.maritalStatus':'Married','applicants.0.residencyStatus':'Citizen','applicants.0.numberOfDependants':2,'applicants.0.mobile':'0412345678','applicants.0.email':'avery@example.test','applicants.1.firstName':'Jordan','applicants.1.middleName':'Kai','applicants.1.surname':'Nguyen','applicants.1.dateOfBirth':'1985-08-20','applicants.1.gender':'Male','applicants.1.maritalStatus':'Married','applicants.1.residencyStatus':'Permanent Resident','applicants.1.numberOfDependants':1,'applicants.1.mobile':'0498765432','applicants.1.email':'jordan@example.test'};for(const [name,value] of Object.entries(applicants))expect(advancedField(name)).toHaveValue(value);
  factSection('Address History');const addresses={'addresses.0.address':'11 Harbour Street','addresses.0.movedInDate':'2023-01-01','addresses.1.address':'9 Former Road','addresses.1.movedInDate':'2018-06-05','addresses.2.address':'22 Garden Avenue','addresses.2.movedInDate':'2020-09-01','addresses.3.address':'7 Previous Parade','addresses.3.movedInDate':'2018-01-01'};for(const [name,value] of Object.entries(addresses))expect(advancedField(name)).toHaveValue(value);expect(activePanel().getAllByRole('combobox').map(field=>field.textContent)).toEqual(['Owned','Renting','Mortgaged','Boarding']);
  factSection('Employment & Income');const employment:Record<string,string|number>={'employment.0.employmentType':'Permanent','employment.0.employerOrBusiness':'Aurixa Systems','employment.0.roleOrPosition':'Director','employment.0.employerAddress':'100 Business Boulevard','employment.0.startDate':'2019-03-12','employment.0.baseSalary':140000.5,'employment.0.bonus':12500,'employment.0.commission':3200.25,'employment.0.overtime':1750,'employment.0.otherTaxableIncome':900,'employment.1.employmentType':'Self-employed','employment.1.employerOrBusiness':'Nguyen Studio','employment.1.roleOrPosition':'Designer','employment.1.employerAddress':'200 Creative Crescent','employment.1.startDate':'2020-01-01','employment.1.baseSalary':95000,'employment.1.bonus':4500,'employment.1.commission':2750,'employment.1.overtime':1250,'employment.1.otherTaxableIncome':600};for(const [name,value] of Object.entries(employment))expect(advancedField(name)).toHaveValue(value);
  factSection('Assets');expect(screen.getAllByTestId('asset-card')).toHaveLength(10);const assets:Record<string,string|number>={'Asset 1 Asset Type':'Imported Asset 1','Asset 1 Description / Address':'1 Asset Avenue','Asset 1 Owner':'Avery','Asset 1 Current Value':100000.25,'Asset 1 Rental / Other Income':500.5,'Asset 1 Financial Institution':'Asset Bank 1','Asset 1 Loan Balance':25000,'Asset 1 Monthly Repayment':750.25,'Asset 1 Interest Rate':5,'Asset 1 Maturity Date':'2030-12-01','Asset 10 Asset Type':'Imported Asset 10','Asset 10 Description / Address':'10 Asset Avenue','Asset 10 Owner':'Jordan','Asset 10 Current Value':1000000,'Asset 10 Rental / Other Income':5005,'Asset 10 Financial Institution':'Asset Bank 10','Asset 10 Loan Balance':250000,'Asset 10 Monthly Repayment':7502.5,'Asset 10 Interest Rate':5.9,'Asset 10 Maturity Date':'2039-12-10'};for(const [label,value] of Object.entries(assets))expect(activePanel().getByLabelText(label)).toHaveValue(value);
  factSection('Liabilities');expect(screen.getAllByTestId('liability-card')).toHaveLength(8);const liabilities:Record<string,string|number>={'Liability 1 Liability Type':'Imported Liability 1','Liability 1 Lender':'Lender 1','Liability 1 Account / Description':'Account 001','Liability 1 Owner':'Avery','Liability 1 Limit / Original Amount':20000.75,'Liability 1 Current Balance':1000.5,'Liability 1 Monthly Repayment':125.25,'Liability 1 Interest Rate':12,'Liability 1 Remaining Term':'2 years','Liability 1 Notes':'Liability note 1','Liability 8 Liability Type':'Imported Liability 8','Liability 8 Lender':'Lender 8','Liability 8 Account / Description':'Account 008','Liability 8 Owner':'Jordan','Liability 8 Limit / Original Amount':160000,'Liability 8 Current Balance':8004,'Liability 8 Monthly Repayment':1002,'Liability 8 Interest Rate':19,'Liability 8 Remaining Term':'9 years','Liability 8 Notes':'Liability note 8'};for(const [label,value] of Object.entries(liabilities))expect(activePanel().getByLabelText(label)).toHaveValue(value);
  clickTab('Living Expenses');expect(screen.getAllByTestId('expense-row')).toHaveLength(50);expect(activePanel().getByLabelText('Childcare monthly amount')).toHaveValue(1);expect(activePanel().getByLabelText('Other Regular Expense monthly amount')).toHaveValue(50);expect(activePanel().getByLabelText('Other Regular Expense notes')).toHaveValue('Imported note 50');input('Childcare monthly amount','321');clickTab('Client Form Output');expect(screen.getByTestId('client-output-preview')).toHaveTextContent('Avery Louise Nguyen');expect(screen.getByTestId('client-output-preview')).toHaveTextContent('Aurixa Systems');expect(screen.getByTestId('output-living-expenses')).toHaveTextContent('$1,595.00');expect(invoke).not.toHaveBeenCalled();
 });

  it('validates Advanced required names and navigates to Applicants without creating',async()=>{setup();advanced();invoke.mockClear();fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Client Fact Find'})).toHaveAttribute('data-state','active'));expect(screen.getByRole('tab',{name:'Applicants'})).toHaveAttribute('aria-selected','true');expect(screen.getByTestId('fact-find-sticky-navigation')).toHaveClass('sticky','top-0','z-20');expect(screen.getByText('Primary first name is required')).toBeInTheDocument();expect(invoke).not.toHaveBeenCalled()});
 it('navigates to Employment and does not create a client for an unsupported imported type',async()=>{setup();advanced();clickTab('Client Fact Find');fireEvent.change(advancedField('applicants.0.firstName'),{target:{value:'Alex'}});fireEvent.change(advancedField('applicants.0.surname'),{target:{value:'Smith'}});factSection('Employment & Income');fireEvent.change(advancedField('employment.0.employmentType'),{target:{value:'Unemployed'}});fireEvent.change(advancedField('employment.0.employerOrBusiness'),{target:{value:'Example'}});invoke.mockClear();vi.mocked(toast.error).mockClear();fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(toast.error).toHaveBeenCalledWith(expect.stringContaining('Employment type "Unemployed" is not supported')));expect(screen.getByRole('tab',{name:'Employment & Income'})).toHaveAttribute('aria-selected','true');expect(invoke).not.toHaveBeenCalled()});
 it('creates an Advanced client from parsed values without attaching the original workbook',async()=>{const calls:any[]=[];invoke.mockImplementation(async(name:string,body:any)=>{calls.push([name,body]);if(body?.table==='clients'&&body.operation==='create')return {data:{success:true,result:{id:'advanced-1'}},error:null};return {data:{success:true,result:{id:'saved'}},error:null}});const {onOpenChange}=setup();advanced();dropWorkbook(completedWorkbookFile());await screen.findByText('completed-client-fact-find.xlsx');fireEvent.click(screen.getByRole('button',{name:'Parse Excel Sheet'}));await screen.findByText('Import successful');fireEvent.click(screen.getByRole('button',{name:'Review Imported Data'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Client Fact Find'})).toHaveAttribute('data-state','active'));fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(onOpenChange).toHaveBeenCalledWith(false));expect(secureStorageUpload).not.toHaveBeenCalled();expect(calls.filter(([,body])=>body?.table==='client_files')).toHaveLength(0);expect(calls).toEqual(expect.arrayContaining([expect.arrayContaining(['manage-client-data',expect.objectContaining({table:'client_employment',data:expect.objectContaining({employer_name:'Aurixa Systems'})})]),expect.arrayContaining(['manage-client-data',expect.objectContaining({table:'client_assets',data:expect.objectContaining({value:100000.25})})]),expect.arrayContaining(['manage-client-data',expect.objectContaining({table:'client_expenses',data:expect.objectContaining({monthly_amount:1})})])]));expect(toast.success).toHaveBeenCalledWith('Client created successfully.');expect(toast.warning).not.toHaveBeenCalled();expect(toast.success).not.toHaveBeenCalledWith(expect.stringContaining('workbook attached'))});
 it('retries only failed Advanced records without duplicating the client, successful records, or GHL sync',async()=>{let employmentAttempts=0;const calls:any[]=[];invoke.mockImplementation(async(name:string,body:any)=>{calls.push([name,body]);if(name!=='manage-client-data')return {data:{success:true},error:null};if(body.table==='clients'&&body.operation==='create')return {data:{success:true,result:{id:'advanced-1'}},error:null};if(body.table==='client_employment'&&employmentAttempts++===0)return {data:{success:false,error:'invalid employment type'},error:null};return {data:{success:true,result:{id:'saved'}},error:null}});const {onOpenChange}=setup();advanced();dropWorkbook(completedWorkbookFile());await screen.findByText('completed-client-fact-find.xlsx');fireEvent.click(screen.getByRole('button',{name:'Parse Excel Sheet'}));await screen.findByText('Import successful');fireEvent.click(screen.getByRole('button',{name:'Review Imported Data'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Client Fact Find'})).toHaveAttribute('data-state','active'));fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(employmentAttempts).toBe(2));const firstCallCount=calls.length;expect(onOpenChange).not.toHaveBeenCalledWith(false);clickTab('Excel Import');expect(screen.getByText('completed-client-fact-find.xlsx')).toBeInTheDocument();clickTab('Client Fact Find');fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(onOpenChange).toHaveBeenCalledWith(false));const creates=calls.filter(([,body])=>body?.table==='clients'&&body.operation==='create');expect(creates).toHaveLength(1);expect(calls.filter(([,body])=>body?.table==='client_files')).toHaveLength(0);expect(secureStorageUpload).not.toHaveBeenCalled();expect(calls.slice(firstCallCount).filter(([,body])=>body?.table==='client_employment')).toHaveLength(1);expect(calls.slice(firstCallCount).filter(([,body])=>body?.table&&body.table!=='client_employment')).toHaveLength(0);expect(calls.some(([name])=>name==='sync-client-to-ghl')).toBe(false)});
 it('renders the premium Advanced workspace structure and icon tabs',()=>{setup();advanced();expect(screen.getByTestId('add-client-premium-header')).toBeInTheDocument();expect(screen.getByTestId('premium-mode-tabs')).toBeInTheDocument();expect(screen.getByTestId('advanced-navigation')).toBeInTheDocument();for(const key of ['excel','fact-find','expenses','output'])expect(screen.getByTestId(`advanced-tab-icon-${key}`)).toBeInTheDocument();expect(screen.getByTestId('advanced-content-scroll')).toBeInTheDocument()});
 it('keeps the footer outside the scroll region with all three Advanced actions',()=>{setup();advanced();const footer=screen.getByTestId('advanced-footer'),scroll=screen.getByTestId('advanced-content-scroll');expect(scroll.contains(footer)).toBe(false);expect(within(footer).getAllByRole('button')).toHaveLength(3);for(const name of ['Cancel','Review Output','Create Client'])expect(within(footer).getByRole('button',{name})).toBeVisible()});
  it('mounts only the selected one of five internal Fact Find sections',()=>{setup();advanced();clickTab('Client Fact Find');for(const name of ['Applicants','Address History','Employment & Income','Assets','Liabilities'])expect(screen.getByRole('tab',{name})).toBeInTheDocument();expect(screen.getByRole('tab',{name:'Applicants'})).toHaveAttribute('aria-selected','true');const navigation=screen.getByTestId('fact-find-sticky-navigation');expect(navigation).toHaveClass('sticky','top-0','z-20','pb-3');expect(navigation.className).not.toMatch(/-mt-6|lg:-mt-8/);expect(navigation.compareDocumentPosition(screen.getByTestId('fact-find-summary'))&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.getByTestId('applicant-card-2')).toBeInTheDocument();expect(screen.queryByTestId('assets-table')).not.toBeInTheDocument();factSection('Address History');expect(screen.getByText('Applicant 1 Address History')).toBeInTheDocument();expect(screen.queryByTestId('applicant-card-1')).not.toBeInTheDocument();factSection('Employment & Income');expect(screen.getByText('Applicant 1 Employment and Income')).toBeInTheDocument();expect(screen.queryByTestId('assets-table')).not.toBeInTheDocument()});
 it('preserves applicant and asset values across unmounting sections',()=>{setup();advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText('First Name')[0],{target:{value:'Alex'}});factSection('Assets');input('Asset 1 Current Value','123');factSection('Applicants');expect(activePanel().getAllByLabelText('First Name')[0]).toHaveValue('Alex');factSection('Assets');expect(activePanel().getByLabelText('Asset 1 Current Value')).toHaveValue(123)});
 it('uses responsive cards without horizontal scroll regions',()=>{setup();advanced();clickTab('Client Fact Find');expect(screen.getByTestId('applicant-responsive-grid')).toHaveClass('xl:grid-cols-2');expect(screen.getByTestId('applicant-card-2')).toHaveTextContent('Optional');factSection('Assets');expect(screen.getAllByTestId('asset-card')).toHaveLength(1);expect(screen.queryByTestId('assets-horizontal-scroll')).not.toBeInTheDocument();factSection('Liabilities');expect(screen.getAllByTestId('liability-card')).toHaveLength(1);expect(screen.queryByTestId('liabilities-horizontal-scroll')).not.toBeInTheDocument()});
 it('resets only the modal content scroll position when switching internal sections',()=>{setup();advanced();clickTab('Client Fact Find');const scroll=screen.getByTestId('advanced-content-scroll');scroll.scrollTop=240;factSection('Assets');expect(scroll.scrollTop).toBe(0)});
 it('does not validate or redirect Review Output when values are invalid',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Assets');input('Asset 1 Current Value','-1');fireEvent.click(screen.getByRole('button',{name:'Review Output'}));expect(screen.getByRole('tab',{name:'Client Form Output'})).toHaveAttribute('data-state','active');expect(screen.getByTestId('client-output-preview')).toBeInTheDocument()});
 it('adds dynamic assets beyond the workbook limit and preserves existing values',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Assets');input('Asset 1 Asset Type','Home');for(let index=0;index<11;index++)fireEvent.click(screen.getByRole('button',{name:'Add Asset'}));expect(screen.getAllByTestId('asset-card')).toHaveLength(12);expect(activePanel().getByLabelText('Asset 1 Asset Type')).toHaveValue('Home');expect(activePanel().getByLabelText('Asset 12 Asset Type')).toHaveFocus()});
 it('adds liabilities beyond the workbook limit',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Liabilities');for(let index=0;index<9;index++)fireEvent.click(screen.getByRole('button',{name:'Add Liability'}));expect(screen.getAllByTestId('liability-card')).toHaveLength(10)});
 it('removes blank assets immediately, confirms populated assets, and reindexes remaining values',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Assets');fireEvent.click(screen.getByRole('button',{name:'Add Asset'}));input('Asset 2 Asset Type','Shares');fireEvent.click(screen.getByRole('button',{name:'Remove Asset 1'}));expect(screen.getAllByTestId('asset-card')).toHaveLength(1);expect(activePanel().getByLabelText('Asset 1 Asset Type')).toHaveValue('Shares');fireEvent.click(screen.getByRole('button',{name:'Remove Asset 1'}));expect(screen.getByText('Remove this asset and all information entered for it?')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Remove'}));expect(screen.getAllByTestId('asset-card')).toHaveLength(1);expect(activePanel().getByLabelText('Asset 1 Asset Type')).toHaveValue('')});
 it('confirms populated liability removal and leaves a clean final entry',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Liabilities');input('Liability 1 Lender','Bank');fireEvent.click(screen.getByRole('button',{name:'Remove Liability 1'}));expect(screen.getByText('Remove this liability and all information entered for it?')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Remove'}));expect(screen.getAllByTestId('liability-card')).toHaveLength(1);expect(activePanel().getByLabelText('Liability 1 Lender')).toHaveValue('')});
 it('substantially limits mounted inputs to the active internal section',()=>{const count=()=>screen.getByRole('tabpanel',{name:/Applicants|Address History|Employment & Income|Assets|Liabilities/}).querySelectorAll('input').length;setup();advanced();clickTab('Client Fact Find');expect(count()).toBe(20);factSection('Address History');expect(count()).toBe(8);factSection('Employment & Income');expect(count()).toBe(20);factSection('Assets');expect(count()).toBe(11);factSection('Liabilities');expect(count()).toBe(11)});
});
