import { readFileSync } from 'node:fs';
import { describe,expect,it } from 'vitest';
const read=(name:string)=>readFileSync(new URL(name,import.meta.url),'utf8');
describe('Client Fact Find subscription boundaries',()=>{
 it('keeps the structural tab free of broad form subscriptions',()=>{const source=read('./ClientFactFindTab.tsx');expect(source).not.toContain('useWatch');expect(source).not.toContain('useFormContext');expect(source).toContain('<FactFindSummary/>')});
 it('watches only calculation inputs in isolated totals',()=>{const summary=read('./FactFindSummary.tsx'),watchers=read('./factFindWatchers.ts');expect(summary).toContain("name:'assets'");expect(summary).toContain("name:'liabilities'");expect(watchers).toContain("'baseSalary','bonus','commission','overtime','otherTaxableIncome'");expect(summary).toContain('calculateAssetTotalsCents(assets)');expect(summary).toContain('calculateOtherLiabilitiesCents(liabilities)');for(const unrelated of ['descriptionOrAddress','rentalOrOtherIncome','monthlyRepayment','notes'])expect(watchers).not.toContain(unrelated)});
 it('isolates table totals and memoizes stable uncontrolled rows',()=>{const assets=read('./AssetsTable.tsx'),liabilities=read('./LiabilitiesTable.tsx');expect(assets).toContain("name: 'assets'");expect(liabilities).toContain("name: 'liabilities'");expect(assets).toContain('memo(function AssetRow');expect(liabilities).toContain('memo(function LiabilityRow');expect(assets).toContain('register(`assets.');expect(liabilities).toContain('register(`liabilities.')});
 it('subscribes FormField validation to its exact field name',()=>{const source=read('./FormField.tsx');expect(source).toContain('useFormState({ control, name, exact: true })');expect(source).not.toContain('formState: { errors }')});
 it('conditionally mounts one internal section and uses native scrolling',()=>{const tab=read('./ClientFactFindTab.tsx'),form=read('./AdvancedClientForm.tsx');for(const section of ['applicants','addresses','employment','assets','liabilities'])expect(tab).toContain(`section==='${section}'`);expect(form).not.toContain("@/components/ui/scroll-area");expect(form).toContain('overflow-y-auto overflow-x-hidden overscroll-contain');expect(form).toContain('[scrollbar-gutter:stable]')});
 it('guards repeated Advanced creation clicks with processing state',()=>{const form=read('./AdvancedClientForm.tsx');expect(form).toContain('if(creating)return');expect(form).toContain('disabled={creating}');expect(form).toContain("creating?'Creating Client…':'Create Client'")});
 it('applies imports with one reset and opens Client Fact Find without broad form watches',()=>{const form=read('./AdvancedClientForm.tsx');expect(form).toContain('methods.reset(parsed.payload)');expect(form).toContain("setTab('fact-find')");expect(form).not.toContain('methods.setValue');expect(form).not.toContain('methods.watch(')});
 it('creates from the latest edited React Hook Form state rather than a parsed snapshot',()=>{const form=read('./AdvancedClientForm.tsx');expect(form).toContain('const payload=methods.getValues()');expect(form.indexOf('const payload=methods.getValues()')).toBeLessThan(form.indexOf('saveAdvancedViewClientData(clientId,payload'))});
 it('uses responsive cards and removes horizontal overflow implementations',()=>{for(const file of ['./AssetsTable.tsx','./LiabilitiesTable.tsx']){const source=read(file);expect(source).toContain('grid-cols-1');expect(source).not.toContain('overflow-x-auto');expect(source).not.toContain('min-w-[1420px]');expect(source).not.toContain('shadow-inner');expect(source).not.toContain('sticky top-0');expect(source).not.toContain('ScrollArea')}});
});
