import type { ReactNode } from 'react';
import { useFormContext } from 'react-hook-form';
import { ArrowLeft, BriefcaseBusiness, CircleDollarSign, FileCheck2, Users, type LucideIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { AdvancedClientCreationPayload } from '@/lib/client-fact-find/types';
import { advSubCard } from './advancedTheme';
import { calculateFactFindTotals, centsToDisplay, formatNetPosition, fullApplicantName } from '@/lib/client-fact-find/calculations';

const DECLARATION = "The information contained in this fact find has been provided for the purpose of assessing the client's financial position and coordinating with authorised finance and property professionals. It does not constitute credit assistance, financial product advice or legal advice. The client should verify all information before relying on the generated document.";

export function ClientFormOutputTab({ onBack }: { onBack: () => void }) {
  const { getValues } = useFormContext<AdvancedClientCreationPayload>();
  const values = getValues();
  const totals = calculateFactFindTotals(values);
  return <div className="space-y-4">
    <Button type="button" variant="outline" className="rounded-lg border-border/60" onClick={onBack}><ArrowLeft className="mr-2 h-4 w-4" />Back to Form</Button>
    <article data-testid="client-output-preview" aria-label="Client form snapshot" className="mx-auto max-w-5xl overflow-hidden rounded-2xl border border-border/55 bg-card shadow-[0_28px_60px_-34px_hsl(var(--background))]">
      <OutputSection title="Portfolio Summary" icon={CircleDollarSign} first><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Total Assets" value={centsToDisplay(totals.totalAssetsCents)} /><Summary label="Total Debt" value={centsToDisplay(totals.totalDebtCents)} /><Summary label="Net Position" value={formatNetPosition(totals.netPositionCents)} /><Summary label="Monthly Living Expenses" value={centsToDisplay(totals.totalMonthlyLivingExpensesCents)} testId="output-living-expenses" /></div></OutputSection>
      <OutputSection title="Applicant Details" icon={Users}><div className="grid gap-4 lg:grid-cols-2">{values.applicants.map(applicant => { const address = values.addresses.find(item => item.applicantNumber === applicant.applicantNumber && item.addressType === 'current'); return <SnapshotCard title={`Applicant ${applicant.applicantNumber}${applicant.applicantNumber === 2 ? ' · Optional' : ''}`} key={applicant.applicantNumber}><Detail label="Full Name" value={fullApplicantName(applicant)} /><Detail label="Date of Birth" value={applicant.dateOfBirth || ''} /><Detail label="Mobile" value={applicant.mobile} /><Detail label="Email" value={applicant.email} /><Detail label="Current Address" value={address?.address || ''} /><Detail label="Living Situation" value={address?.livingSituation || ''} /></SnapshotCard>; })}</div></OutputSection>
      <OutputSection title="Employment & Income" icon={BriefcaseBusiness}><div className="grid gap-4 lg:grid-cols-2">{values.applicants.map((applicant, index) => { const employment = values.employment.find(item => item.applicantNumber === applicant.applicantNumber); const income = index === 0 ? totals.applicant1AnnualIncomeCents : totals.applicant2AnnualIncomeCents; return <SnapshotCard title={`Applicant ${applicant.applicantNumber}`} key={applicant.applicantNumber}><Detail label="Employment Type" value={employment?.employmentType || ''} /><Detail label="Employer / Business" value={employment?.employerOrBusiness || ''} /><Detail label="Role / Position" value={employment?.roleOrPosition || ''} /><Detail label="Start Date" value={employment?.startDate || ''} /><Detail label="Total Annual Income" value={centsToDisplay(income)} /></SnapshotCard>; })}</div></OutputSection>
      <OutputSection title="Financial Summary" icon={FileCheck2}><dl className="overflow-hidden rounded-xl border border-border/55"><SummaryRow label="Total Assets" value={centsToDisplay(totals.totalAssetsCents)} /><SummaryRow label="Asset-Linked Debt" value={centsToDisplay(totals.totalAssetLinkedDebtCents)} /><SummaryRow label="Other Liabilities" value={centsToDisplay(totals.totalOtherLiabilitiesCents)} /><SummaryRow label="Total Debt" value={centsToDisplay(totals.totalDebtCents)} /><SummaryRow label="Monthly Living Expenses" value={centsToDisplay(totals.totalMonthlyLivingExpensesCents)} /><SummaryRow label="Net Position" value={formatNetPosition(totals.netPositionCents)} /></dl></OutputSection>
      <OutputSection title="Declaration" icon={FileCheck2} last><p className="text-sm leading-6 text-muted-foreground">{DECLARATION}</p></OutputSection>
    </article>
  </div>;
}

function OutputSection({ title, icon: Icon, children, first = false, last = false }: { title: string; icon: LucideIcon; children: ReactNode; first?: boolean; last?: boolean }) { return <section data-output-section={title} className={`p-5 sm:p-7 ${first ? 'bg-primary/[0.06]' : 'border-t border-border/45'} ${last ? 'bg-background/40' : ''}`}><div className="mb-5 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg border border-brand-300/25 bg-primary/10 text-brand-200"><Icon className="h-4 w-4" aria-hidden="true" /></span><h2 className="text-lg font-semibold sm:text-xl">{title}</h2></div>{children}</section>; }
function SnapshotCard({ title, children }: { title: string; children: ReactNode }) { return <div className={`${advSubCard} p-4`}><h3 className="font-semibold">{title}</h3><dl className="mt-3 grid grid-cols-1 gap-3 text-sm sm:grid-cols-2">{children}</dl></div>; }
function Summary({ label, value, testId }: { label: string; value: string; testId?: string }) { const negative = label === 'Net Position' && value.startsWith('-'); return <div className="rounded-xl border border-border/55 bg-background/45 p-4"><p className="text-xs text-muted-foreground">{label}</p><p data-testid={testId} className={`mt-1 text-lg font-semibold ${negative ? 'text-destructive' : ''}`}>{value}</p></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-0.5 break-words">{value || '—'}</dd></div>; }
function SummaryRow({ label, value }: { label: string; value: string }) { const negative = label === 'Net Position' && value.startsWith('-'); return <div className="flex justify-between gap-4 border-b border-border/70 px-4 py-3.5 odd:bg-muted/15 last:border-0"><dt>{label}</dt><dd className={`text-right font-semibold ${negative ? 'text-destructive' : ''}`}>{value}</dd></div>; }
