import { useCallback, useRef, useState } from 'react';
import { AlertTriangle, CheckCircle2, Download, FileSpreadsheet, Loader2, Trash2, UploadCloud } from 'lucide-react';
import { useDropzone } from 'react-dropzone';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { EXCEL_ACCEPT, MAX_EXCEL_FILE_BYTES, parseAdvancedClientWorkbookFile, validateExcelFile, type ParsedExcelImport } from '@/lib/client-fact-find/excelImport';
import { advEyebrow, advPanelHeader, advSurface } from './advancedTheme';
import advancedClientTemplateUrl from '../../../../docs/reference/Aurixa Systems - White Label Client Fact Find Template.xlsx?inline';

export function ExcelImportTab({file,onFileChange,hasFormValues,onApply}:{file:File|null;onFileChange:(file:File|null)=>void;hasFormValues:boolean;onApply:(parsed:ParsedExcelImport)=>void}){
  const [parsed,setParsed]=useState<ParsedExcelImport|null>(null),[error,setError]=useState(''),[parsing,setParsing]=useState(false),[confirm,setConfirm]=useState(false);
  const parseRun=useRef(0);
  const select=useCallback((files:File[])=>{const next=files[0];if(!next)return;parseRun.current+=1;const invalid=validateExcelFile(next);setParsed(null);setError('');setParsing(false);setConfirm(false);if(invalid){onFileChange(null);setError(invalid);return}onFileChange(next)},[onFileChange]);
  const parseSelectedWorkbook=async()=>{if(!file||parsing)return;const run=++parseRun.current;setParsing(true);setParsed(null);setError('');try{const result=await parseAdvancedClientWorkbookFile(file);if(run!==parseRun.current)return;if(result.fatalErrors.length){setError(result.fatalErrors.join(' '));return}setParsed(result)}catch{if(run===parseRun.current)setError('The workbook could not be imported. Confirm that it is a valid Excel workbook.')}finally{if(run===parseRun.current)setParsing(false)}};
  const {getRootProps,getInputProps,isDragActive,open}=useDropzone({accept:EXCEL_ACCEPT,maxFiles:1,multiple:false,maxSize:MAX_EXCEL_FILE_BYTES,noClick:true,onDropAccepted:select,onDropRejected:rejections=>{parseRun.current+=1;const candidate=rejections[0]?.file;setParsed(null);setParsing(false);setConfirm(false);onFileChange(null);setError(candidate?.size>MAX_EXCEL_FILE_BYTES?'The workbook is larger than the 10 MB maximum.':'Unsupported file type. Select an .xlsx or .xls workbook.')}});
  const clear=()=>{parseRun.current+=1;setParsed(null);setError('');setParsing(false);setConfirm(false);onFileChange(null)};
  const apply=()=>{if(!parsed)return;if(hasFormValues){setConfirm(true);return}onApply(parsed)};
  return <div className="space-y-4" data-testid="excel-import-tab">
    <Card className={advSurface}><CardHeader className={`flex flex-col items-start justify-between gap-4 sm:flex-row ${advPanelHeader}`}><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-brand-300/25 bg-primary/10 text-brand-200"><FileSpreadsheet className="h-5 w-5"/></span><div><p className={advEyebrow}>Document processing</p><CardTitle className="mt-0.5">Excel Import</CardTitle><p className="mt-2 text-sm text-muted-foreground">Download the original template, complete it, then import one workbook locally. Nothing is uploaded until you create the client.</p></div></div><Button asChild variant="outline" className="min-h-11 w-full shrink-0 rounded-lg border-brand-300/30 hover:bg-primary/10 sm:w-auto"><a href={advancedClientTemplateUrl} download="Aurixa-Systems-Client-Fact-Find-Template.xlsx"><Download className="mr-2 h-4 w-4"/>Download Template</a></Button></CardHeader>
      <CardContent><div {...getRootProps()} data-testid="excel-dropzone" className={`group flex min-h-52 flex-col items-center justify-center rounded-xl border border-dashed p-5 text-center transition-[background-color,border-color] duration-150 motion-reduce:transition-none ${isDragActive?'border-brand-300/70 bg-primary/15':'border-border/60 bg-background/40 hover:border-brand-300/40 hover:bg-background/70'}`}><input {...getInputProps()} aria-label="Excel workbook"/><span className="flex h-14 w-14 items-center justify-center rounded-xl border border-brand-300/25 bg-primary/10 transition-transform duration-150 group-hover:-translate-y-0.5 motion-reduce:transform-none motion-reduce:transition-none"><UploadCloud className="h-6 w-6 text-brand-200"/></span><p className="mt-3 font-semibold">Drag and drop an Excel workbook here</p><p className="mt-1 text-sm text-muted-foreground">.xlsx or .xls · one file · maximum 10 MB</p><Button type="button" variant="secondary" className="mt-4 min-h-11 rounded-xl border border-brand-300/20" onClick={open}>Browse Files</Button></div></CardContent>
    </Card>
    {error&&<div role="alert" className="flex gap-2 rounded-xl border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive"><AlertTriangle className="h-4 w-4 shrink-0"/>{error}</div>}
    {file&&<Card className={advSurface}><CardHeader className={advPanelHeader}><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-success/25 bg-success-light text-success"><FileSpreadsheet className="h-5 w-5"/></span><div><CardTitle className="text-base">{parsed?'Import successful':'Workbook selected'}</CardTitle><p className="text-xs text-muted-foreground">{file.type||'Microsoft Excel workbook'}</p></div></div><dl className="grid gap-1 text-sm"><div><dt className="inline text-muted-foreground">Filename: </dt><dd className="inline break-all font-medium">{file.name}</dd></div><div><dt className="inline text-muted-foreground">File size: </dt><dd className="inline font-medium">{(file.size/1024).toFixed(1)} KB</dd></div></dl></CardHeader><CardContent className="space-y-4">{parsed&&<><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-7"><Summary label="Applicants found" value={parsed.summary.applicantsFound}/><Summary label="Address records found" value={parsed.summary.addressesFound}/><Summary label="Employment records found" value={parsed.summary.employmentRecordsFound}/><Summary label="Assets populated" value={parsed.summary.assetsPopulated}/><Summary label="Liabilities populated" value={parsed.summary.liabilitiesPopulated}/><Summary label="Living expenses populated" value={parsed.summary.livingExpensesPopulated}/><Summary label="Warning count" value={parsed.summary.warnings}/></div>{parsed.warnings.length>0&&<div><p className="text-sm font-semibold">Import warnings</p><ul className="mt-1 list-disc pl-5 text-sm text-muted-foreground">{parsed.warnings.map((warning,index)=><li key={`${index}-${warning}`}>{warning}</li>)}</ul></div>}</>}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={clear}><Trash2 className="mr-2 h-4 w-4"/>Clear File</Button><Button type="button" variant={parsed?'outline':'default'} onClick={parseSelectedWorkbook} disabled={parsing}>{parsing&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}{parsing?'Parsing Excel Sheet…':parsed?'Parse Again':'Parse Excel Sheet'}</Button>{parsed&&<Button type="button" onClick={apply}><CheckCircle2 className="mr-2 h-4 w-4"/>Review Imported Data</Button>}</div></CardContent></Card>}
    <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Replace Advanced form values?</AlertDialogTitle><AlertDialogDescription>Importing this workbook will replace the current Advanced form values.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>{if(parsed)onApply(parsed)}}>Import and Replace</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>
}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-lg border border-border/55 bg-background/45 p-2.5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-bold tabular-nums">{value}</p></div>}
