import { useState } from 'react';
import { fireEvent,render,screen,waitFor } from '@testing-library/react';
import * as XLSX from 'xlsx';
import { afterEach,describe,expect,it,vi } from 'vitest';
import * as excelImport from '@/lib/client-fact-find/excelImport';
import type { ParsedExcelImport } from '@/lib/client-fact-find/excelImport';
import { ExcelImportTab } from './ExcelImportTab';

function workbook(){const book=XLSX.utils.book_new(),fact=XLSX.utils.aoa_to_sheet([]),expenses=XLSX.utils.aoa_to_sheet([]);Object.assign(fact,{C7:{t:'s',v:'Alex'},C9:{t:'s',v:'Smith'},C28:{t:'s',v:'Aurixa'},H7:{t:'s',v:'Taylor'},H9:{t:'s',v:'Nguyen'},H19:{t:'s',v:'9 Ocean Drive'},H28:{t:'s',v:'Formara'},A40:{t:'s',v:'Savings'},D40:{t:'n',v:1000}});fact['!ref']='A1:J60';Object.assign(expenses,{A5:{t:'s',v:'Childcare & Support'},B5:{t:'s',v:'Childcare'},C5:{t:'n',v:125}});expenses['!ref']='A1:D55';XLSX.utils.book_append_sheet(book,fact,'Client Fact Find');XLSX.utils.book_append_sheet(book,expenses,'Living Expenses');return XLSX.write(book,{type:'array',bookType:'xlsx'}) as ArrayBuffer}
function Harness({onApply=vi.fn(),hasFormValues=false}:{onApply?:(parsed:ParsedExcelImport)=>void;hasFormValues?:boolean}){const [file,setFile]=useState<File|null>(null);return <ExcelImportTab file={file} onFileChange={setFile} hasFormValues={hasFormValues} onApply={onApply}/>}
function file(name='completed.xlsx'){const bytes=workbook(),next=new File([bytes],name,{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});Object.defineProperty(next,'arrayBuffer',{value:async()=>bytes});return next}
function drop(next=file()){fireEvent.drop(screen.getByTestId('excel-dropzone'),{dataTransfer:{files:[next],items:[{kind:'file',type:next.type,getAsFile:()=>next}],types:['Files']}})}
async function parse(){fireEvent.click(await screen.findByRole('button',{name:'Parse Excel Sheet'}));await screen.findByText('Import successful')}

afterEach(()=>vi.restoreAllMocks());
describe('ExcelImportTab',()=>{
  it('stores a valid workbook without parsing until Parse Excel Sheet is clicked',async()=>{const original=excelImport.parseAdvancedClientWorkbookFile,parser=vi.spyOn(excelImport,'parseAdvancedClientWorkbookFile').mockImplementation(original);render(<Harness/>);expect(screen.queryByRole('button',{name:'Parse Excel Sheet'})).not.toBeInTheDocument();drop();expect(await screen.findByText('completed.xlsx')).toBeInTheDocument();expect(screen.getByText('Workbook selected')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Parse Excel Sheet'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Review Imported Data'})).not.toBeInTheDocument();expect(parser).not.toHaveBeenCalled();await parse();expect(parser).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Parse Again'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Review Imported Data'})).toBeInTheDocument()});

  it('disables parsing and prevents duplicate clicks while the workbook is processing',async()=>{let resolve!:(value:ParsedExcelImport)=>void;const original=excelImport.parseAdvancedClientWorkbookFile,pending=new Promise<ParsedExcelImport>(done=>{resolve=done}),parser=vi.spyOn(excelImport,'parseAdvancedClientWorkbookFile').mockReturnValue(pending);render(<Harness/>);drop();const button=await screen.findByRole('button',{name:'Parse Excel Sheet'});fireEvent.click(button);const parsing=screen.getByRole('button',{name:'Parsing Excel Sheet…'});expect(parsing).toBeDisabled();fireEvent.click(parsing);expect(parser).toHaveBeenCalledTimes(1);resolve(await original(file('result.xlsx')));await waitFor(()=>expect(screen.getByText('Import successful')).toBeInTheDocument())});

  it('shows a parsing error, permits retry, and clears all state',async()=>{const original=excelImport.parseAdvancedClientWorkbookFile,parser=vi.spyOn(excelImport,'parseAdvancedClientWorkbookFile').mockRejectedValueOnce(new Error('broken')).mockImplementation(original);render(<Harness/>);drop();fireEvent.click(await screen.findByRole('button',{name:'Parse Excel Sheet'}));expect(await screen.findByRole('alert')).toHaveTextContent('The workbook could not be imported');expect(screen.getByRole('button',{name:'Parse Excel Sheet'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:'Parse Excel Sheet'}));await screen.findByText('Import successful');expect(parser).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('button',{name:'Clear File'}));expect(screen.queryByText('completed.xlsx')).not.toBeInTheDocument();expect(screen.queryByText('Import successful')).not.toBeInTheDocument();expect(screen.queryByRole('alert')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Parse (Excel Sheet|Again)/})).not.toBeInTheDocument()});

  it('requires a newly selected workbook to be parsed again',async()=>{render(<Harness/>);drop();await parse();expect(screen.getByRole('button',{name:'Review Imported Data'})).toBeInTheDocument();drop(file('replacement.xlsx'));expect(await screen.findByText('replacement.xlsx')).toBeInTheDocument();expect(screen.getByText('Workbook selected')).toBeInTheDocument();expect(screen.queryByText('Import successful')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Review Imported Data'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Parse Excel Sheet'})).toBeInTheDocument()});

  it('applies the complete editable payload only after review',async()=>{const onApply=vi.fn();render(<Harness onApply={onApply}/>);drop();await parse();expect(onApply).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Review Imported Data'}));expect(onApply).toHaveBeenCalledTimes(1);expect(onApply.mock.calls[0][0].payload.applicants[0]).toMatchObject({firstName:'Alex',surname:'Smith'});expect(onApply.mock.calls[0][0].payload.employment[0].employerOrBusiness).toBe('Aurixa');expect(onApply.mock.calls[0][0].payload.assets[0].currentValue).toBe(1000);expect(onApply.mock.calls[0][0].payload.expenses[0].monthlyAmount).toBe(125)});

  it('offers the embedded template download with the official filename',()=>{render(<Harness/>);const link=screen.getByRole('link',{name:/Download Template/});expect(link).toHaveAttribute('download','Aurixa-Systems-Client-Fact-Find-Template.xlsx');const href=link.getAttribute('href')??'';expect(href.startsWith('data:')).toBe(true);expect(href).not.toContain('/assets/')});

  it('parses applicant 1 from column C and applicant 2 from column H',async()=>{const onApply=vi.fn();render(<Harness onApply={onApply}/>);drop();await parse();fireEvent.click(screen.getByRole('button',{name:'Review Imported Data'}));const payload=onApply.mock.calls[0][0].payload;expect(payload.applicants[0]).toMatchObject({firstName:'Alex',surname:'Smith'});expect(payload.applicants[1]).toMatchObject({firstName:'Taylor',surname:'Nguyen'});expect(payload.employment[1].employerOrBusiness).toBe('Formara');expect(payload.addresses.find(item=>item.applicantNumber===2&&item.addressType==='current')?.address).toBe('9 Ocean Drive')});

  it('requires confirmation before replacing entered form values',async()=>{const onApply=vi.fn();render(<Harness onApply={onApply} hasFormValues/>);drop();await parse();fireEvent.click(screen.getByRole('button',{name:'Review Imported Data'}));expect(screen.getByText('Importing this workbook will replace the current Advanced form values.')).toBeInTheDocument();expect(onApply).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Import and Replace'}));expect(onApply).toHaveBeenCalledTimes(1)});
});
