import { useMemo } from 'react';
import { useFormContext,useWatch } from 'react-hook-form';
import type { AdvancedClientCreationPayload,FactFindEmployment } from '@/lib/client-fact-find/types';
import { calculateAssetTotalsCents,calculateIncomeCents,calculateOtherLiabilitiesCents,centsToDisplay,formatNetPosition } from '@/lib/client-fact-find/calculations';
import { INCOME_KEYS,incomeNames } from './factFindWatchers';
import { advEyebrow,advPanelHeader,advSurface } from './advancedTheme';

const INCOME_NAMES=[...incomeNames(0),...incomeNames(1)] as const;
export function FactFindSummary(){const {control}=useFormContext<AdvancedClientCreationPayload>();const incomeValues=useWatch({control,name:INCOME_NAMES});const assets=useWatch({control,name:'assets'})??[];const liabilities=useWatch({control,name:'liabilities'})??[];const totals=useMemo(()=>{let offset=0;const employment=()=>Object.fromEntries(INCOME_KEYS.map(key=>[key,incomeValues[offset++]])) as Pick<FactFindEmployment,typeof INCOME_KEYS[number]>;const applicant1=employment(),applicant2=employment();const assetTotals=calculateAssetTotalsCents(assets);const other=calculateOtherLiabilitiesCents(liabilities);const debt=assetTotals.totalAssetLinkedDebtCents+other;return {income1:calculateIncomeCents(applicant1),income2:calculateIncomeCents(applicant2),assets:assetTotals.totalAssetsCents,debt,net:assetTotals.totalAssetsCents-debt}},[incomeValues,assets,liabilities]);return <section data-testid="fact-find-summary" className={`${advSurface} min-w-0`} aria-label="Fact find summary"><div className={`px-4 py-2 ${advPanelHeader}`}><p className={advEyebrow}>Financial position snapshot</p></div><div className="grid grid-cols-2 lg:grid-cols-5"><Kpi label="Applicant 1 Income" value={centsToDisplay(totals.income1)}/><Kpi label="Applicant 2 Income" value={centsToDisplay(totals.income2)}/><Kpi label="Total Assets" value={centsToDisplay(totals.assets)} positive/><Kpi label="Total Debt" value={centsToDisplay(totals.debt)}/><Kpi label="Net Position" value={formatNetPosition(totals.net)} negative={totals.net<0} emphasis/></div></section>}
function Kpi({label,value,negative=false,positive=false,emphasis=false}:{label:string;value:string;negative?:boolean;positive?:boolean;emphasis?:boolean}){return <div className={`min-w-0 border-border/45 px-4 py-3.5 [&:not(:nth-child(2n+1))]:border-l lg:[&:not(:first-child)]:border-l ${emphasis?'col-span-2 bg-primary/10 lg:col-span-1':''}`}><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">{label}</p><p className={`mt-1 truncate text-base font-bold tabular-nums sm:text-lg ${negative?'text-destructive':positive?'text-success':'text-foreground'}`}>{value}</p></div>}
