import { useState } from 'react';
import { Sparkles, UserPlus } from 'lucide-react';
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { cn } from '@/lib/utils';
import { StandardAddClientForm } from './add-client/StandardAddClientForm';
import { AdvancedClientForm } from './add-client/AdvancedClientForm';

interface AddClientModalProps { open:boolean; onOpenChange:(open:boolean)=>void }
type ClientMode='standard'|'advanced';
export function AddClientModal({open,onOpenChange}:AddClientModalProps){const [mode,setMode]=useState<ClientMode>('standard');const [session,setSession]=useState(0);const close=()=>{setMode('standard');setSession(x=>x+1);onOpenChange(false)};return <Dialog open={open} onOpenChange={isOpen=>{if(!isOpen)close();else onOpenChange(true)}}><DialogContent data-testid="add-client-modal-shell" className={cn('flex w-[calc(100vw-1rem)] flex-col gap-0 overflow-hidden border-border/60 bg-card p-0 shadow-[0_40px_90px_-30px_hsl(var(--background))] transition-[max-width,height] duration-150 motion-reduce:transition-none',mode==='advanced'?'h-[min(94vh,940px)] max-h-[calc(100vh-0.75rem)] sm:max-w-[min(96vw,1480px)] sm:rounded-[1.35rem]':'max-h-[90vh] sm:max-w-[680px] sm:rounded-[1.35rem]')}>
 <DialogHeader data-testid="add-client-premium-header" className="relative shrink-0 overflow-hidden border-b border-border/50 bg-card px-5 py-4 text-left sm:px-6"><div aria-hidden="true" className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-brand-300/60 to-transparent"/><div className="relative flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-brand-300/35 bg-primary/10 text-brand-200"><UserPlus className="h-5 w-5"/></span><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Client onboarding</p><DialogTitle className="text-xl font-bold tracking-tight">Add New Client</DialogTitle><DialogDescription className="mt-0.5 text-sm leading-5 text-muted-foreground">{mode==='standard'?'Create a new client record. Optionally sync to GoHighLevel.':'Review an unsaved Client Financial Position & Fact Find preview.'}</DialogDescription></div></div><ModeTabs mode={mode} onChange={setMode}/></div></DialogHeader>
 <div id="client-mode-panel-standard" role="tabpanel" aria-labelledby="client-mode-tab-standard" hidden={mode!=='standard'} className="min-h-0 flex-1 flex-col data-[visible=true]:flex" data-visible={mode==='standard'}><StandardAddClientForm key={`standard-${session}`} active={open&&mode==='standard'} onCancel={close} onCreated={close}/></div><div id="client-mode-panel-advanced" role="tabpanel" aria-labelledby="client-mode-tab-advanced" hidden={mode!=='advanced'} className="min-h-0 flex-1 flex-col data-[visible=true]:flex" data-visible={mode==='advanced'}><AdvancedClientForm key={`advanced-${session}`} active={open&&mode==='advanced'} onCancel={close}/></div></DialogContent></Dialog>}

function ModeTabs({mode,onChange}:{mode:ClientMode;onChange:(mode:ClientMode)=>void}){const modes:ClientMode[]=['standard','advanced'];const keyDown=(event:React.KeyboardEvent<HTMLDivElement>)=>{const current=modes.indexOf(mode);let next=current;if(event.key==='ArrowRight')next=(current+1)%modes.length;else if(event.key==='ArrowLeft')next=(current-1+modes.length)%modes.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=modes.length-1;else return;event.preventDefault();onChange(modes[next]);requestAnimationFrame(()=>document.getElementById(`client-mode-tab-${modes[next]}`)?.focus())};return <div data-testid="premium-mode-tabs" role="tablist" aria-label="Client creation mode" onKeyDown={keyDown} className="grid shrink-0 grid-cols-2 rounded-xl border border-border/60 bg-background/60 p-1 sm:min-w-64">{modes.map(value=><button type="button" role="tab" id={`client-mode-tab-${value}`} aria-controls={`client-mode-panel-${value}`} aria-selected={mode===value} tabIndex={mode===value?0:-1} onClick={()=>onChange(value)} className="relative flex min-h-10 items-center justify-center gap-2 rounded-lg border border-transparent px-4 text-sm font-semibold text-muted-foreground transition-[background-color,border-color,color] duration-150 hover:bg-background hover:text-foreground motion-reduce:transition-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-card aria-selected:border-brand-300/45 aria-selected:bg-primary/15 aria-selected:text-foreground" key={value}>{value==='advanced'&&<Sparkles className="h-4 w-4"/>}{value==='standard'?'Standard':'Advanced'}</button>)}</div>}
