import assert from 'node:assert/strict'; import { readFileSync } from 'node:fs'; import test from 'node:test';
const read=p=>readFileSync(p,'utf8'); const sql=read('supabase/migrations/20260730210000_transaction_case_backbone_phase5.sql'); const admin=read('supabase/functions/legal-matters-admin/index.ts'); const ui=read('src/components/admin/solicitor-portal/TransactionCasesPanel.tsx');
test('backbone retains separate legal, finance and deal links',()=>{for(const table of ['transaction_cases','transaction_case_links','transaction_case_link_history','transaction_case_reconciliation_issues']) assert.ok(sql.includes(`public.${table}`));for(const column of ['legal_matter_id','purchase_file_id','client_deal_id']) assert.ok(sql.includes(column));});
test('database blocks cross-client and multi-case links',()=>{assert.match(sql,/guard_transaction_case_links/);assert.match(sql,/CROSS_CLIENT_CASE_LINK/);assert.match(sql,/DOMAIN_RECORD_ALREADY_LINKED/);assert.match(sql,/case_id uuid NOT NULL UNIQUE/);});
test('backfill uses only explicit and reverse identifiers, never address matching',()=>{assert.match(sql,/legacy_explicit/);assert.match(sql,/legacy_reverse/);assert.doesNotMatch(sql,/property_address_normalized\s*=/);assert.match(sql,/transaction_case_reconciliation_issues/);});
test('link changes are versioned, atomic, audited and maintain compatibility columns',()=>{assert.match(sql,/FOR UPDATE/);assert.match(sql,/STALE_VERSION/);assert.match(sql,/transaction_case_link_history/);assert.match(sql,/Compatibility adapter/);assert.match(sql,/row_version=row_version\+1/);});
test('Command Centre exposes case list, health and guarded commands behind a feature flag',()=>{for(const op of ['list_transaction_cases','get_transaction_case','create_transaction_case','link_transaction_case_record','unlink_transaction_case_record']) assert.ok(admin.includes(op));assert.match(admin,/TRANSACTION_CASES_V1/);assert.match(admin,/409/);});
test('workspace displays identity, domain health, issues and link history',()=>{for(const text of ['Transaction cases','domain_statuses','Reconciliation','Link history']) assert.ok(ui.includes(text));});
test('case tables and commands are service-role only',()=>{assert.match(sql,/REVOKE ALL ON public\.transaction_cases/);assert.match(sql,/FROM PUBLIC,anon,authenticated/);assert.match(sql,/TO service_role/);});
