import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const app=fs.readFileSync('src/App.tsx','utf8'),layout=fs.readFileSync('src/components/solicitor-portal/SolicitorPortalLayout.tsx','utf8'),guard=fs.readFileSync('src/components/solicitor-portal/SolicitorPortalProtectedRoute.tsx','utf8'),queries=fs.readFileSync('src/lib/solicitorQueries.ts','utf8'),matters=fs.readFileSync('src/pages/solicitor/SolicitorMatters.tsx','utf8'),detail=fs.readFileSync('src/pages/solicitor/SolicitorMatterDetail.tsx','utf8'),api=fs.readFileSync('supabase/functions/solicitor-portal-matters/index.ts','utf8'),realtime=fs.readFileSync('src/components/solicitor-portal/SolicitorRealtimeBridge.tsx','utf8');
test('one nested protected layout owns the solicitor workspace',()=>{assert.match(app,/element={<SolicitorPortalProtectedRoute \/>}/);assert.match(app,/element={<SolicitorPortalLayout \/>}/);assert.match(layout,/<Outlet \/>/);assert.match(guard,/<Outlet \/>/);assert.doesNotMatch(app,/SolicitorPortalProtectedRoute>\s*<Solicitor/)});
test('all required nested workspace routes exist',()=>{for(const route of ['matters','pipeline','matters/:matterId','messages','tasks','notifications','settings'])assert.match(app,new RegExp(`path="${route.replace('/','\\/')}"`))});
test('stable query keys and cancellation-aware queries own server state',()=>{for(const key of ['session','matters','matter','milestones','documents','conversations'])assert.match(queries,new RegExp(`${key}:`));assert.match(queries,/\{signal\}/);assert.match(fs.readFileSync('src/lib/solicitorPortal.ts','utf8'),/signal: options\.signal/);assert.match(queries,/invalidateQueries/)});
test('matter list uses debounced server pagination',()=>{assert.match(matters,/useDebounce\(search,300\)/);assert.match(matters,/useSolicitorMatters/);assert.match(api,/count: 'exact'/);assert.match(api,/query\.range\(from, from \+ pageSize - 1\)/);assert.match(api,/total_pages/)});
test('stale writes have a recoverable conflict dialog',()=>{assert.match(detail,/STALE_VERSION/);assert.match(detail,/This matter changed elsewhere/);assert.match(detail,/Keep reviewing draft/);assert.match(detail,/Reload latest matter/)});
test('realtime invalidates governed queries without polling',()=>{assert.match(realtime,/postgres_changes/);assert.match(realtime,/solicitor_matter_access/);assert.match(realtime,/messages/);assert.doesNotMatch(realtime,/setInterval/)});
test('matter modules expose the full workspace boundary',()=>{const modules=fs.readFileSync('src/components/solicitor-portal/matter/index.ts','utf8');for(const name of ['MatterOverview','MatterParties','MatterMilestones','MatterDocuments','MatterSearches','MatterRequisitions','MatterDisbursements','MatterCommunications','MatterFinanceSummary','MatterCompliance','MatterContractIntelligence','MatterAudit','MatterRealtime'])assert.match(modules,new RegExp(name))});
