import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const sql=fs.readFileSync('supabase/migrations/20260730250000_immutable_document_service_phase9.sql','utf8');const worker=fs.readFileSync('supabase/functions/legal-document-processor/index.ts','utf8');const helper=fs.readFileSync('supabase/functions/_shared/immutableDocuments.ts','utf8');
test('logical records retain immutable version history',()=>{assert.match(sql,/UNIQUE\(document_record_id,version_number\)/);assert.match(sql,/supersedes_version_id/);assert.match(sql,/IMMUTABLE_DOCUMENT_VERSION_DELETE_FORBIDDEN/);assert.doesNotMatch(sql,/DELETE FROM public\.document_versions/i);});
test('actual bytes determine size mime and hash',()=>{assert.match(worker,/blob\.size/);assert.match(worker,/detectDocumentMime\(bytes\)/);assert.match(worker,/sha256Hex\(bytes\)/);assert.match(worker,/declared_mime_mismatch/);assert.match(helper,/executable_signature/);assert.match(helper,/unsupported_or_ambiguous_zip/);});
test('malware and mismatch fail closed before download',()=>{assert.match(sql,/v\.malware_scan_status='clean'/);assert.match(worker,/scanDocument\(bytes,sha\)/);assert.match(helper,/malware_scanner_not_configured/);assert.match(sql,/lifecycle_status='available'/);});
test('grants revoke access without deleting evidence',()=>{assert.match(sql,/set_document_access_grant/);assert.match(sql,/g\.revoked_at IS NULL/);assert.match(sql,/document_download_audit/);});
test('client contract exposes only reviewed clean versions without storage internals',()=>{const client=fs.readFileSync('supabase/functions/client-portal-batch6/index.ts','utf8');const branch=client.slice(client.indexOf("operation === 'legal_documents'"),client.indexOf("operation === 'legal_document_download'"));assert.doesNotMatch(branch,/storage_path|scan_details|storage_bucket/);assert.match(branch,/malware_scan_status==='clean'/);assert.match(branch,/\['reviewed','retained','legal_hold'\]/);});
test('solicitor mutations scope versions to verified case and matter parents',()=>{const api=fs.readFileSync('supabase/functions/solicitor-portal-documents/index.ts','utf8');assert.match(api,/document_records!inner\(id,case_id,legal_matter_id\)/);assert.match(api,/document_records\.legal_matter_id/);assert.match(api,/IMMUTABLE_DOCUMENT_DELETE_FORBIDDEN/);});
test('superseded objects are never removed by immutable path',()=>{const api=fs.readFileSync('supabase/functions/solicitor-portal-documents/index.ts','utf8');const start=api.indexOf("if(IMMUTABLE_DOCUMENTS_V2){const versionId");const immutableAttach=api.slice(start,api.indexOf('const { data: existing }',start));assert.doesNotMatch(immutableAttach,/storage\.from\([^)]*\)\.remove/);assert.match(api,/if\(IMMUTABLE_DOCUMENTS_V2\)return json\(\{error:'Immutable document records cannot be deleted/);});
