import assert from 'node:assert/strict'; import { readFileSync } from 'node:fs'; import test from 'node:test';
const read=p=>readFileSync(p,'utf8'); const migration=read('supabase/migrations/20260730200000_legal_integrity_commands_phase4.sql');
const solicitor=read('supabase/functions/solicitor-portal-matters/index.ts'); const compliance=read('supabase/functions/solicitor-portal-compliance/index.ts'); const admin=read('supabase/functions/legal-matters-admin/index.ts'); const domain=read('supabase/functions/_shared/legalMatters.ts');
test('transition graph is explicit and arbitrary jumps are rejected',()=>{assert.match(migration,/is_legal_matter_transition_allowed/);assert.match(migration,/INVALID_TRANSITION/);assert.doesNotMatch(migration,/\('instructed','settled'\)/);});
test('status command locks, version-checks and atomically writes history and audit',()=>{for(const t of ['FOR UPDATE','STALE_VERSION','legal_matter_status_history','legal_matter_audit_events']) assert.ok(migration.includes(t));assert.match(solicitor,/rpc\('transition_legal_matter'/);assert.match(admin,/rpc\('transition_legal_matter'/);});
test('stale and invalid mutations map to HTTP 409',()=>{for(const source of [solicitor,compliance,admin]){assert.match(source,/STALE_VERSION/);assert.match(source,/409/);}});
test('link command validates same client and uniqueness in the transaction',()=>{assert.match(migration,/guard_legal_matter_ownership_and_links/);assert.match(migration,/CROSS_CLIENT_LINK/);assert.match(migration,/RECORD_ALREADY_LINKED/);assert.match(admin,/rpc\('link_legal_matter_record'/);});
test('solicitor generic updates exclude Finance-owned fields',()=>{assert.match(domain,/Transaction financials are Finance\/Command Centre owned/);assert.match(domain,/f !== 'finance_clause_date'/);});
test('closure is blocked and reopen changes workflow and closure together',()=>{assert.match(migration,/CLOSURE_BLOCKED/);assert.match(migration,/now\(\)-interval '15 minutes'/);for(const table of ['legal_matter_critical_dates','legal_matter_settlement_tasks','legal_matter_disbursements','legal_matter_requisitions']) assert.ok(migration.includes(table));assert.match(migration,/status=_target_status,closure_status='open'/);assert.match(compliance,/rpc\('close_legal_matter'/);assert.match(compliance,/rpc\('reopen_legal_matter'/);});
test('responsible solicitor must belong to the exact active practice',()=>{assert.match(admin,/assignee\.firm_id !== targetFirm/);assert.match(admin,/assignee\.is_active/);});

test('Phase 4 mutations retain a safe cutover kill switch',()=>{for(const source of [solicitor,compliance,admin]) assert.match(source,/SOLICITOR_LEGAL_INTEGRITY_V1/);});
test('frontend mutations carry the aggregate row version',()=>{const detail=read('src/pages/solicitor/SolicitorMatterDetail.tsx');const panel=read('src/components/admin/solicitor-portal/AdminLegalMattersPanel.tsx');assert.match(detail,/expected_version: matter\?\.row_version/);assert.match(panel,/expected_version: expectedVersion/);});
