import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const finance=fs.readFileSync('supabase/functions/finance-legal-coordination/index.ts','utf8'),solicitor=fs.readFileSync('supabase/functions/solicitor-portal-matters/index.ts','utf8'),worker=fs.readFileSync('supabase/functions/cross-portal-outbox-worker/index.ts','utf8'),admin=fs.readFileSync('supabase/functions/legal-matters-admin/index.ts','utf8'),migration=fs.readFileSync('supabase/migrations/20260730270000_finance_solicitor_collaboration_phase11.sql','utf8');
test('Finance coordination requires exact purchase-file assignment and projection',()=>{assert.match(finance,/assigned_finance_user_id',actorId/);assert.match(finance,/finance_case_read_model/);for(const forbidden of ['internal_notes','risk_notes','conflict','privileged','income','expenses','assets','liabilities','borrowing_capacity','commission','smr','aml'])assert.doesNotMatch(finance.slice(finance.indexOf("select('case_id,client_id"),finance.indexOf(".eq('purchase_file_id'")),new RegExp(forbidden,'i'));});
test('Solicitor finance snapshot is projection-only and excludes financial position',()=>{const detail=solicitor.slice(solicitor.indexOf('// Finance collaboration is projection-only'),solicitor.indexOf('// Phase 4'));assert.match(detail,/solicitor_case_read_model/);assert.doesNotMatch(detail,/from\('purchase_files'\)/);for(const forbidden of ['income','expenses','assets','liabilities','borrowing_capacity','commission','smr','aml'])assert.doesNotMatch(solicitor,new RegExp(`select\\([^\\n]*${forbidden}`,'i'));});
test('both portals use one shared runway, explicitly granted documents and canonical conversation',()=>{for(const api of [finance,solicitor]){assert.match(api,/get_case_runway/);assert.match(api,/visibility==='shared'|visibility === 'shared'/);assert.match(api,/document_access_grants|list_accessible_documents/);assert.match(api,/finance_solicitor/);assert.match(api,/get_conversation_messages/);}});
test('projection carries provenance without crossing private domains',()=>{assert.match(worker,/legal_source_version/);assert.match(worker,/finance_source_version/);assert.match(worker,/finance_clause_state/);assert.match(migration,/link_health/);assert.doesNotMatch(worker,/finance_case_read_model'\)\.upsert\(\{[^}]*internal_notes/);});
test('Command Centre owns inspection reconciliation and durable replay',()=>{assert.match(admin,/list_collaboration_health/);assert.match(admin,/get_finance_solicitor_collaboration_health/);assert.match(admin,/get_collaboration_inspector/);assert.match(admin,/conversation_participants/);assert.match(admin,/solicitor_matter_access/);assert.match(admin,/integration_delivery_attempts/);assert.match(admin,/request_case_projection_refresh/);assert.match(migration,/transaction_case_operational_events/);});
test('legal administration no longer loads client options directly in the browser',()=>{const panel=fs.readFileSync('src/components/admin/solicitor-portal/AdminLegalMattersPanel.tsx','utf8');assert.doesNotMatch(panel,/integrations\/supabase\/client|supabase\.from\('clients'\)/);assert.match(panel,/list_workspace_options/);});
test('portal and Command Centre surfaces are feature flagged and actionable',()=>{const financeUi=fs.readFileSync('src/components/finance-portal/FinanceLegalCoordinationPanel.tsx','utf8'),solicitorUi=fs.readFileSync('src/components/solicitor-portal/MatterFinanceCoordinationPanel.tsx','utf8'),cases=fs.readFileSync('src/components/admin/solicitor-portal/TransactionCasesPanel.tsx','utf8');assert.match(financeUi,/Private legal notes are never shown/);assert.match(solicitorUi,/Financial-position and AML data are never shown/);assert.match(cases,/Queue projection refresh/);});
