import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const api=fs.readFileSync('supabase/functions/client-legal-workspace/index.ts','utf8');const migration=fs.readFileSync('supabase/migrations/20260730260000_client_legal_workspace_phase10.sql','utf8');const page=fs.readFileSync('src/pages/portal/PortalLegalDetail.tsx','utf8');const worker=fs.readFileSync('supabase/functions/cross-portal-outbox-worker/index.ts','utf8');
test('browser workspace reads a sanitised case projection only',()=>{assert.match(api,/client_case_read_model/);const select=api.slice(api.indexOf("select('case_id,client_id"),api.indexOf(".eq('case_id'"));for(const forbidden of ['internal_notes','risk_notes','conflict','analysis','audit','income','assets','liabilities'])assert.doesNotMatch(select,new RegExp(forbidden));assert.doesNotMatch(page,/supabase\.from|legal_matters/);});
test('client runway and canonical legal conversation remain governed',()=>{assert.match(api,/get_case_runway/);assert.match(api,/_audience:'client'/);assert.match(api,/const milestones=.*\.map/);assert.match(api,/const actions=.*\.map/);assert.doesNotMatch(api,/workspace:\{case:legalCase,milestones:runway/);assert.match(api,/get_participant_conversations/);assert.match(api,/scope==='client_solicitor'/);assert.match(api,/post_conversation_message/);});
test('documents require clean reviewed grants and acknowledgements are auditable',()=>{assert.match(api,/malware_scan_status==='clean'/);assert.match(api,/\['reviewed','retained','legal_hold'\]/);assert.match(migration,/document_access_grants/);assert.match(migration,/client_document_acknowledged/);assert.match(migration,/legal_matter_audit_events/);});
test('client uploads are parent scoped and enter immutable quarantine',()=>{assert.match(api,/document_records.*case_id/);assert.match(api,/\.eq\('owner','client'\)/);assert.match(api,/request_document_version/);assert.match(api,/register_uploaded_document_version/);assert.match(api,/processing_status:'queued'/);assert.doesNotMatch(api,/storage\.from\([^)]*\)\.remove/);});
test('outbox projection includes only client-safe contacts and activity',()=>{assert.match(worker,/practice_name/);assert.match(worker,/client_case_activity_read_model/);assert.doesNotMatch(worker,/client_case_read_model'\)\.upsert\(\{[^}]*internal_notes/);assert.match(worker,/scan_status==='clean'/);});
test('feature flag gates route navigation and server contract',()=>{const layout=fs.readFileSync('src/components/portal/PortalLayout.tsx','utf8');const app=fs.readFileSync('src/App.tsx','utf8');assert.match(api,/CLIENT_LEGAL_WORKSPACE/);assert.match(layout,/VITE_CLIENT_LEGAL_WORKSPACE/);assert.match(app,/legal\/:caseId/);});
test('responsive workspace has actionable empty states and accessible controls',()=>{assert.match(page,/aria-label="Upload requested legal document"/);assert.match(page,/aria-label="Message to legal team"/);assert.match(page,/legal team will publish/);assert.match(page,/lg:grid-cols-2/);});
