/**
 * The Market News Feed's canonical source registry, as CODE.
 *
 * GENERATED by `scripts/market-sources/extract-registry.mjs` from the
 * migrations that define it. Do not hand-edit: run
 * `npm run market:registry:generate`, and
 * `npm run market:registry:check` fails CI when this file has drifted from
 * them.
 *
 * ## Why the registry has to be able to travel as code
 *
 * `market_sources` is reference data a migration INSERTs. A clone is
 * provisioned by copying the schema and the migration LEDGER, and the rows
 * those migrations insert do not come with it — measured 19 Sep 2026 on the
 * clone `plisdzywzleljorrphxv`: all seven seeding migrations recorded as
 * applied, the table holding **0 rows**, 310 ingestion runs having produced
 * nothing. The feed was correctly but permanently empty and no operator act
 * available in the product could change it.
 *
 * Code reaches every deployment. Rows do not. So the registry ships here and
 * `registrySeed.pure.ts` decides when a deployment may seed itself from it.
 */

export interface CanonicalMarketSource {
  source_key: string;
  name: string;
  description: string;
  adapter_type: string;
  primary_url: string;
  feed_urls: string[];
  listing_urls: string[];
  source_authority: string;
  reliability_tier: string;
  default_segments: string[];
  category: string;
  refresh_frequency_minutes: number;
  copyright_mode: string;
  perspective: string | null;
  /** `{}` where the adapter needs no configuration. */
  adapter_config: Record<string, unknown>;
  /** Why a disabled source is disabled, in the defining migration's words. */
  disabled_reason: string | null;
  /** The enablement the defining migration gave it. */
  enabled: boolean;
  registry_status: string;
}

export const CANONICAL_MARKET_SOURCES: readonly CanonicalMarketSource[] =
[
  {
    "source_key": "abc_business",
    "name": "ABC News Business",
    "description": "ABC News Business public market intelligence metadata.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.abc.net.au/news/business",
    "feed_urls": [],
    "listing_urls": [
      "https://www.abc.net.au/news/business",
      "https://www.abc.net.au/news/topic/business-economics-and-finance"
    ],
    "source_authority": "tier_1_media",
    "reliability_tier": "tier_1_media",
    "default_segments": [
      "economic",
      "political",
      "finance",
      "property",
      "policy_regulation",
      "social"
    ],
    "category": "economy",
    "refresh_frequency_minutes": 60,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "afca",
    "name": "Australian Financial Complaints Authority",
    "description": "Australian Financial Complaints Authority public market intelligence metadata.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.afca.org.au/news/latest-news",
    "feed_urls": [],
    "listing_urls": [
      "https://www.afca.org.au/news/latest-news",
      "https://www.afca.org.au/news/media-releases"
    ],
    "source_authority": "dispute_resolution_authority",
    "reliability_tier": "official",
    "default_segments": [
      "finance",
      "policy_regulation",
      "social"
    ],
    "category": "policy_regulation",
    "refresh_frequency_minutes": 240,
    "copyright_mode": "public_metadata_and_summary",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "afg_online",
    "name": "Australian Finance Group",
    "description": "AFG — aggregator lodgement data and the AFG Mortgage Index on borrowing patterns and lender share.",
    "adapter_type": "rss",
    "primary_url": "https://afgonline.com.au/",
    "feed_urls": [
      "https://afgonline.com.au/feed/"
    ],
    "listing_urls": [
      "https://afgonline.com.au/news/"
    ],
    "source_authority": "specialist_data",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "property",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 240,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "aggregator_industry",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "allens_legal_insights",
    "name": "Allens Legal Insights",
    "description": "Allens Legal Insights public market intelligence metadata.",
    "adapter_type": "rss",
    "primary_url": "https://feeds.feedburner.com/AllensLatestPublications",
    "feed_urls": [
      "https://feeds.feedburner.com/AllensLatestPublications",
      "https://feeds.feedburner.com/Allenspublicationsandmediareleases"
    ],
    "listing_urls": [
      "https://www.allens.com.au/insights-news/"
    ],
    "source_authority": "legal_interpretation",
    "reliability_tier": "industry",
    "default_segments": [
      "policy_regulation",
      "finance",
      "property",
      "construction",
      "economic"
    ],
    "category": "policy_regulation",
    "refresh_frequency_minutes": 240,
    "copyright_mode": "rss_excerpt_and_transformative_summary",
    "perspective": "legal_commentary_not_primary_law",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "anz_institutional_insights",
    "name": "ANZ Institutional Insights",
    "description": "ANZ institutional economic, rates, trade and property analysis.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.anz.com/institutional/insights/",
    "feed_urls": [],
    "listing_urls": [
      "https://www.anz.com/institutional/insights/"
    ],
    "source_authority": "bank_research",
    "reliability_tier": "institutional_research",
    "default_segments": [
      "economic",
      "finance",
      "property",
      "international"
    ],
    "category": "economy",
    "refresh_frequency_minutes": 180,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "bank_forecast",
    "adapter_config": {
      "anchor_patterns": [
        "^/institutional/insights/articles/[0-9]{4}/[0-9]{2}/[a-z0-9-]+/$"
      ],
      "title_min_length": 12
    },
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "apra_news",
    "name": "Australian Prudential Regulation Authority",
    "description": "APRA media releases and statistics — prudential standards, serviceability buffers and ADI lending data.",
    "adapter_type": "rss",
    "primary_url": "https://www.apra.gov.au/news-and-publications",
    "feed_urls": [
      "https://www.apra.gov.au/rss.xml"
    ],
    "listing_urls": [
      "https://www.apra.gov.au/news-and-publications"
    ],
    "source_authority": "regulator",
    "reliability_tier": "official",
    "default_segments": [
      "finance",
      "policy_regulation",
      "economic",
      "property"
    ],
    "category": "policy_regulation",
    "refresh_frequency_minutes": 90,
    "copyright_mode": "public_sector_metadata_and_summary",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "asic_newsroom",
    "name": "Australian Securities and Investments Commission",
    "description": "ASIC announcements on financial services, lending conduct, enforcement and consumer protection.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.asic.gov.au/newsroom/",
    "feed_urls": [],
    "listing_urls": [
      "https://www.asic.gov.au/newsroom/"
    ],
    "source_authority": "regulator",
    "reliability_tier": "official",
    "default_segments": [
      "finance",
      "policy_regulation",
      "economic"
    ],
    "category": "policy_regulation",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "public_sector_metadata_and_summary",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": "Newsroom links only section indexes and the media-release listing is a 14KB client-rendered shell; no JSON-LD, no article anchors, zero items under a valid pattern. Needs a server-side data source, not a selector change.",
    "enabled": false,
    "registry_status": "canonical"
  },
  {
    "source_key": "austrac",
    "name": "AUSTRAC",
    "description": "AUSTRAC public market intelligence metadata.",
    "adapter_type": "rss_with_html_fallback",
    "primary_url": "https://www.austrac.gov.au/media-release/rss.xml",
    "feed_urls": [
      "https://www.austrac.gov.au/media-release/rss.xml"
    ],
    "listing_urls": [
      "https://www.austrac.gov.au/news-and-media/news-and-media-releases",
      "https://www.austrac.gov.au/news-and-media/media-release",
      "https://www.austrac.gov.au/industry-and-business/consultations"
    ],
    "source_authority": "regulator",
    "reliability_tier": "official",
    "default_segments": [
      "policy_regulation",
      "finance",
      "property",
      "political"
    ],
    "category": "policy_regulation",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "public_sector_metadata_and_summary",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "australian_banking_association",
    "name": "Australian Banking Association",
    "description": "Australian Banking Association public market intelligence metadata.",
    "adapter_type": "feed_with_html_fallback",
    "primary_url": "https://www.ausbanking.org.au/feed/",
    "feed_urls": [
      "https://www.ausbanking.org.au/feed/"
    ],
    "listing_urls": [
      "https://www.ausbanking.org.au/news/",
      "https://www.ausbanking.org.au/news-resources/media-releases/"
    ],
    "source_authority": "industry_association",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "policy_regulation",
      "economic",
      "political"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "banking_industry_advocacy",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "australian_broker",
    "name": "Australian Broker",
    "description": "Australian Broker (Key Media) — mortgage broking, lender policy and lending criteria news.",
    "adapter_type": "rss",
    "primary_url": "https://www.brokernews.com.au/",
    "feed_urls": [
      "https://www.brokernews.com.au/rss"
    ],
    "listing_urls": [
      "https://www.brokernews.com.au/news"
    ],
    "source_authority": "specialist_industry_media",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "property",
      "policy_regulation",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 60,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "australian_bureau_statistics",
    "name": "Australian Bureau of Statistics",
    "description": "Official Australian statistics covering inflation, employment, lending, dwelling approvals, construction and population.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.abs.gov.au/media-centre/media-releases",
    "feed_urls": [],
    "listing_urls": [
      "https://www.abs.gov.au/media-centre/media-releases"
    ],
    "source_authority": "official_statistics",
    "reliability_tier": "official",
    "default_segments": [
      "economic",
      "finance",
      "property",
      "construction",
      "rental",
      "policy_regulation"
    ],
    "category": "economy",
    "refresh_frequency_minutes": 60,
    "copyright_mode": "public_sector_metadata_and_summary",
    "perspective": null,
    "adapter_config": {
      "item_selector": "__anchor_only__",
      "anchor_patterns": [
        "^/media-centre/media-releases/[a-z0-9-]+$"
      ],
      "title_min_length": 12
    },
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "australian_financial_review",
    "name": "Australian Financial Review",
    "description": "Premium Australian business, property, banking and economic journalism.",
    "adapter_type": "licensed_api",
    "primary_url": "https://business.afr.com/content-integrations",
    "feed_urls": [],
    "listing_urls": [],
    "source_authority": "tier_1_premium_business_media",
    "reliability_tier": "tier_1_media",
    "default_segments": [
      "economic",
      "finance",
      "property",
      "policy_regulation"
    ],
    "category": "economy",
    "refresh_frequency_minutes": 15,
    "copyright_mode": "licensed_content_only",
    "perspective": "premium_business_media",
    "adapter_config": {},
    "disabled_reason": "Licence pending. Requires AFR_CONTENT_API_BASE_URL, AFR_CONTENT_API_KEY, AFR_CONTENT_API_CLIENT_ID and AFR_CONTENT_INTEGRATION_ENABLED plus written redistribution rights. Scraping afr.com is not an acceptable fallback.",
    "enabled": false,
    "registry_status": "canonical"
  },
  {
    "source_key": "australian_treasury",
    "name": "Australian Treasury",
    "description": "Departmental media releases and consultations on housing, tax, the financial system and economic policy.",
    "adapter_type": "html_listing",
    "primary_url": "https://treasury.gov.au/media-release",
    "feed_urls": [],
    "listing_urls": [
      "https://treasury.gov.au/media-release",
      "https://treasury.gov.au/consultation"
    ],
    "source_authority": "primary_government",
    "reliability_tier": "official",
    "default_segments": [
      "economic",
      "finance",
      "property",
      "policy_regulation"
    ],
    "category": "policy_regulation",
    "refresh_frequency_minutes": 90,
    "copyright_mode": "public_sector_metadata_and_summary",
    "perspective": null,
    "adapter_config": {
      "item_selector": "__anchor_only__",
      "anchor_patterns": [
        "^/media-release/[a-z0-9-]+$",
        "^/consultation/c[0-9-]{4,20}$"
      ],
      "title_min_length": 12
    },
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "banking_code_compliance_committee",
    "name": "Banking Code Compliance Committee",
    "description": "Banking Code Compliance Committee public market intelligence metadata.",
    "adapter_type": "html_listing",
    "primary_url": "https://bankingcode.org.au/",
    "feed_urls": [],
    "listing_urls": [
      "https://bankingcode.org.au/",
      "https://bankingcode.org.au/resources/",
      "https://bankingcode.org.au/banks/guidance-notes/"
    ],
    "source_authority": "code_compliance_body",
    "reliability_tier": "official",
    "default_segments": [
      "finance",
      "policy_regulation",
      "social"
    ],
    "category": "policy_regulation",
    "refresh_frequency_minutes": 360,
    "copyright_mode": "public_metadata_and_summary",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "bloomberg_australia",
    "name": "Bloomberg Australia and Global Macro",
    "description": "Licensed Bloomberg coverage of central banks, rates, currencies and property-related markets.",
    "adapter_type": "licensed_api",
    "primary_url": "https://professional.bloomberg.com/products/data/enterprise-catalog/event-driven-feeds/",
    "feed_urls": [],
    "listing_urls": [],
    "source_authority": "global_tier_1_financial_media",
    "reliability_tier": "tier_1_media",
    "default_segments": [
      "economic",
      "finance",
      "property",
      "international",
      "policy_regulation"
    ],
    "category": "economy",
    "refresh_frequency_minutes": 15,
    "copyright_mode": "licensed_content_only",
    "perspective": "global_financial_media",
    "adapter_config": {},
    "disabled_reason": "Licence pending. Requires BLOOMBERG_TEXTUAL_NEWS_ENDPOINT, BLOOMBERG_CLIENT_ID, BLOOMBERG_CLIENT_SECRET and BLOOMBERG_CONTENT_ENABLED. Scraping bloomberg.com is not an acceptable fallback.",
    "enabled": false,
    "registry_status": "canonical"
  },
  {
    "source_key": "broker_daily",
    "name": "Broker Daily",
    "description": "Broker Daily public market intelligence metadata.",
    "adapter_type": "feed_with_html_fallback",
    "primary_url": "https://www.brokerdaily.au/feed/",
    "feed_urls": [
      "https://www.brokerdaily.au/feed/"
    ],
    "listing_urls": [
      "https://www.brokerdaily.au/",
      "https://www.brokerdaily.au/lender",
      "https://www.brokerdaily.au/regulation",
      "https://www.brokerdaily.au/property",
      "https://www.brokerdaily.au/economy"
    ],
    "source_authority": "specialist_industry_media",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "property",
      "policy_regulation",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 60,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "commonwealth_bank_economics",
    "name": "Commonwealth Bank Economics",
    "description": "CBA economic, household, property and interest-rate research.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.commbank.com.au/newsroom/latest-economic-news-and-analysis.html",
    "feed_urls": [],
    "listing_urls": [
      "https://www.commbank.com.au/newsroom/latest-economic-news-and-analysis.html"
    ],
    "source_authority": "bank_research",
    "reliability_tier": "institutional_research",
    "default_segments": [
      "economic",
      "finance",
      "property",
      "construction"
    ],
    "category": "economy",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "bank_forecast",
    "adapter_config": {
      "item_selector": "__anchor_only__",
      "anchor_patterns": [
        "^/articles/newsroom/[0-9]{4}/[a-zA-Z]{3,9}/[a-z0-9-]+.html$"
      ],
      "title_min_length": 12
    },
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "cotality_australia",
    "name": "Cotality Australia",
    "description": "Cotality Australia public market intelligence metadata.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.cotality.com/au/insights",
    "feed_urls": [],
    "listing_urls": [
      "https://www.cotality.com/au/insights",
      "https://www.cotality.com/research-news"
    ],
    "source_authority": "specialist_data",
    "reliability_tier": "partner",
    "default_segments": [
      "property",
      "rental",
      "construction",
      "economic"
    ],
    "category": "property_market",
    "refresh_frequency_minutes": 180,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "customer_owned_banking",
    "name": "Customer Owned Banking Association",
    "description": "COBA — mutual bank and credit union sector positions on lending policy and competition.",
    "adapter_type": "rss",
    "primary_url": "https://www.customerownedbanking.asn.au/",
    "feed_urls": [
      "https://www.coba.asn.au/feed/"
    ],
    "listing_urls": [
      "https://www.customerownedbanking.asn.au/"
    ],
    "source_authority": "industry_association",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "policy_regulation",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 240,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "mutual_banking_advocacy",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "domain_research",
    "name": "Domain Research and News",
    "description": "Domain Research and News public market intelligence metadata.",
    "adapter_type": "feed_with_html_fallback",
    "primary_url": "https://www.domain.com.au/news/feed/",
    "feed_urls": [
      "https://www.domain.com.au/news/feed/"
    ],
    "listing_urls": [
      "https://www.domain.com.au/research/",
      "https://www.domain.com.au/news/national/",
      "https://www.domain.com.au/news/author/domain-research/",
      "https://www.domain.com.au/group/newsroom/media-releases/"
    ],
    "source_authority": "specialist_data",
    "reliability_tier": "partner",
    "default_segments": [
      "property",
      "rental",
      "finance",
      "economic",
      "policy_regulation"
    ],
    "category": "property_market",
    "refresh_frequency_minutes": 180,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "fbaa",
    "name": "Finance Brokers Association of Australasia",
    "description": "Finance Brokers Association of Australasia public market intelligence metadata.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.fbaa.com.au/news-media/newshub/",
    "feed_urls": [],
    "listing_urls": [
      "https://www.fbaa.com.au/news-media/newshub/",
      "https://www.fbaa.com.au/news-media/brokernet/",
      "https://www.fbaa.com.au/news-media/broker-magazine/"
    ],
    "source_authority": "industry_association",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "policy_regulation",
      "property",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 180,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "industry_advocacy",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "federal_register_legislation",
    "name": "Federal Register of Legislation",
    "description": "Federal Register of Legislation public market intelligence metadata.",
    "adapter_type": "official_api",
    "primary_url": "https://api.prod.legislation.gov.au/v1/",
    "feed_urls": [],
    "listing_urls": [
      "https://api.prod.legislation.gov.au/swagger/index.html"
    ],
    "source_authority": "primary_legal",
    "reliability_tier": "official",
    "default_segments": [
      "policy_regulation",
      "political",
      "finance",
      "property",
      "construction",
      "economic"
    ],
    "category": "policy_regulation",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "public_sector_metadata_and_summary",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "finder_au",
    "name": "Finder",
    "description": "Finder — comparison coverage of home loan rates, lender offers and household borrowing costs.",
    "adapter_type": "rss",
    "primary_url": "https://www.finder.com.au/",
    "feed_urls": [
      "https://www.finder.com.au/feed"
    ],
    "listing_urls": [
      "https://www.finder.com.au/news"
    ],
    "source_authority": "specialist_industry_media",
    "reliability_tier": "watchlist",
    "default_segments": [
      "finance",
      "property",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 240,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "comparison_service",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "firstlinks",
    "name": "Firstlinks",
    "description": "Firstlinks (Morningstar Australia) — investment, superannuation and tax-policy commentary affecting borrowers.",
    "adapter_type": "rss",
    "primary_url": "https://www.firstlinks.com.au/",
    "feed_urls": [
      "https://www.firstlinks.com.au/feed"
    ],
    "listing_urls": [
      "https://www.firstlinks.com.au/"
    ],
    "source_authority": "specialist_industry_media",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "economic",
      "policy_regulation",
      "property"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 240,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "investment_commentary",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "guardian_australia",
    "name": "The Guardian Australia",
    "description": "The Guardian Australia public market intelligence metadata.",
    "adapter_type": "rss",
    "primary_url": "https://www.theguardian.com/au/rss",
    "feed_urls": [
      "https://www.theguardian.com/au/rss",
      "https://www.theguardian.com/australia-news/business-australia/rss"
    ],
    "listing_urls": [
      "https://www.theguardian.com/australia-news/business-australia"
    ],
    "source_authority": "tier_1_media",
    "reliability_tier": "tier_1_media",
    "default_segments": [
      "political",
      "economic",
      "social",
      "property",
      "rental",
      "policy_regulation"
    ],
    "category": "political",
    "refresh_frequency_minutes": 60,
    "copyright_mode": "rss_excerpt_and_transformative_summary",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "infochoice",
    "name": "InfoChoice",
    "description": "InfoChoice — comparison-desk coverage of home loan rates, fixed vs variable and lender repricing.",
    "adapter_type": "rss",
    "primary_url": "https://www.infochoice.com.au/",
    "feed_urls": [
      "https://www.infochoice.com.au/feed"
    ],
    "listing_urls": [
      "https://www.infochoice.com.au/news"
    ],
    "source_authority": "specialist_industry_media",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "property",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "master_builders_australia",
    "name": "Master Builders Australia",
    "description": "Construction industry association — housing supply, building costs, labour and planning reform.",
    "adapter_type": "rss",
    "primary_url": "https://masterbuilders.com.au/",
    "feed_urls": [
      "https://masterbuilders.com.au/feed/"
    ],
    "listing_urls": [
      "https://masterbuilders.com.au/media-releases"
    ],
    "source_authority": "industry_association",
    "reliability_tier": "industry",
    "default_segments": [
      "construction",
      "property",
      "policy_regulation",
      "economic"
    ],
    "category": "construction",
    "refresh_frequency_minutes": 240,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "construction_industry_advocacy",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "mfaa",
    "name": "Mortgage & Finance Association of Australia",
    "description": "Mortgage & Finance Association of Australia public market intelligence metadata.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.mfaa.com.au/news",
    "feed_urls": [],
    "listing_urls": [
      "https://www.mfaa.com.au/news",
      "https://www.mfaa.com.au/about/media-releases"
    ],
    "source_authority": "industry_association",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "policy_regulation",
      "property",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 180,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "industry_advocacy",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "mortgage_professional_australia",
    "name": "Mortgage Professional Australia",
    "description": "Mortgage Professional Australia public market intelligence metadata.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.mpamag.com/au/mortgage-industry/market-updates",
    "feed_urls": [],
    "listing_urls": [
      "https://www.mpamag.com/au/mortgage-industry/market-updates",
      "https://www.mpamag.com/au/news/general",
      "https://www.mpamag.com/au/mortgage-industry/industry-trends"
    ],
    "source_authority": "specialist_industry_media",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "property",
      "economic",
      "policy_regulation"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 90,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "nab_economics_market_news",
    "name": "NAB Economics and Market News",
    "description": "NAB economic, housing, business and monetary-policy research.",
    "adapter_type": "rss_with_html_fallback",
    "primary_url": "https://news.nab.com.au/",
    "feed_urls": [
      "https://news.nab.com.au/feed/"
    ],
    "listing_urls": [
      "https://news.nab.com.au/tag/economic-market"
    ],
    "source_authority": "bank_research",
    "reliability_tier": "institutional_research",
    "default_segments": [
      "economic",
      "finance",
      "property",
      "construction"
    ],
    "category": "economy",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "bank_forecast",
    "adapter_config": {},
    "disabled_reason": "news.nab.com.au/feed/ returns HTTP 404; no working RSS endpoint found. Re-enable if NAB publishes a stable economics feed.",
    "enabled": false,
    "registry_status": "canonical"
  },
  {
    "source_key": "national_housing_supply_affordability_council",
    "name": "National Housing Supply and Affordability Council",
    "description": "Independent statutory housing-system assessments, supply forecasts and affordability analysis.",
    "adapter_type": "html_listing",
    "primary_url": "https://nhsac.gov.au/",
    "feed_urls": [],
    "listing_urls": [
      "https://nhsac.gov.au/"
    ],
    "source_authority": "independent_statutory_research",
    "reliability_tier": "official",
    "default_segments": [
      "property",
      "rental",
      "construction",
      "economic",
      "policy_regulation",
      "social"
    ],
    "category": "property_market",
    "refresh_frequency_minutes": 240,
    "copyright_mode": "public_sector_metadata_and_summary",
    "perspective": "independent_housing_analysis",
    "adapter_config": {
      "item_selector": "__anchor_only__",
      "anchor_patterns": [
        "^/reports-and-submissions/[a-z0-9-]+$"
      ],
      "title_min_length": 12
    },
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "parliament_australia",
    "name": "Parliament of Australia",
    "description": "Parliament of Australia public market intelligence metadata.",
    "adapter_type": "rss_multi",
    "primary_url": "https://parlinfo.aph.gov.au/parlInfo/feeds/rss.w3p;adv=yes;orderBy=date-eFirst;page=0;query=Date%3AthisYear%20Dataset%3Abillsdgs;resCount=100",
    "feed_urls": [
      "https://parlinfo.aph.gov.au/parlInfo/feeds/rss.w3p;adv=yes;orderBy=date-eFirst;page=0;query=Date%3AthisYear%20Dataset%3Abillsdgs;resCount=100",
      "https://www.aph.gov.au/senate/rss/new_inquiries",
      "https://www.aph.gov.au/senate/rss/reports",
      "https://www.aph.gov.au/house/rss/house_inquiries",
      "https://www.aph.gov.au/house/rss/joint_inquiries",
      "https://www.aph.gov.au/house/rss/media_releases"
    ],
    "listing_urls": [
      "https://www.aph.gov.au/Parliamentary_Business/Bills_Legislation"
    ],
    "source_authority": "primary_government",
    "reliability_tier": "official",
    "default_segments": [
      "political",
      "policy_regulation",
      "finance",
      "property",
      "construction",
      "economic"
    ],
    "category": "policy_regulation",
    "refresh_frequency_minutes": 60,
    "copyright_mode": "public_sector_metadata_and_summary",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "property_council_australia",
    "name": "Property Council of Australia / Property Australia",
    "description": "Property Council of Australia / Property Australia public market intelligence metadata.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.propertycouncil.com.au/news-research/property-australia",
    "feed_urls": [],
    "listing_urls": [
      "https://www.propertycouncil.com.au/news-research/property-australia",
      "https://www.propertycouncil.com.au/news-research/overview"
    ],
    "source_authority": "industry_advocacy",
    "reliability_tier": "industry",
    "default_segments": [
      "property",
      "construction",
      "political",
      "policy_regulation",
      "economic"
    ],
    "category": "planning_supply",
    "refresh_frequency_minutes": 240,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "industry_advocacy",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "proptrack_rea",
    "name": "realestate.com.au / PropTrack",
    "description": "realestate.com.au / PropTrack public market intelligence metadata.",
    "adapter_type": "feed_with_html_fallback",
    "primary_url": "https://www.realestate.com.au/news/feed/",
    "feed_urls": [
      "https://www.realestate.com.au/news/feed/"
    ],
    "listing_urls": [
      "https://www.realestate.com.au/insights/",
      "https://www.realestate.com.au/news/",
      "https://www.proptrack.com.au/insights-hub/insights/"
    ],
    "source_authority": "specialist_data",
    "reliability_tier": "partner",
    "default_segments": [
      "property",
      "rental",
      "economic",
      "finance"
    ],
    "category": "property_market",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "reserve_bank_australia",
    "name": "Reserve Bank of Australia",
    "description": "RBA media releases, speeches and Bulletin research — cash rate decisions and monetary policy guidance.",
    "adapter_type": "rss_multi",
    "primary_url": "https://www.rba.gov.au/media-releases/",
    "feed_urls": [
      "https://www.rba.gov.au/rss/rss-cb-media-releases.xml",
      "https://www.rba.gov.au/rss/rss-cb-speeches.xml",
      "https://www.rba.gov.au/rss/rss-cb-bulletin.xml"
    ],
    "listing_urls": [
      "https://www.rba.gov.au/media-releases/"
    ],
    "source_authority": "primary_government",
    "reliability_tier": "official",
    "default_segments": [
      "finance",
      "economic",
      "policy_regulation",
      "property"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 60,
    "copyright_mode": "public_sector_metadata_and_summary",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "reuters_australia",
    "name": "Reuters Australia / Asia-Pacific",
    "description": "Reuters Australia / Asia-Pacific public market intelligence metadata.",
    "adapter_type": "html_listing_or_licensed_feed",
    "primary_url": "https://www.reuters.com/world/asia-pacific/",
    "feed_urls": [],
    "listing_urls": [
      "https://www.reuters.com/world/asia-pacific/"
    ],
    "source_authority": "tier_1_media",
    "reliability_tier": "tier_1_media",
    "default_segments": [
      "economic",
      "finance",
      "political",
      "property",
      "policy_regulation"
    ],
    "category": "economy",
    "refresh_frequency_minutes": 60,
    "copyright_mode": "link_and_metadata_only_unless_licensed",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "savings_com_au",
    "name": "Savings.com.au",
    "description": "Savings.com.au — home loan and deposit rate movements, lender policy changes and credit conditions.",
    "adapter_type": "rss",
    "primary_url": "https://www.savings.com.au/",
    "feed_urls": [
      "https://www.savings.com.au/feed"
    ],
    "listing_urls": [
      "https://www.savings.com.au/news"
    ],
    "source_authority": "specialist_industry_media",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "property",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 90,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "the_adviser_australia",
    "name": "The Adviser",
    "description": "The Adviser public market intelligence metadata.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.theadviser.com.au/",
    "feed_urls": [],
    "listing_urls": [
      "https://www.theadviser.com.au/",
      "https://www.theadviser.com.au/lender",
      "https://www.theadviser.com.au/breaking-news"
    ],
    "source_authority": "specialist_industry_media",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "property",
      "policy_regulation",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 60,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "the_conversation_au",
    "name": "The Conversation Australia",
    "description": "Academic analysis of housing, lending and economic policy, written by named researchers under a Creative Commons licence.",
    "adapter_type": "rss",
    "primary_url": "https://theconversation.com/au/business",
    "feed_urls": [
      "https://theconversation.com/au/business/articles.atom"
    ],
    "listing_urls": [
      "https://theconversation.com/au/business"
    ],
    "source_authority": "academic_research",
    "reliability_tier": "industry",
    "default_segments": [
      "economic",
      "property",
      "finance",
      "policy_regulation",
      "social"
    ],
    "category": "economy",
    "refresh_frequency_minutes": 180,
    "copyright_mode": "creative_commons_attribution_excerpt_and_summary",
    "perspective": "academic_analysis",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "treasury_ministers_priority",
    "name": "Australian Treasury Ministers",
    "description": "Ministerial releases on the economy, housing, taxation, banking and financial-services policy.",
    "adapter_type": "rss_with_html_fallback",
    "primary_url": "https://ministers.treasury.gov.au/",
    "feed_urls": [
      "https://ministers.treasury.gov.au/ministers/jim-chalmers-2022/media-releases/feed"
    ],
    "listing_urls": [
      "https://ministers.treasury.gov.au/ministers/jim-chalmers-2022/media-releases"
    ],
    "source_authority": "primary_government",
    "reliability_tier": "official",
    "default_segments": [
      "economic",
      "property",
      "finance",
      "policy_regulation",
      "construction"
    ],
    "category": "policy_regulation",
    "refresh_frequency_minutes": 90,
    "copyright_mode": "public_sector_metadata_and_summary",
    "perspective": "government_policy",
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "urban_developer",
    "name": "The Urban Developer",
    "description": "The Urban Developer public market intelligence metadata.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.theurbandeveloper.com/articles/top-stories",
    "feed_urls": [],
    "listing_urls": [
      "https://www.theurbandeveloper.com/articles/top-stories",
      "https://www.theurbandeveloper.com/"
    ],
    "source_authority": "specialist_industry_media",
    "reliability_tier": "industry",
    "default_segments": [
      "construction",
      "property",
      "political",
      "economic",
      "policy_regulation"
    ],
    "category": "construction",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "westpac_iq_economics",
    "name": "Westpac IQ Economics",
    "description": "Westpac economic, housing, consumer-sentiment and rates research.",
    "adapter_type": "html_listing",
    "primary_url": "https://www.westpaciq.com.au/economics.html",
    "feed_urls": [],
    "listing_urls": [
      "https://www.westpaciq.com.au/economics.html"
    ],
    "source_authority": "bank_research",
    "reliability_tier": "institutional_research",
    "default_segments": [
      "economic",
      "finance",
      "property"
    ],
    "category": "economy",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": "bank_forecast",
    "adapter_config": {
      "item_selector": "__anchor_only__",
      "anchor_patterns": [
        "^/economics/[0-9]{4}/[0-9]{2}/[a-zA-Z0-9-]+$"
      ],
      "title_min_length": 12
    },
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  },
  {
    "source_key": "your_mortgage",
    "name": "Your Mortgage",
    "description": "Your Mortgage (Key Media) — home loan products, rate movements and borrower-facing lending guidance.",
    "adapter_type": "rss",
    "primary_url": "https://www.yourmortgage.com.au/",
    "feed_urls": [
      "https://www.yourmortgage.com.au/feed"
    ],
    "listing_urls": [
      "https://www.yourmortgage.com.au/mortgage-news"
    ],
    "source_authority": "specialist_industry_media",
    "reliability_tier": "industry",
    "default_segments": [
      "finance",
      "property",
      "economic"
    ],
    "category": "finance",
    "refresh_frequency_minutes": 120,
    "copyright_mode": "metadata_and_transformative_summary_only",
    "perspective": null,
    "adapter_config": {},
    "disabled_reason": null,
    "enabled": true,
    "registry_status": "canonical"
  }
] as const;

/** How many sources this manifest carries. Asserted by the check script. */
export const CANONICAL_MARKET_SOURCE_COUNT = 43;
