"""Design-token seam between the template library and Claude Design.

The library's palette and type scale are authored in ``theme.py`` as Python
dataclass defaults. That is the right home for them — they are versioned,
reviewable and diffable — but it means an external design system has nowhere to
plug in without editing code.

This module is that plug. ``design-tokens.json``, when present, overrides the
palette and type scale for every one of the 40 templates at build time:

    python3 scripts/aurixa-templates/design_tokens.py --export   # write current values
    python3 scripts/aurixa-templates/build_library.py --sample   # build against them

**Connecting Claude Design.** Claude Design syncs an HTML/CSS component library
with a claude.ai/design project; this library is Word documents generated by
python-docx, so the two cannot be synced directly. The token file is the bridge:
export the design system's colours and type scale into this shape and the whole
library re-cuts to match. See ``DESIGN.md`` for the current step-by-step.

Deliberate constraints, matching the white-label rules in ``theme.py``:

* only **colour** and **type size** are overridable. Spacing, margins, cover
  architecture and table structure stay in code, because those are the things
  that break a layout when a non-designer changes them;
* semantic colours (success / warning / alert) are overridable but *called out*,
  since changing them changes what a status means to a reader;
* an unknown key is an error rather than a silent no-op — a typo'd token name
  that quietly did nothing would be discovered in a client-facing PDF.
"""

from __future__ import annotations

import json
from dataclasses import fields as dataclass_fields
from pathlib import Path
from typing import Any

TOKENS_PATH = Path(__file__).with_name("design-tokens.json")

#: Semantic colours a partner may set but probably should not.
SEMANTIC_KEYS = {
    "success", "success_soft", "success_line",
    "warning", "warning_soft", "warning_line",
    "alert", "alert_soft", "alert_line",
    "info", "info_soft", "info_line",
}

_HEX = set("0123456789abcdefABCDEF")


def _is_hex(value: Any) -> bool:
    return isinstance(value, str) and len(value) == 6 and all(c in _HEX for c in value)


class TokenError(ValueError):
    """Raised for an unknown or malformed token, never swallowed."""


def load_tokens(path: Path | None = None) -> dict[str, dict[str, Any]]:
    """Read the token file. Returns empty overrides when there is no file."""
    target = path or TOKENS_PATH
    if not target.exists():
        return {"palette": {}, "type_scale": {}}
    payload = json.loads(target.read_text())
    return {
        "palette": {k: v for k, v in (payload.get("palette") or {}).items()
                    if not k.startswith("_")},
        "type_scale": {k: v for k, v in (payload.get("typeScale") or {}).items()
                       if not k.startswith("_")},
    }


def apply_tokens(palette_cls, type_scale_cls, tokens: dict[str, dict[str, Any]]):
    """Return ``(palette, type_scale)`` instances with the overrides applied.

    Validates against the dataclass fields so a token the library does not have
    is reported rather than ignored.
    """
    palette_fields = {f.name for f in dataclass_fields(palette_cls)}
    scale_fields = {f.name for f in dataclass_fields(type_scale_cls)}

    colours = tokens.get("palette") or {}
    unknown = sorted(set(colours) - palette_fields)
    if unknown:
        raise TokenError(
            f"Unknown palette token(s): {', '.join(unknown)}. "
            f"Valid: {', '.join(sorted(palette_fields))}")
    bad = sorted(k for k, v in colours.items() if not _is_hex(v))
    if bad:
        raise TokenError(
            f"Palette token(s) must be 6-digit hex without '#': {', '.join(bad)}")

    sizes = tokens.get("type_scale") or {}
    unknown = sorted(set(sizes) - scale_fields)
    if unknown:
        raise TokenError(
            f"Unknown type-scale token(s): {', '.join(unknown)}. "
            f"Valid: {', '.join(sorted(scale_fields))}")
    bad = sorted(k for k, v in sizes.items()
                 if not isinstance(v, (int, float)) or not 4 <= float(v) <= 96)
    if bad:
        raise TokenError(
            f"Type-scale token(s) must be a point size between 4 and 96: "
            f"{', '.join(bad)}")

    return palette_cls(**colours), type_scale_cls(**sizes)


def export_tokens(palette, type_scale, path: Path | None = None) -> Path:
    """Write the library's current values out in token shape.

    This is the starting point for a design system: export, hand the file to
    whoever owns the design, take it back with the values changed.
    """
    target = path or TOKENS_PATH
    payload = {
        "_comment": (
            "Design tokens for the Aurixa Command Center template library. "
            "Colour is 6-digit hex without '#'; type scale is in points. "
            "Only colour and type size are overridable — spacing, margins and "
            "layout stay in scripts/aurixa-templates/theme.py by design. "
            "Regenerate with: python3 scripts/aurixa-templates/design_tokens.py --export"
        ),
        "_semanticWarning": (
            "Changing success/warning/alert changes what a status means to a "
            "reader. Do it deliberately or not at all."
        ),
        "palette": {f.name: getattr(palette, f.name)
                    for f in dataclass_fields(palette)},
        "typeScale": {f.name: getattr(type_scale, f.name)
                      for f in dataclass_fields(type_scale)},
    }
    target.write_text(json.dumps(payload, indent=2) + "\n")
    return target


def main() -> int:
    import argparse
    import sys

    sys.path.insert(0, str(Path(__file__).parent))
    from theme import Palette, TypeScale  # noqa: E402

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export", action="store_true",
                        help="write the library's current values to design-tokens.json")
    parser.add_argument("--check", action="store_true",
                        help="validate design-tokens.json without building")
    args = parser.parse_args()

    if args.export:
        path = export_tokens(Palette(), TypeScale())
        print(f"Wrote {path.relative_to(Path(__file__).resolve().parents[2])}")
        return 0

    tokens = load_tokens()
    if not tokens["palette"] and not tokens["type_scale"]:
        print("No design-tokens.json — the library builds from theme.py defaults.")
        return 0
    apply_tokens(Palette, TypeScale, tokens)
    print(f"design-tokens.json is valid: "
          f"{len(tokens['palette'])} colour(s), {len(tokens['type_scale'])} size(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
