/**
 * E4 — Table Candidate Arbitration & Preservation (canonical shared module) specs.
 *
 * Verifies the TypeScript contracts, deterministic IDs (byte-identical to the
 * Python producer `pdf-parse-service/table_candidates.py`), the mapper's
 * source-derived header policy (no synthesized `Column N`), the renderer-facing
 * table child suppression, the document-level report, the E0 handoff, and the
 * template integration bridge.
 */
import { describe, it, expect } from 'vitest';
import {
  candidateId,
  cellId,
  validateTableCandidate,
  validateTableArbitration,
  deriveNativeHeaderPolicy,
  resolveTableSuppression,
  buildTablePreservationReport,
  attachTablePreservationSummary,
  tableContainmentRequirement,
  TABLE_CANDIDATE_CONTRACT_VERSION,
  TABLE_ARBITRATION_VERSION,
  TABLE_PRESERVATION_VERSION,
  type TableArbitrationResultV1,
  type TablePreservationRegionPlanV1,
  type TableSuppressionOverlay,
} from '../pdfImport/tableArbitration.pure';
import type { SourceBBox } from '../pdfImport/sourceSceneGraphV2.pure';
import {
  resolvePageTablePreservation,
  buildPageTablePreservation,
} from '../pdfImport/tablePreservationIntegration';

// ── Cross-runtime parity fixtures (generated by the Python producer) ─────────

const PARITY_BBOX: SourceBBox = { x: 40, y: 100, width: 500, height: 80 };
const PARITY_CELLS = [
  { row: 0, col: 0, rowSpan: 1, colSpan: 1, columnHeader: true, rowHeader: false, text: 'Year' },
  { row: 0, col: 1, rowSpan: 1, colSpan: 1, columnHeader: true, rowHeader: false, text: 'Value' },
  { row: 1, col: 0, rowSpan: 1, colSpan: 1, columnHeader: false, rowHeader: false, text: '2020' },
  { row: 1, col: 1, rowSpan: 1, colSpan: 1, columnHeader: false, rowHeader: false, text: '$1,200,000' },
];

describe('deterministic IDs — cross-runtime parity with the Python producer', () => {
  it('derives the same candidate ID the sidecar producer does', () => {
    const id = candidateId('src-p0001-tabl-0001-aaaa1111', 'docling-primary',
      { runtimeProfile: 'legacy', tableMode: null, cellMatching: null },
      PARITY_BBOX, 2, 2, 1, 0, PARITY_CELLS);
    expect(id).toBe('tblcand-70adb2c8-dpri-f6d96b6b');
  });

  it('derives the same cell ID the producer does', () => {
    expect(cellId('tblcand-70adb2c8-dpri-f6d96b6b', 0, 0, 1, 1)).toBe('tcell-b287bd45');
  });

  it('changing the provider profile changes the candidate ID', () => {
    const a = candidateId('r', 'docling-primary', { tableMode: 'fast', cellMatching: true }, PARITY_BBOX, 2, 2, 1, 0, PARITY_CELLS);
    const b = candidateId('r', 'docling-primary', { tableMode: 'accurate', cellMatching: false }, PARITY_BBOX, 2, 2, 1, 0, PARITY_CELLS);
    expect(a).not.toBe(b);
  });

  it('is deterministic', () => {
    const mk = () => candidateId('r', 'docling-fast', {}, PARITY_BBOX, 2, 2, 1, 0, PARITY_CELLS);
    expect(mk()).toBe(mk());
  });
});

// ── Validators ────────────────────────────────────────────────────────────────

function candidate(overrides: Record<string, unknown> = {}) {
  const id = 'tblcand-70adb2c8-dpri-f6d96b6b';
  return {
    version: TABLE_CANDIDATE_CONTRACT_VERSION, id, sourceRegionId: 'r', pageId: 'p', pageNumber: 1,
    provider: 'docling-primary', providerVersion: null, providerReference: null,
    profile: { runtimeProfile: 'legacy', pipelineFamily: null, tableMode: null, cellMatching: null, modelId: null, converterKey: null },
    bbox: PARITY_BBOX, numRows: 2, numCols: 2, headerRowCount: 1, headerColumnCount: 0,
    cells: [{ id: cellId(id, 0, 0, 1, 1), row: 0, col: 0, rowSpan: 1, colSpan: 1, columnHeader: true, rowHeader: false, text: 'Year', normalizedText: 'Year', numericTokens: [], punctuationTokens: [], bbox: null, confidence: null, providerReferences: [] }],
    caption: null, sourceCropPath: 'job/pages/page-001/regions/r.png', confidence: null, extractionElapsedMs: null,
    complete: true, problems: [], ...overrides,
  };
}

describe('validateTableCandidate', () => {
  it('accepts a valid candidate', () => { expect(validateTableCandidate(candidate())).toEqual([]); });
  it('rejects a bad version', () => { expect(validateTableCandidate(candidate({ version: 'x' }))).toContain('candidate_bad_version'); });
  it('rejects duplicate cell ids', () => {
    const c = candidate();
    c.cells.push({ ...c.cells[0] });
    expect(validateTableCandidate(c)).toContain('candidate_duplicate_cell_id');
  });
  it('rejects an unsafe crop path', () => {
    expect(validateTableCandidate(candidate({ sourceCropPath: '../../etc/passwd' }))).toContain('candidate_crop_path_unsafe');
  });
  it('rejects a non-finite bbox', () => {
    expect(validateTableCandidate(candidate({ bbox: { x: 0, y: 0, width: Infinity, height: 1 } }))).toContain('candidate_bbox_non_finite');
  });
});

function arbitration(state: string, overrides: Partial<TableArbitrationResultV1> = {}): TableArbitrationResultV1 {
  return {
    version: TABLE_ARBITRATION_VERSION, sourceRegionId: 'r', state: state as never,
    selectedCandidateId: state === 'native_verified' ? 'tblcand-x' : null, selectedIntegrityReport: null,
    rankedCandidateIds: [], rejectedCandidateIds: [], sourceCropAvailable: state === 'source_crop', reason: 'x', problems: [],
    ...overrides,
  };
}

describe('validateTableArbitration', () => {
  it('accepts a valid native_verified arbitration', () => {
    expect(validateTableArbitration(arbitration('native_verified')).ok).toBe(true);
  });
  it('flags source_crop without a crop', () => {
    const r = validateTableArbitration(arbitration('source_crop', { sourceCropAvailable: false }));
    expect(r.ok).toBe(false); expect(r.problems).toContain('source_crop_without_crop');
  });
  it('absent → absent state', () => { expect(validateTableArbitration(null).state).toBe('absent'); });
});

// ── Mapper header policy (no Column N) ────────────────────────────────────────

describe('deriveNativeHeaderPolicy', () => {
  it('uses source header text and never synthesizes Column N', () => {
    const p = deriveNativeHeaderPolicy({ headerRows: 1, numCols: 3, rows: [['Year', 'Value', 'Notes'], ['2020', '$1', 'x']] });
    expect(p.showHeader).toBe(true);
    expect(p.columnLabels).toEqual(['Year', 'Value', 'Notes']);
    expect(p.hasSourceHeaders).toBe(true);
    expect(p.genericHeaderInSource).toBe(false);
  });
  it('leaves a missing header label blank — NOT Column N', () => {
    const p = deriveNativeHeaderPolicy({ headerRows: 1, numCols: 3, rows: [['Year', '', undefined as never]] });
    expect(p.columnLabels).toEqual(['Year', '', '']);
    expect(p.columnLabels.some((l) => /column\s*\d/i.test(l))).toBe(false);
  });
  it('a header-less source shows no header and no labels', () => {
    const p = deriveNativeHeaderPolicy({ headerRows: 0, numCols: 2, rows: [['2019', '$1'], ['2020', '$2']] });
    expect(p.showHeader).toBe(false);
    expect(p.hasSourceHeaders).toBe(false);
  });
  it('flags a source that literally reads Column N', () => {
    const p = deriveNativeHeaderPolicy({ headerRows: 1, numCols: 2, rows: [['Column 1', 'Column 2']] });
    expect(p.genericHeaderInSource).toBe(true);
    expect(p.hasSourceHeaders).toBe(false);
  });
});

// ── Suppression ───────────────────────────────────────────────────────────────

function plan(regionId: string, mode: TablePreservationRegionPlanV1['renderMode']): TablePreservationRegionPlanV1 {
  return {
    version: TABLE_PRESERVATION_VERSION, regionId, pageNumber: 1, renderMode: mode,
    selectedCandidateId: null, sourceCropPath: 'j/r.png', suppressRegionIds: [], suppressOverlayIds: [],
    integrityState: 'n/a', integrityScore: null, hardDefectCodes: [], manualReviewRequired: false, reason: 'x',
  };
}

describe('resolveTableSuppression', () => {
  const tableBBoxes = { t1: { x: 40, y: 100, width: 400, height: 200 } as SourceBBox };
  const overlays: TableSuppressionOverlay[] = [
    { id: 'inside', bbox: { x: 60, y: 150, width: 40, height: 20 } },
    { id: 'outside', bbox: { x: 500, y: 600, width: 40, height: 20 } },
  ];

  it('a source-crop table suppresses overlapping overlays only', () => {
    const res = resolveTableSuppression([plan('t1', 'table-source-crop')], tableBBoxes, overlays);
    expect(res.suppressedOverlayIds).toEqual(['inside']);
    expect(res.keptOverlayIds).toEqual(['outside']);
  });
  it('a verified native table also suppresses duplicate child overlays', () => {
    const res = resolveTableSuppression([plan('t1', 'verified-native-table')], tableBBoxes, overlays);
    expect(res.suppressedOverlayIds).toEqual(['inside']);
  });
  it('a containment-fallback table suppresses nothing (E0 owns it)', () => {
    const res = resolveTableSuppression([plan('t1', 'containment-fallback')], tableBBoxes, overlays);
    expect(res.suppressedOverlayIds).toEqual([]);
  });
  it('never suppresses a page-sized overlay', () => {
    const res = resolveTableSuppression([plan('t1', 'table-source-crop')], tableBBoxes,
      [{ id: 'bg', bbox: { x: 0, y: 0, width: 595, height: 842 } }]);
    expect(res.suppressedOverlayIds).toEqual([]);
  });
});

// ── Document report + E0 handoff ──────────────────────────────────────────────

describe('buildTablePreservationReport + E0 handoff', () => {
  it('aggregates render modes across pages', () => {
    const report = buildTablePreservationReport([
      { pageNumber: 1, tables: [plan('t1', 'verified-native-table'), plan('t2', 'table-source-crop')] },
      { pageNumber: 2, tables: [plan('t3', 'blocked')] },
    ]);
    expect(report.tableRegionCount).toBe(3);
    expect(report.nativeVerifiedTableCount).toBe(1);
    expect(report.sourceCropTableCount).toBe(1);
    expect(report.blockedTableCount).toBe(1);
    expect(report.problems.some((p) => p.includes('table_blocked'))).toBe(true);
  });

  it('attaches additively without mutating the base', () => {
    const base = { version: 'x' } as const;
    const report = buildTablePreservationReport([]);
    const merged = attachTablePreservationSummary(base, report);
    expect(merged.tablePreservation).toBe(report);
    expect((base as Record<string, unknown>).tablePreservation).toBeUndefined();
  });

  it('maps arbitration state to the E0 requirement; invalid → null (never weakens E0)', () => {
    expect(tableContainmentRequirement(arbitration('native_verified'))).toBe('permit_score_based');
    expect(tableContainmentRequirement(arbitration('source_crop'))).toBe('protected_visual');
    expect(tableContainmentRequirement(arbitration('containment_fallback'))).toBe('page_fallback');
    expect(tableContainmentRequirement(arbitration('blocked'))).toBe('manual_review');
    expect(tableContainmentRequirement({ garbage: true })).toBeNull();
    expect(tableContainmentRequirement(null)).toBeNull();
  });
});

// ── Template integration bridge ───────────────────────────────────────────────

function tableRegion(id: string, bbox: SourceBBox, children: string[] = []) {
  return {
    version: 'source-region-v2', id, pageId: 'docling-page-1', pageNumber: 1, type: 'table' as const, bbox,
    polygon: null, readingOrder: null, zOrderHint: null, confidence: null,
    sourceCrop: { path: `j/${id}.png`, sha256: 'a'.repeat(64), mime: 'image/png' as const, widthPx: null, heightPx: null, sourceDpi: 300, paddingPt: 2 },
    text: null, table: null, chart: null, visual: null,
    relationships: { parentRegionId: null, childRegionIds: children, captionRegionIds: [], labelRegionIds: [] },
    providerEvidence: [], problems: [], complete: true,
  };
}

function childText(id: string, bbox: SourceBBox, parent: string) {
  return { ...tableRegion(id, bbox), type: 'text' as const, relationships: { parentRegionId: parent, childRegionIds: [], captionRegionIds: [], labelRegionIds: [] } };
}

describe('resolvePageTablePreservation (template bridge)', () => {
  const page = {
    id: 'page-1',
    blocks: [{ id: 'b1', overlays: [
      { id: 'ov-in', type: 'text', x: 60, y: 150, width: 40, height: 20 },
      { id: 'ov-out', type: 'text', x: 500, y: 600, width: 40, height: 20 },
    ] }],
  } as unknown as import('../templateSchema').Page;

  it('source-crop arbitration suppresses child overlays + children + requires review', () => {
    const region = tableRegion('t1', { x: 40, y: 100, width: 400, height: 200 }, ['child-1']);
    const child = childText('child-1', { x: 60, y: 150, width: 40, height: 20 }, 't1');
    const arb = arbitration('source_crop', { sourceCropAvailable: true });
    const res = resolvePageTablePreservation(page, [region, child] as never, { t1: arb }, 1);
    expect(res.plans[0].renderMode).toBe('table-source-crop');
    expect(res.plans[0].suppressRegionIds).toContain('child-1');
    expect(res.suppression.suppressedOverlayIds).toEqual(['ov-in']);
    expect(res.manualReviewRequired).toBe(true);
  });

  it('absent/invalid arbitration degrades to containment-fallback, never native', () => {
    const region = tableRegion('t1', { x: 40, y: 100, width: 400, height: 200 });
    const res = resolvePageTablePreservation(page, [region] as never, {}, 1);
    expect(res.plans[0].renderMode).toBe('containment-fallback');
    expect(res.requiresPageFallback).toBe(true);
  });

  it('native_verified renders native but keeps the crop reference', () => {
    const region = tableRegion('t1', { x: 40, y: 100, width: 400, height: 200 });
    const arb = arbitration('native_verified', { selectedCandidateId: 'tblcand-x' });
    const res = resolvePageTablePreservation(page, [region] as never, { t1: arb }, 1);
    expect(res.plans[0].renderMode).toBe('verified-native-table');
    expect(res.plans[0].sourceCropPath).toBe('j/t1.png');
  });
});
