export type MarketSourceType = 'rss' | 'atom' | 'official_api' | 'html_listing' | 'licensed_partner_feed' | 'manual' | 'feed_with_html_fallback' | 'rss_with_html_fallback' | 'rss_multi' | 'html_listing_or_licensed_feed';
export type MarketUpdateCategory = 'finance' | 'property_market' | 'construction' | 'policy_regulation' | 'rental_market' | 'economy' | 'planning_supply' | 'political' | 'other';
export type MarketGeography = 'Australia' | 'NSW' | 'VIC' | 'QLD' | 'WA' | 'SA' | 'TAS' | 'ACT' | 'NT' | 'Multi';
export type MarketImpactLevel = 'low' | 'medium' | 'high' | 'critical';
export type MarketAudienceTag = 'investors' | 'owner_occupiers' | 'first_home_buyers' | 'smsf' | 'developers' | 'buyers_agents' | 'mortgage_brokers' | 'property_managers' | 'builders' | 'finance_brokers';
export type MarketUpdateStatus = 'candidate' | 'published' | 'ignored' | 'rejected' | 'failed';
export type MarketSourceReliabilityTier = 'official' | 'tier_1_media' | 'industry' | 'partner' | 'manual' | 'watchlist';
export type MarketSourceRegistryStatus = 'canonical' | 'archived_legacy' | 'unresolved_legacy';
/**
 * How the ingestion pipeline treats a source.
 * - `live`     — fetched, and anything that clears the publication bar reaches the feed.
 * - `shadow`   — fetched and classified identically, but every item is held at
 *                `visibility: 'shadow'` and can never be published. This is how a
 *                source is validated on real traffic without touching the feed.
 * - `disabled` — not fetched at all; there is no reachable endpoint.
 */
export type MarketIngestMode = 'live' | 'shadow' | 'disabled';
export type MarketUpdateVisibility = 'public' | 'shadow';
export type MarketSegment = 'finance' | 'property' | 'construction' | 'political' | 'economic' | 'social' | 'policy_regulation' | 'rental';
export type MarketFreshnessTier = 'breaking' | 'today' | 'this_week' | 'older';
export type MarketDigestPeriod = '24h' | 'weekly' | 'biweekly' | 'monthly' | 'quarterly' | 'annual';

export type MarketUpdatesFailureStage = 'authentication' | 'database' | 'function' | 'network' | 'source_adapter' | 'classification' | 'ingestion' | 'digest' | 'qa' | 'configuration';
export type MarketUpdatesErrorCode = 'missing_session' | 'session_expired' | 'migration_missing' | 'rls_denied' | 'function_missing' | 'unauthorised' | 'forbidden' | 'server_error' | 'network_error' | 'registry_empty' | 'sources_disabled' | 'ingestion_empty' | 'source_failed' | 'source_fetch_failed' | 'source_parse_failed' | 'source_validation_failed' | 'database_insert_failed' | 'provider_not_configured' | 'provider_unauthorised' | 'provider_payment_required' | 'provider_rate_limited' | 'provider_timeout' | 'digest_failed' | 'cron_missing' | 'cron_stale' | 'ai_unavailable' | 'unknown';
export interface MarketUpdatesOperationalIssue { stage:MarketUpdatesFailureStage; code:MarketUpdatesErrorCode; message:string; remediation:string; httpStatus?:number; functionName?:string; correlationId?:string; retryable:boolean; }

export interface MarketSourceSeed { source_key:string; display_name:string; description:string; adapter_type:MarketSourceType; primary_url:string; feed_urls:string[]; listing_urls:string[]; source_authority:string; reliability_tier:MarketSourceReliabilityTier; default_segments:MarketSegment[]; default_category:MarketUpdateCategory; default_geography:MarketGeography[]; refresh_frequency_minutes:number; enabled:boolean; copyright_mode:string; extraction_policy:Record<string,unknown>; source_weight:number; relevant_keywords:string[]; excluded_keywords:string[]; perspective:string|null; adapter_config:Record<string,string>; }
export interface MarketSource { id: string; source_key?:string|null; name: string; description?: string | null; source_type: MarketSourceType; adapter_type?:MarketSourceType|null; url: string; primary_url?:string|null; feed_urls?:string[]; listing_urls?:string[]; adapter_config?:Record<string,unknown>; source_authority?:string|null; perspective?:string|null; copyright_mode?:string|null; legal_storage_policy?:'link_metadata_only'|'metadata_excerpt_transformative_summary'|'licensed_metadata_excerpt_transformative_summary'|null; category: MarketUpdateCategory; geography: MarketGeography; reliability_tier: MarketSourceReliabilityTier; enabled: boolean; /** Optional so a client running ahead of the deployed read contract still renders; fall back with `resolveIngestMode`. */ ingest_mode?:MarketIngestMode|null; shadow_since?:string|null; shadow_promotion_notes?:string|null; refresh_frequency_hours: number; refresh_frequency_minutes:number; next_eligible_fetch_at?:string|null; consecutive_failures?:number; health_status?:'healthy'|'degraded'|'failed'|'disabled'; registry_status?:MarketSourceRegistryStatus|null; superseded_by_source_id?:string|null; archived_at?:string|null; reconciliation_reason?:string|null; disabled_reason?:string|null; last_http_status?:number|null; last_latency_ms?:number|null; last_items_discovered?:number; last_items_published?:number; last_fetched_at?: string | null; last_success_at?: string | null; last_error?: string | null; created_at: string; updated_at: string; }
export interface MarketSourceRegistrySummary { canonical:number; enabledCanonical:number; disabledCanonical:number; archivedLegacy:number; unresolvedLegacy:number; totalRecords:number; matchedLegacy:number; mergedRows:number; updateReferencesReassigned:number; fetchRunReferencesReassigned:number; reconciledAt?:string|null; }
export interface MarketUpdate { id: string; correlation_id?:string|null; source_id?: string | null; source_name: string; source_url: string; canonical_url?:string|null; original_url?:string|null; source_authority?:string|null; source_perspective?:string|null; author?:string|null; public_excerpt?:string|null; source_published_at?: string | null; ingested_at: string; title: string; slug?: string | null; category: MarketUpdateCategory; segments: MarketSegment[]; freshness_tier: MarketFreshnessTier; geography: MarketGeography[]; impact_level: MarketImpactLevel; audience_tags: MarketAudienceTag[]; raw_excerpt?: string | null; raw_content_hash?: string | null; ai_summary?: string | null; key_points: string[]; why_it_matters?: string | null; property_implications?: string | null; finance_implications?: string | null; policy_implications?: string | null; risk_flags: string[]; lending_criteria_tags?:string[]; legal_topics?:string[]; economic_topics?:string[]; legal_status?:string|null; effective_date?:string|null; confidence_score?: number | null; citation_urls: string[]; relevance_score: number; status: MarketUpdateStatus; publication_reason?:string|null; candidate_reason?:string|null; ai_status?:string|null; ai_failure_code?:string|null; validation_failures?:string[]; failure_reason?: string | null; model_used?:string|null; route_used?:string|null; fallback_used?:boolean; ai_latency_ms?:number|null; ai_failure_reason?:string|null; dedupe_hash: string; visibility?:MarketUpdateVisibility|null; shadow_would_publish?:boolean|null; archived_at?:string|null; archived_by?:string|null; pre_archive_status?:MarketUpdateStatus|null; created_at: string; updated_at: string; }
export interface ArchivedMarketUpdate extends MarketUpdate { archived_at:string; archived_by?:string|null; pre_archive_status:MarketUpdateStatus; }
export interface MarketUpdateArchivePage { items:ArchivedMarketUpdate[]; count:number; page:number; pageSize:number; hasMore:boolean; }
export type MarketUpdateArchiveOutcome = 'archived' | 'already_archived' | 'restored' | 'already_restored';
export interface SetMarketNewsArchiveStateInput { updateId:string; archived:boolean; }
export interface SetMarketNewsArchiveStateResult {
  id:string;
  isArchived:boolean;
  archivedAt:string|null;
  outcome:MarketUpdateArchiveOutcome;
  correlationId:string;
}
export interface MarketDigest24h { id: string; correlation_id?:string|null; period: MarketDigestPeriod; period_key?:string; generated_at: string; period_start: string; period_end: string; queued_at?:string|null; started_at?:string|null; completed_at?:string|null; executive_summary: string; top_update_ids: string[]; finance_lending_highlights: string[]; property_market_highlights: string[]; construction_supply_highlights: string[]; policy_regulation_highlights: string[]; political_economic_watchpoints: string[]; social_watchpoints: string[]; /** The digest tool schema emits a plain narrative string per segment; older rows used the structured shape. */
  segment_breakdown: Record<string, string | { headline?: string; highlights?: string[]; implications?: string }>; buyer_implications?: string | null; investor_implications?: string | null; broker_adviser_implications?: string | null; client_advisory_implications: string[]; recommended_watchlist_for_tomorrow: string[]; source_urls: string[]; confidence_score?: number | null; status: 'queued' | 'generating' | 'published' | 'draft' | 'failed' | 'no_data'; update_count?:number; candidate_count?:number; last_published_update_at?:string|null; error_code?:string|null; safe_error_message?:string|null; model_used?:string|null; route_used?:string|null; fallback_used?:boolean; ai_latency_ms?:number|null; ai_failure_reason?:string|null; }
export interface MarketQAKeyFigure { label: string; value: string; source_id?: string }
export type MarketQATimeHorizon = 'immediate' | 'short_term' | 'medium_term' | 'long_term' | 'unclear';
export type MarketQASentiment = 'positive' | 'neutral' | 'cautious' | 'negative';
export interface MarketQARetrievedItem { id: string; title: string; source_name: string; source_url: string; source_published_at?: string | null; impact_level?: string | null; used: boolean; /** Which retrieval strategies surfaced this item — 'focus' marks the update the question was asked about. */ strategies?: string[]; }
/** How much breadth the answer is allowed to gather, traded against turnaround. */
export type MarketQADepth = 'brief' | 'standard' | 'deep';
/** Per-audience reading of the same evidence. Fields are empty when the sources do not support one. */
export interface MarketQAImplications { investors?: string; owner_occupiers?: string; first_home_buyers?: string; developers?: string; brokers?: string; }
export interface MarketQATimelineEntry { date: string; event: string; source_id?: string }
/** Live progress emitted while the research pipeline runs, so a longer answer does not read as a hang. */
export interface MarketQAStage { stage: 'planning' | 'searching' | 'reading' | 'analysing'; label: string; queries?: string[]; context_size?: number; sources?: number; depth?: MarketQADepth; retrieval_mode?: string; }
export interface MarketQAMessage { id: string; correlation_id?:string|null; role: 'user' | 'assistant'; content: string; citations: string[]; source_update_ids: string[]; confidence_score?: number | null; limitations: string[]; created_at: string; follow_up_questions?: string[]; key_figures?: MarketQAKeyFigure[]; time_horizon?: MarketQATimeHorizon; sentiment?: MarketQASentiment; model_used?: string; route_used?:string; fallback_used?:boolean; retrieved?: MarketQARetrievedItem[]; question_id?: string | null; rate_limited?: boolean; depth_mode?: MarketQADepth; implications?: MarketQAImplications; timeline?: MarketQATimelineEntry[]; watch_items?: string[]; contrarian_view?: string; retrieval_mode?: string; context_size?: number; strategies?: string[]; research_plan?: { resolved_question?: string; queries?: string[] }; }
export interface MarketUpdateFilters { category?: MarketUpdateCategory | 'all'; geography?: MarketGeography | 'all'; impact?: MarketImpactLevel | 'all'; audience?: MarketAudienceTag | 'all'; segment?: MarketSegment | 'all'; freshness?: MarketFreshnessTier | 'all'; search?: string; dateRange?: { from?: string; to?: string }; status?: MarketUpdateStatus; limit?: number; }
export interface MarketIngestionSummary { runId?:string; status?:MarketIngestionRun['status']; active?:boolean; sourcesConsidered?:number; sourcesProcessed?:number; sourcesSucceeded?:number; sourcesFailed?:number; discovered?:number; classified?:number; ingested: number; published: number; candidates: number; ignored: number; rejected?:number; persistenceFailed?:number; failed: number; skippedDuplicates: number; /** Shadow-mode sources exercised by the run, and what they would have published had they been live. */ shadowSources?:number; shadowIngested?:number; shadowWouldPublish?:number; sourceErrors: Array<{ sourceId: string; message: string }>; message?: string; }
export interface NormalisedMarketSourceItem { source_id?: string | null; source_name: string; source_url: string; source_published_at?: string | null; title: string; excerpt?: string | null; content?: string | null; category?: MarketUpdateCategory; geography?: MarketGeography[]; audience_tags?: MarketAudienceTag[]; }
export interface MarketIngestionRun { id:string; correlation_id?:string|null; trigger_type:'cron'|'page_open'|'manual'|'digest_prerequisite'|'retry'|'source_test'; started_at:string; completed_at?:string|null; status:'queued'|'running'|'completed'|'partial'|'failed'|'skipped_fresh'; sources_considered:number; sources_processed:number; sources_succeeded:number; sources_failed:number; items_discovered:number; items_deduplicated?:number; items_classified?:number; items_published:number; items_candidate?:number; items_ignored?:number; items_rejected?:number; items_failed?:number; duration_ms?:number|null; error_summary?:string|null; metadata?:Record<string,any>; }
/** Evidence accumulated for a shadow-mode source since it entered shadow. */
export interface MarketShadowSourceMetric { source_id:string; source_key?:string|null; name:string; ingest_mode:MarketIngestMode; shadow_since?:string|null; shadow_promotion_notes?:string|null; health_status?:string|null; source_authority?:string|null; shadow_items:number; would_publish:number; below_relevance:number; rejected:number; avg_relevance?:number|null; avg_confidence?:number|null; last_shadow_item_at?:string|null; }
export interface MarketSourceHealth { totalSources:number; enabledSources:number; healthySources:number; degradedSources:number; failedSources:number; shadowSources?:number; shadowHealthySources?:number; heldSources?:number; shadowMetrics?:MarketShadowSourceMetric[]; archivedLegacy?:number|null; unresolvedLegacy?:number|null; publishedUpdates?:number|null; candidates?:number|null; ignored?:number|null; archivedUpdates?:number|null; lastFetchedAt?:string|null; lastSuccessAt?:string|null; lastError?:string|null; nextScheduledFetch?:string|null; latestRun?:MarketIngestionRun|null; latestSourceFetch?:Record<string,unknown>|null; latestDigest?:Record<string,unknown>|null; latestCronRun?:MarketIngestionRun|null; activeRun?:MarketIngestionRun|null; agents?:Array<{agentKey:string; configured:boolean; route?:string; modelId?:string; fallbackCount?:number;lastUsedAt?:string|null; hasError?:boolean; updatedAt?:string|null}>; openRouter?:{configured:boolean;enabled:boolean;lastTestAt?:string|null;lastTestSuccess?:boolean|null}; automation?:{lastDispatchAt?:string|null;lastIngestionDispatchAt?:string|null;cronStale?:boolean;configuredJobCount?:number;expectedJobCount?:number;requiredSecretsPresent?:boolean;alerts?:Array<{key:string;severity:'warning'|'error';message:string;last_detected_at?:string}>}|null; warnings?:string[]; }
export interface MarketQASourceContext { update_id: string; title: string; summary: string; citations: string[]; source_url: string; }
export interface MarketDigestGenerationResult { digest: MarketDigest24h | null; message: string; noData: boolean; }
