/**
 * Builder stock — reading a lossless WebP (VP8L).
 *
 * WHY THIS IS HERE AT ALL. Display eligibility decides by DECODING the picture
 * and measuring what has been drawn on it, and it fails closed: a container no
 * decoder here reads is `pending`, which shows no image. Builder Stock accepts
 * WebP, so leaving it undecodable meant every future WebP upload — including a
 * perfectly clean builder photograph — had an empty card. Failing closed is
 * right; failing closed on a format the product accepts is a gap, not a policy.
 *
 * WHY IT IS WRITTEN RATHER THAN INSTALLED. This runs inside a Supabase edge
 * function. The vetted decoder for WebP is libwebp, which reaches JavaScript
 * only as a WebAssembly or asm.js build — a binary blob nobody reviewing this
 * repository can read, fetched at deploy time, for a module whose entire job is
 * to be a deterministic, bounded, auditable measurement. So the format is
 * implemented from its specification, in the same shape as the PNG, JPEG and
 * GIF readers beside it, and validated against libwebp's own output through
 * fixtures generated by it.
 *
 * WHAT IT IS ALLOWED TO COST. Everything here is bounded before it is
 * attempted: dimensions are checked against the caller's pixel ceiling before a
 * buffer is allocated, every Huffman read is length-limited, and a backward
 * reference that points outside the picture ends the decode rather than
 * wrapping. A malformed file returns null; it never throws and never loops.
 *
 * NOTHING HERE WRITES ANYTHING. The bytes handed in are read and not modified,
 * and the pixels produced exist only to be measured.
 */

/**
 * A pixel buffer this module allocated, named with its backing store.
 *
 * `Uint32Array` on its own means `Uint32Array<ArrayBufferLike>`, which admits a
 * `SharedArrayBuffer` — so a function returning one cannot be assigned to a
 * variable holding a buffer this module made, and the transforms below hand
 * exactly that back. Every buffer here is a fresh `new Uint32Array(n)`, so
 * saying so is both accurate and what makes the assignment type-check.
 *
 * Deliberately used on RETURNS and locals only. Parameters stay the wide
 * `Uint32Array`: narrowing what a function will accept would be the opposite
 * of a fix.
 */
type PixelBuffer = Uint32Array<ArrayBuffer>;

/** A decoded picture: 8-bit RGB triples, row-major. */
export interface WebpRaster {
  width: number;
  height: number;
  /** RGB, three bytes per pixel. Alpha is composited away by the caller. */
  pixels: Uint8Array;
  /** ARGB, one word per pixel, in case the caller wants the alpha. */
  argb: Uint32Array;
}

/**
 * A bit reader in VP8L's order: least-significant bit first, within bytes read
 * in increasing address order.
 *
 * `ok` goes false the first time a read runs past the end and never goes back.
 * Every loop in this file checks it, so a truncated file terminates instead of
 * decoding zeroes for ever.
 */
export class LosslessBitReader {
  private bitPosition = 0;
  ok = true;

  constructor(private readonly bytes: Uint8Array, private readonly start = 0,
    private readonly end = bytes.length) {}

  read(count: number): number {
    let value = 0;
    for (let i = 0; i < count; i++) {
      const index = this.start + (this.bitPosition >> 3);
      if (index >= this.end) { this.ok = false; return value; }
      const bit = (this.bytes[index] >> (this.bitPosition & 7)) & 1;
      value |= bit << i;
      this.bitPosition += 1;
    }
    return value >>> 0;
  }
}

// ---------------------------------------------------------------------------
// Huffman
// ---------------------------------------------------------------------------

/**
 * A canonical Huffman code, held as a flat table indexed by the next
 * `maxLength` bits.
 *
 * Table-driven rather than tree-walking because the decode reads several
 * million symbols on a large picture and a pointer chase per bit is the whole
 * cost. `maxLength` is capped at 15 by the format.
 */
interface HuffmanCode {
  /** For each index: symbol in the low 16 bits, length in the high bits. */
  table: Int32Array;
  maxLength: number;
  /** A code with exactly one symbol consumes no bits at all. */
  single: number;
}

const MAX_CODE_LENGTH = 15;

function buildHuffman(lengths: Uint8Array | number[]): HuffmanCode | null {
  let maxLength = 0;
  let used = 0;
  let onlySymbol = -1;
  for (let symbol = 0; symbol < lengths.length; symbol++) {
    const length = lengths[symbol];
    if (!length) continue;
    if (length > MAX_CODE_LENGTH) return null;
    if (length > maxLength) maxLength = length;
    used += 1;
    onlySymbol = symbol;
  }
  if (!used) return null;
  if (used === 1) {
    return { table: new Int32Array(1), maxLength: 0, single: onlySymbol };
  }

  const counts = new Int32Array(MAX_CODE_LENGTH + 1);
  for (const length of lengths) counts[length] += 1;
  counts[0] = 0;

  // Canonical assignment, and a completeness check: an over-subscribed or
  // under-subscribed code is a corrupt file, not something to decode past.
  const nextCode = new Int32Array(MAX_CODE_LENGTH + 2);
  let code = 0;
  let left = 1;
  for (let length = 1; length <= MAX_CODE_LENGTH; length++) {
    left <<= 1;
    left -= counts[length];
    if (left < 0) return null;
    code = (code + counts[length - 1]) << 1;
    nextCode[length] = code;
  }
  if (left !== 0) return null;

  const size = 1 << maxLength;
  const table = new Int32Array(size).fill(-1);
  for (let symbol = 0; symbol < lengths.length; symbol++) {
    const length = lengths[symbol];
    if (!length) continue;
    const canonical = nextCode[length]++;
    // The reader hands over bits least-significant first, so the canonical
    // code (which is most-significant first) is reversed once, here, rather
    // than the bits being reversed on every read.
    let reversed = 0;
    for (let bit = 0; bit < length; bit++) {
      reversed = (reversed << 1) | ((canonical >> bit) & 1);
    }
    const step = 1 << length;
    for (let index = reversed; index < size; index += step) {
      table[index] = (length << 16) | symbol;
    }
  }
  return { table, maxLength, single: -1 };
}

/** Peek `maxLength` bits, consume only what the matched code actually used. */
function readSymbol(reader: LosslessBitReader, code: HuffmanCode): number {
  if (code.single >= 0) return code.single;
  // Read one bit at a time against the table: the table is indexed by the
  // low bits, so a prefix match is found by growing the index.
  let index = 0;
  for (let length = 1; length <= code.maxLength; length++) {
    index |= reader.read(1) << (length - 1);
    if (!reader.ok) return -1;
    const entry = code.table[index];
    if (entry >= 0 && (entry >> 16) === length) return entry & 0xffff;
  }
  return -1;
}

/** The order the code-length code's own lengths arrive in. From the spec. */
const CODE_LENGTH_ORDER = [
  17, 18, 0, 1, 2, 3, 4, 5, 16, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
];

function readHuffmanCode(
  reader: LosslessBitReader, alphabetSize: number,
): HuffmanCode | null {
  const simple = reader.read(1);
  if (!reader.ok) return null;

  if (simple) {
    const symbolCount = reader.read(1) + 1;
    const firstIsByte = reader.read(1);
    const lengths = new Uint8Array(alphabetSize);
    const first = firstIsByte ? reader.read(8) : reader.read(1);
    if (first >= alphabetSize) return null;
    if (symbolCount === 1) {
      lengths[first] = 1;
      return { table: new Int32Array(1), maxLength: 0, single: first };
    }
    const second = reader.read(8);
    if (second >= alphabetSize || !reader.ok) return null;
    lengths[first] = 1;
    lengths[second] = 1;
    return buildHuffman(lengths);
  }

  const codeLengthCount = reader.read(4) + 4;
  if (codeLengthCount > CODE_LENGTH_ORDER.length) return null;
  const codeLengthLengths = new Uint8Array(19);
  for (let i = 0; i < codeLengthCount; i++) {
    codeLengthLengths[CODE_LENGTH_ORDER[i]] = reader.read(3);
  }
  if (!reader.ok) return null;
  const lengthCode = buildHuffman(codeLengthLengths);
  if (!lengthCode) return null;

  let maxSymbol = alphabetSize;
  if (reader.read(1)) {
    const lengthBits = 2 + 2 * reader.read(3);
    maxSymbol = 2 + reader.read(lengthBits);
    if (maxSymbol > alphabetSize) return null;
  }
  if (!reader.ok) return null;

  const lengths = new Uint8Array(alphabetSize);
  let previous = 8;
  let symbol = 0;
  while (symbol < alphabetSize) {
    if (maxSymbol-- === 0) break;
    const value = readSymbol(reader, lengthCode);
    if (value < 0) return null;
    if (value < 16) {
      lengths[symbol++] = value;
      if (value) previous = value;
      continue;
    }
    let repeat: number;
    let fill: number;
    if (value === 16) { repeat = 3 + reader.read(2); fill = previous; }
    else if (value === 17) { repeat = 3 + reader.read(3); fill = 0; }
    else { repeat = 11 + reader.read(7); fill = 0; }
    if (!reader.ok) return null;
    if (symbol + repeat > alphabetSize) return null;
    for (let i = 0; i < repeat; i++) lengths[symbol++] = fill;
  }
  return buildHuffman(lengths);
}

// ---------------------------------------------------------------------------
// Backward references
// ---------------------------------------------------------------------------

/** Prefix-coded value: 4 direct codes, then offset + extra bits. */
function prefixValue(reader: LosslessBitReader, prefix: number): number {
  if (prefix < 4) return prefix + 1;
  const extraBits = (prefix - 2) >> 1;
  const offset = (2 + (prefix & 1)) << extraBits;
  return offset + reader.read(extraBits) + 1;
}

/**
 * The 120 short distances, as (y << 4 | 8 - x) pairs. Straight from the
 * specification: the first 120 distance codes name a nearby pixel by its
 * position rather than by a linear offset, because a picture's repeats are
 * two-dimensional.
 */
const CODE_TO_PLANE = [
  0x18, 0x07, 0x17, 0x19, 0x28, 0x06, 0x27, 0x29, 0x16, 0x1a, 0x26, 0x2a, 0x38,
  0x05, 0x37, 0x39, 0x15, 0x1b, 0x36, 0x3a, 0x25, 0x2b, 0x48, 0x04, 0x47, 0x49,
  0x14, 0x1c, 0x35, 0x3b, 0x46, 0x4a, 0x24, 0x2c, 0x58, 0x45, 0x4b, 0x34, 0x3c,
  0x03, 0x57, 0x59, 0x13, 0x1d, 0x56, 0x5a, 0x23, 0x2d, 0x44, 0x4c, 0x55, 0x5b,
  0x33, 0x3d, 0x68, 0x02, 0x67, 0x69, 0x12, 0x1e, 0x66, 0x6a, 0x22, 0x2e, 0x54,
  0x5c, 0x43, 0x4d, 0x65, 0x6b, 0x32, 0x3e, 0x78, 0x01, 0x77, 0x79, 0x53, 0x5d,
  0x11, 0x1f, 0x64, 0x6c, 0x42, 0x4e, 0x76, 0x7a, 0x21, 0x2f, 0x75, 0x7b, 0x31,
  0x3f, 0x63, 0x6d, 0x52, 0x5e, 0x00, 0x74, 0x7c, 0x41, 0x4f, 0x10, 0x20, 0x62,
  0x6e, 0x30, 0x73, 0x7d, 0x51, 0x5f, 0x40, 0x72, 0x7e, 0x61, 0x6f, 0x50, 0x71,
  0x7f, 0x60, 0x70,
];

function planeToDistance(width: number, planeCode: number): number {
  if (planeCode > 120) return planeCode - 120;
  const code = CODE_TO_PLANE[planeCode - 1];
  const distance = (code >> 4) * width + (8 - (code & 0x0f));
  return distance < 1 ? 1 : distance;
}

// ---------------------------------------------------------------------------
// Transforms
// ---------------------------------------------------------------------------

const PREDICTOR_TRANSFORM = 0;
const COLOR_TRANSFORM = 1;
const SUBTRACT_GREEN = 2;
const COLOR_INDEXING_TRANSFORM = 3;

interface Transform {
  type: number;
  bits: number;
  width: number;
  height: number;
  data: Uint32Array;
}

const clamp255 = (value: number) => value < 0 ? 0 : value > 255 ? 255 : value;

/** Average of two packed ARGB values, per channel. */
function average2(a: number, b: number): number {
  return ((((a >>> 24) + (b >>> 24)) >> 1) << 24
    | ((((a >> 16) & 0xff) + ((b >> 16) & 0xff)) >> 1) << 16
    | ((((a >> 8) & 0xff) + ((b >> 8) & 0xff)) >> 1) << 8
    | (((a & 0xff) + (b & 0xff)) >> 1)) >>> 0;
}

/** The specification's gradient predictor, clamped per channel. */
function clampAddSubtractFull(left: number, top: number, topLeft: number): number {
  let out = 0;
  for (let shift = 0; shift < 32; shift += 8) {
    const value = ((left >> shift) & 0xff) + ((top >> shift) & 0xff)
      - ((topLeft >> shift) & 0xff);
    out |= clamp255(value) << shift;
  }
  return out >>> 0;
}

function select(top: number, left: number, topLeft: number): number {
  let predictLeft = 0;
  let predictTop = 0;
  for (let shift = 0; shift < 32; shift += 8) {
    const t = (top >> shift) & 0xff;
    const l = (left >> shift) & 0xff;
    const tl = (topLeft >> shift) & 0xff;
    predictLeft += Math.abs(tl - t);
    predictTop += Math.abs(tl - l);
  }
  return predictLeft < predictTop ? left : top;
}

function clampAddSubtractHalf(a: number, b: number): number {
  let out = 0;
  for (let shift = 0; shift < 32; shift += 8) {
    const av = (a >> shift) & 0xff;
    const bv = (b >> shift) & 0xff;
    // Truncating halving, not an arithmetic shift: the reference divides by
    // two in C, which rounds toward zero, and `>> 1` rounds toward minus
    // infinity. They differ on every negative odd difference.
    out |= clamp255(av + ((av - bv) / 2 | 0)) << shift;
  }
  return out >>> 0;
}

function predict(mode: number, left: number, top: number, topLeft: number,
  topRight: number): number {
  switch (mode) {
    case 0: return 0xff000000;
    case 1: return left;
    case 2: return top;
    case 3: return topRight;
    case 4: return topLeft;
    case 5: return average2(average2(left, topRight), top);
    case 6: return average2(left, topLeft);
    case 7: return average2(left, top);
    case 8: return average2(topLeft, top);
    case 9: return average2(top, topRight);
    case 10: return average2(average2(left, topLeft), average2(top, topRight));
    case 11: return select(top, left, topLeft);
    case 12: return clampAddSubtractFull(left, top, topLeft);
    case 13: return clampAddSubtractHalf(average2(left, top), topLeft);
    default: return 0xff000000;
  }
}

function applyPredictor(pixels: Uint32Array, width: number, height: number,
  transform: Transform): void {
  const bits = transform.bits;
  const tilesPerRow = (width + (1 << bits) - 1) >> bits;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const index = y * width + x;
      if (y === 0 && x === 0) {
        pixels[index] = (pixels[index] + 0xff000000) >>> 0;
        continue;
      }
      let predicted: number;
      if (y === 0) predicted = pixels[index - 1];
      else if (x === 0) predicted = pixels[index - width];
      else {
        const tile = transform.data[(y >> bits) * tilesPerRow + (x >> bits)];
        const mode = (tile >> 8) & 0xff;
        const left = pixels[index - 1];
        const top = pixels[index - width];
        const topLeft = pixels[index - width - 1];
        /*
         * NO SPECIAL CASE ON THE LAST COLUMN, deliberately. The reference
         * decoder reads its row buffer straight through, so "top-right" of the
         * rightmost pixel is the FIRST PIXEL OF THE CURRENT ROW — an artefact
         * of the layout that the format then depends on. Clamping to the pixel
         * above instead is a plausible-looking read that puts a handful of
         * pixels per picture wrong, which is not lossless.
         */
        const topRight = pixels[index - width + 1];
        predicted = predict(mode, left, top, topLeft, topRight);
      }
      const value = pixels[index];
      pixels[index] = (
        ((((value >>> 24) + (predicted >>> 24)) & 0xff) << 24)
        | (((((value >> 16) & 0xff) + ((predicted >> 16) & 0xff)) & 0xff) << 16)
        | (((((value >> 8) & 0xff) + ((predicted >> 8) & 0xff)) & 0xff) << 8)
        | (((value & 0xff) + (predicted & 0xff)) & 0xff)
      ) >>> 0;
    }
  }
}

const signed8 = (value: number) => (value << 24) >> 24;

function applyColourTransform(pixels: Uint32Array, width: number, height: number,
  transform: Transform): void {
  const bits = transform.bits;
  const tilesPerRow = (width + (1 << bits) - 1) >> bits;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const tile = transform.data[(y >> bits) * tilesPerRow + (x >> bits)];
      const greenToRed = signed8(tile & 0xff);
      const greenToBlue = signed8((tile >> 8) & 0xff);
      const redToBlue = signed8((tile >> 16) & 0xff);

      const index = y * width + x;
      const value = pixels[index];
      const green = (value >> 8) & 0xff;
      let red = (value >> 16) & 0xff;
      let blue = value & 0xff;
      red = (red + ((greenToRed * signed8(green)) >> 5)) & 0xff;
      blue = (blue + ((greenToBlue * signed8(green)) >> 5)
        + ((redToBlue * signed8(red)) >> 5)) & 0xff;
      pixels[index] = ((value & 0xff00ff00) | (red << 16) | blue) >>> 0;
    }
  }
}

function applySubtractGreen(pixels: Uint32Array): void {
  for (let i = 0; i < pixels.length; i++) {
    const value = pixels[i];
    const green = (value >> 8) & 0xff;
    pixels[i] = ((value & 0xff00ff00)
      | ((((value >> 16) & 0xff) + green) & 0xff) << 16
      | (((value & 0xff) + green) & 0xff)) >>> 0;
  }
}

/** Expand a palette-indexed row back to full width. */
function applyColourIndexing(pixels: Uint32Array, packedWidth: number, width: number,
  height: number, transform: Transform): PixelBuffer | null {
  const paletteSize = transform.width;
  const bitsPerPixel = paletteSize <= 2 ? 1 : paletteSize <= 4 ? 2 : paletteSize <= 16 ? 4 : 8;
  const perByte = 8 / bitsPerPixel;
  const out = new Uint32Array(width * height);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const packedIndex = y * packedWidth + ((x / perByte) | 0);
      if (packedIndex >= pixels.length) return null;
      const green = (pixels[packedIndex] >> 8) & 0xff;
      const shift = bitsPerPixel * (x % perByte);
      const entry = (green >> shift) & ((1 << bitsPerPixel) - 1);
      out[y * width + x] = entry < paletteSize ? transform.data[entry] : 0xff000000;
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// The image stream
// ---------------------------------------------------------------------------

const COLOUR_CACHE_MULTIPLIER = 0x1e35a7bd;

interface HuffmanGroup {
  green: HuffmanCode;
  red: HuffmanCode;
  blue: HuffmanCode;
  alpha: HuffmanCode;
  distance: HuffmanCode;
}

function readHuffmanGroups(reader: LosslessBitReader, count: number,
  cacheBits: number): HuffmanGroup[] | null {
  const greenAlphabet = 256 + 24 + (cacheBits ? 1 << cacheBits : 0);
  const groups: HuffmanGroup[] = [];
  for (let i = 0; i < count; i++) {
    const green = readHuffmanCode(reader, greenAlphabet);
    const red = readHuffmanCode(reader, 256);
    const blue = readHuffmanCode(reader, 256);
    const alpha = readHuffmanCode(reader, 256);
    const distance = readHuffmanCode(reader, 40);
    if (!green || !red || !blue || !alpha || !distance) return null;
    groups.push({ green, red, blue, alpha, distance });
  }
  return groups;
}

interface StreamOptions {
  /** Only the top-level stream carries transforms and meta-Huffman. */
  topLevel: boolean;
  maxPixels: number;
}

/**
 * Decode one entropy-coded image, and the transforms wrapped around it.
 *
 * Recursive by design: the predictor map, the colour-transform map and the
 * palette are each an image in this same format, one level down, without
 * transforms of their own.
 */
function decodeImageStream(
  reader: LosslessBitReader, width: number, height: number, options: StreamOptions,
): { pixels: PixelBuffer; width: number; height: number } | null {
  if (width <= 0 || height <= 0) return null;
  if (width * height > options.maxPixels) return null;

  const transforms: Transform[] = [];
  let streamWidth = width;

  if (options.topLevel) {
    const seen = new Set<number>();
    while (reader.read(1)) {
      if (!reader.ok) return null;
      const type = reader.read(2);
      // Each transform may appear once. Without this a crafted file can
      // declare thousands and exhaust the budget before a pixel is read.
      if (seen.has(type)) return null;
      seen.add(type);

      if (type === PREDICTOR_TRANSFORM || type === COLOR_TRANSFORM) {
        const bits = reader.read(3) + 2;
        const tileWidth = (streamWidth + (1 << bits) - 1) >> bits;
        const tileHeight = (height + (1 << bits) - 1) >> bits;
        const sub = decodeImageStream(reader, tileWidth, tileHeight,
          { topLevel: false, maxPixels: options.maxPixels });
        if (!sub) return null;
        transforms.push({
          type, bits, width: tileWidth, height: tileHeight, data: sub.pixels,
        });
      } else if (type === SUBTRACT_GREEN) {
        transforms.push({ type, bits: 0, width: 0, height: 0, data: new Uint32Array(0) });
      } else if (type === COLOR_INDEXING_TRANSFORM) {
        const paletteSize = reader.read(8) + 1;
        const sub = decodeImageStream(reader, paletteSize, 1,
          { topLevel: false, maxPixels: options.maxPixels });
        if (!sub) return null;
        // The palette is stored as deltas along its own row.
        for (let i = 1; i < paletteSize; i++) {
          const previous = sub.pixels[i - 1];
          const value = sub.pixels[i];
          sub.pixels[i] = (
            ((((value >>> 24) + (previous >>> 24)) & 0xff) << 24)
            | (((((value >> 16) & 0xff) + ((previous >> 16) & 0xff)) & 0xff) << 16)
            | (((((value >> 8) & 0xff) + ((previous >> 8) & 0xff)) & 0xff) << 8)
            | (((value & 0xff) + (previous & 0xff)) & 0xff)
          ) >>> 0;
        }
        const bitsPerPixel = paletteSize <= 2 ? 1 : paletteSize <= 4 ? 2
          : paletteSize <= 16 ? 4 : 8;
        const perByte = 8 / bitsPerPixel;
        transforms.push({
          type, bits: bitsPerPixel, width: paletteSize, height: 1, data: sub.pixels,
        });
        streamWidth = Math.ceil(streamWidth / perByte);
      } else {
        return null;
      }
      if (!reader.ok) return null;
    }
    if (!reader.ok) return null;
  }

  // ── colour cache ─────────────────────────────────────────────────────────
  let cacheBits = 0;
  if (reader.read(1)) {
    cacheBits = reader.read(4);
    if (cacheBits < 1 || cacheBits > 11) return null;
  }
  if (!reader.ok) return null;

  // ── meta-Huffman ─────────────────────────────────────────────────────────
  let groupCount = 1;
  let metaBits = 0;
  let metaWidth = 0;
  let metaImage: Uint32Array | null = null;
  if (options.topLevel && reader.read(1)) {
    metaBits = reader.read(3) + 2;
    const metaW = (streamWidth + (1 << metaBits) - 1) >> metaBits;
    const metaH = (height + (1 << metaBits) - 1) >> metaBits;
    const sub = decodeImageStream(reader, metaW, metaH,
      { topLevel: false, maxPixels: options.maxPixels });
    if (!sub) return null;
    metaWidth = metaW;
    metaImage = sub.pixels;
    let highest = 0;
    for (const value of metaImage) {
      const group = ((value >> 8) & 0xffff);
      if (group > highest) highest = group;
    }
    groupCount = highest + 1;
    if (groupCount > 1 << 16) return null;
  }
  if (!reader.ok) return null;

  const groups = readHuffmanGroups(reader, groupCount, cacheBits);
  if (!groups) return null;

  // ── pixels ───────────────────────────────────────────────────────────────
  const count = streamWidth * height;
  const pixels = new Uint32Array(count);
  const cache = cacheBits ? new Uint32Array(1 << cacheBits) : null;
  const cacheShift = 32 - cacheBits;

  let position = 0;
  let x = 0;
  let y = 0;
  while (position < count) {
    if (!reader.ok) return null;
    const group = metaImage
      ? groups[((metaImage[(y >> metaBits) * metaWidth + (x >> metaBits)] >> 8) & 0xffff)]
      : groups[0];
    if (!group) return null;

    const symbol = readSymbol(reader, group.green);
    if (symbol < 0) return null;

    if (symbol < 256) {
      const red = readSymbol(reader, group.red);
      const blue = readSymbol(reader, group.blue);
      const alpha = readSymbol(reader, group.alpha);
      if (red < 0 || blue < 0 || alpha < 0) return null;
      const value = ((alpha << 24) | (red << 16) | (symbol << 8) | blue) >>> 0;
      pixels[position] = value;
      if (cache) cache[Math.imul(COLOUR_CACHE_MULTIPLIER, value) >>> cacheShift] = value;
      position += 1;
      if (++x === streamWidth) { x = 0; y += 1; }
      continue;
    }

    if (symbol < 256 + 24) {
      const length = prefixValue(reader, symbol - 256);
      const distanceSymbol = readSymbol(reader, group.distance);
      if (distanceSymbol < 0) return null;
      const planeCode = prefixValue(reader, distanceSymbol);
      const distance = planeToDistance(streamWidth, planeCode);
      if (distance > position || position + length > count) return null;
      for (let i = 0; i < length; i++) {
        const value = pixels[position - distance];
        pixels[position] = value;
        if (cache) cache[Math.imul(COLOUR_CACHE_MULTIPLIER, value) >>> cacheShift] = value;
        position += 1;
        if (++x === streamWidth) { x = 0; y += 1; }
      }
      continue;
    }

    if (!cache) return null;
    const entry = symbol - 256 - 24;
    if (entry >= cache.length) return null;
    const value = cache[entry];
    pixels[position] = value;
    position += 1;
    if (++x === streamWidth) { x = 0; y += 1; }
  }

  // ── unwind the transforms, last declared first ───────────────────────────
  let out = pixels;
  let outWidth = streamWidth;
  for (let i = transforms.length - 1; i >= 0; i--) {
    const transform = transforms[i];
    if (transform.type === PREDICTOR_TRANSFORM) {
      applyPredictor(out, outWidth, height, transform);
    } else if (transform.type === COLOR_TRANSFORM) {
      applyColourTransform(out, outWidth, height, transform);
    } else if (transform.type === SUBTRACT_GREEN) {
      applySubtractGreen(out);
    } else {
      const expanded = applyColourIndexing(out, outWidth, width, height, transform);
      if (!expanded) return null;
      out = expanded;
      outWidth = width;
    }
  }

  return { pixels: out, width: outWidth, height };
}

/**
 * Decode a VP8L chunk body (everything after the four-character code and its
 * length) into ARGB.
 */
export function decodeVp8l(
  body: Uint8Array, limits: { maxPixels: number },
): WebpRaster | null {
  if (body.length < 5 || body[0] !== 0x2f) return null;
  const reader = new LosslessBitReader(body, 1);
  const width = reader.read(14) + 1;
  const height = reader.read(14) + 1;
  reader.read(1); // alpha_is_used — the caller composites, so it is not needed
  const version = reader.read(3);
  if (!reader.ok || version !== 0) return null;
  if (width * height > limits.maxPixels) return null;

  const decoded = decodeImageStream(reader, width, height,
    { topLevel: true, maxPixels: limits.maxPixels });
  if (!decoded) return null;

  return { width, height, pixels: argbToRgb(decoded.pixels, width * height), argb: decoded.pixels };
}

/**
 * Flatten ARGB onto white.
 *
 * White rather than black because a transparent WebP is almost always a logo
 * or a cut-out on a light page, and compositing it onto black would invent a
 * huge flat dark region for the overlay detector to find.
 */
export function argbToRgb(argb: Uint32Array, count: number): Uint8Array {
  const out = new Uint8Array(count * 3);
  for (let i = 0; i < count; i++) {
    const value = argb[i];
    const alpha = value >>> 24;
    const red = (value >> 16) & 0xff;
    const green = (value >> 8) & 0xff;
    const blue = value & 0xff;
    if (alpha === 255) {
      out[i * 3] = red;
      out[i * 3 + 1] = green;
      out[i * 3 + 2] = blue;
    } else {
      const inverse = 255 - alpha;
      out[i * 3] = (red * alpha + 255 * inverse) / 255;
      out[i * 3 + 1] = (green * alpha + 255 * inverse) / 255;
      out[i * 3 + 2] = (blue * alpha + 255 * inverse) / 255;
    }
  }
  return out;
}
