import { createClient } from 'npm:@supabase/supabase-js@2.55.0';
import { createCorsHeaders } from '../_shared/auth.ts';
import { verifyFinancePortalSession } from '../_shared/requestSecurity.ts';
const ENABLED=Deno.env.get('FINANCE_SOLICITOR_COLLABORATION')==='true';
const json=(body:unknown,status:number,headers:Record<string,string>)=>new Response(JSON.stringify(body),{status,headers:{...headers,'Content-Type':'application/json'}});
const telemetryHash=async(value:string|null)=>value?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(v=>v.toString(16).padStart(2,'0')).join(''):null;
const safeDocument=(e:any)=>({id:e.record.id,title:e.record.title,category:e.record.category,current_version:e.version?{id:e.version.id,version_number:e.version.version_number,filename:e.version.original_filename,mime_type:e.version.detected_mime_type,byte_size:e.version.byte_size,sha256:e.version.sha256,reviewed_at:e.version.reviewed_at}:null});
Deno.serve(async req=>{const cors=createCorsHeaders(req.headers.get('origin'));if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({success:false,error:'Method not allowed'},405,cors);if(!ENABLED)return json({success:false,error:'Not found'},404,cors);
 try{const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const body=await req.json().catch(()=>({}));const token=req.headers.get('x-finance-session-token')||body.finance_session_token||body.session_token;const auth=await verifyFinancePortalSession(db,token);if(!auth.ok||!auth.actorId)return json({success:false,error:'Authentication required'},401,cors);const actorId=auth.actorId,fileId=String(body.purchase_file_id||'');if(!fileId)return json({success:false,error:'purchase_file_id is required'},400,cors);
 const {data:file}=await db.from('purchase_files').select('id,assigned_finance_user_id').eq('id',fileId).eq('assigned_finance_user_id',actorId).is('archived_at',null).maybeSingle();if(!file)return json({success:false,error:'Not found'},404,cors);const {data:projection}=await db.from('finance_case_read_model').select('case_id,client_id,legal_matter_id,purchase_file_id,legal_status,contractual_settlement_date,matter_reference,practice_name,practice_email,practice_phone,solicitor_user_id,solicitor_name,solicitor_email,finance_clause_date,finance_clause_state,legal_source_version,legal_updated_at,link_health,updated_at').eq('purchase_file_id',fileId).maybeSingle();if(!projection)return json({success:false,error:'Transaction case link required',code:'CASE_LINK_REQUIRED'},409,cors);const operation=String(body.operation||'get_coordination');
 if(operation==='get_coordination'){const [{data:runway,error:runwayError},{data:documents,error:documentError},{data:conversations,error:conversationError}]=await Promise.all([db.rpc('get_case_runway',{_case_id:projection.case_id,_audience:'finance'}),db.rpc('list_accessible_documents',{_case_id:projection.case_id,_audience:'finance',_grantee_id:actorId}),db.rpc('get_participant_conversations',{_participant_type:'finance_user',_participant_id:actorId,_case_id:projection.case_id})]);if(runwayError||documentError||conversationError)throw runwayError||documentError||conversationError;const sharedTasks=(runway?.tasks||[]).filter((t:any)=>t.visibility==='shared').map((t:any)=>({id:t.id,label:t.label,description:t.description,status:t.status,due_at:t.due_at,completed_at:t.completed_at,row_version:t.row_version}));const milestones=(runway?.milestones||[]).filter((m:any)=>m.visibility==='shared').map((m:any)=>({id:m.id,milestone_type:m.milestone_type,title:m.title,due_at:m.due_at,status:m.status,authority:m.authority,row_version:m.row_version}));const sharedDocuments=(documents||[]).filter((e:any)=>e.version?.malware_scan_status==='clean'&&['reviewed','retained','legal_hold'].includes(e.version?.lifecycle_status)).map(safeDocument);const threads=[];for(const entry of (conversations||[]).filter((e:any)=>e.conversation?.scope==='finance_solicitor')){const {data:messages}=await db.rpc('get_conversation_messages',{_conversation_id:entry.conversation.id,_participant_type:'finance_user',_participant_id:actorId,_limit:100,_before:null});threads.push({id:entry.conversation.id,subject:entry.conversation.subject,unread_count:entry.unread_count,messages:(messages||[]).map((m:any)=>({id:m.id,sender_type:m.sender_type,sender_name:m.sender_name,body:m.body,created_at:m.created_at}))});}return json({success:true,coordination:{case:projection,milestones,shared_tasks:sharedTasks,shared_documents:sharedDocuments,conversations:threads,provenance:{legal:{source:'legal_matter_projection',version:projection.legal_source_version,updated_at:projection.legal_updated_at},finance:{source:'purchase_file',updated_at:projection.updated_at}}}},200,cors);}
 if(operation==='reply'){const conversationId=String(body.conversation_id||''),message=String(body.message||'').trim();const {data:conversation}=await db.from('conversations').select('id').eq('id',conversationId).eq('case_id',projection.case_id).eq('scope','finance_solicitor').maybeSingle();if(!conversation||!message)return json({success:false,error:'Conversation or message not found'},404,cors);const {data,error}=await db.rpc('post_conversation_message',{_conversation_id:conversationId,_actor_type:'finance_user',_actor_id:actorId,_body:message,_idempotency_key:String(body.idempotency_key||`finance-legal:${actorId}:${crypto.randomUUID()}`),_sender_name:'Finance',_reply_to:body.reply_to_message_id||null});if(error)return json({success:false,error:error.message},/ACCESS_DENIED/.test(error.message||'')?403:400,cors);return json({success:true,message:data},200,cors);}
 if(operation==='download_document'){const recordId=String(body.document_record_id||''),versionId=String(body.document_version_id||'');const {data:authorized,error}=await db.rpc('authorize_document_download',{_document_record_id:recordId,_document_version_id:versionId,_audience:'finance',_grantee_id:actorId});if(error)throw error;if(!authorized||authorized.record?.case_id!==projection.case_id)return json({success:false,error:'Not found'},404,cors);const version=authorized.version;const {data:signed,error:signError}=await db.storage.from(version.storage_bucket).createSignedUrl(version.storage_path,300,{download:version.original_filename});if(signError)throw signError;const correlationId=crypto.randomUUID();await db.rpc('record_document_download',{_document_record_id:recordId,_document_version_id:version.id,_actor_type:'finance_user',_actor_id:actorId,_audience:'finance',_ip_hash:await telemetryHash(req.headers.get('cf-connecting-ip')),_user_agent_hash:await telemetryHash(req.headers.get('user-agent')),_correlation_id:correlationId});return json({success:true,url:signed?.signedUrl||null,filename:version.original_filename,version_id:version.id,sha256:version.sha256},200,cors);}
 return json({success:false,error:'Unknown operation'},400,cors);}catch(error){console.error('[finance-legal-coordination]',error instanceof Error?error.message:'request_failed');return json({success:false,error:'Unable to load legal coordination'},500,cors);}});
