import { z } from 'npm:zod@3.25.76';
export const EXPENSE_KEYS=['childcare','child_maintenance','public_school_costs','private_school_costs','higher_education_vocational_training','groceries','electricity_gas','council_rates','water_sewer','body_corporate','home_repairs','furnishings_electrical','building_insurance','contents_insurance','health_insurance','income_protection','life_insurance','vehicle_insurance','investment_rates_utilities_body_corporate','investment_repairs_maintenance','investment_insurance','secondary_rates_utilities_body_corporate','secondary_repairs_maintenance','secondary_insurance','medical_health','natural_therapies','rent','board','clothing_footwear','cosmetics_haircare','dry_cleaning','pets','alcohol_tobacco','cinema_concerts_memberships','dining_out','gym_sports','travel_holidays','gifts_miscellaneous','gambling','home_mobile_phone','internet_pay_tv_streaming','petrol','registration','vehicle_maintenance','public_transport','taxi_ride_sharing','tolls_parking','regular_donations','voluntary_superannuation','other_regular_expense'] as const;
const t=z.string(), d=z.union([z.literal(''),z.string().date(),z.null()]), m=z.preprocess(v=>v==null||v===''?0:v,z.coerce.number().finite().nonnegative()), p=z.preprocess(v=>typeof v==='string'?v.replace('%',''):v,z.coerce.number().min(0).max(100));
const applicant=z.object({applicantNumber:z.union([z.literal(1),z.literal(2)]),title:t,firstName:t,middleName:t,surname:t,dateOfBirth:d,gender:t,maritalStatus:t,residencyStatus:t,numberOfDependants:z.number().int().nonnegative().nullable(),mobile:t,email:z.union([z.literal(''),z.string().email()]),relationship:z.enum(['primary_client','secondary_contact'])}).strict();
const employment=z.object({applicantNumber:z.union([z.literal(1),z.literal(2)]),employmentType:t,employerOrBusiness:t,roleOrPosition:t,employerAddress:t,startDate:d,baseSalary:m,bonus:m,commission:m,overtime:m,otherTaxableIncome:m}).strict();
const totals=z.object({totalAssetsCents:z.number().int(),totalAssetLinkedDebtCents:z.number().int(),totalOtherLiabilitiesCents:z.number().int(),totalDebtCents:z.number().int(),netPositionCents:z.number().int(),applicant1AnnualIncomeCents:z.number().int(),applicant2AnnualIncomeCents:z.number().int(),totalMonthlyLivingExpensesCents:z.number().int(),clientFormOutputLivingExpensesCents:z.number().int()}).strict();
export const payloadSchema=z.object({templateVersion:z.string().min(1),branding:z.object({organisationName:t,tradingName:t,tagline:t,primaryColour:z.string().regex(/^#[\da-f]{6}$/i),accentColour:z.string().regex(/^#[\da-f]{6}$/i),website:t,email:z.union([z.literal(''),z.string().email()]),phone:t,businessAddress:t,documentTitle:t,confidentialityLabel:t,preparedBy:t,logoReference:t,version:t,sourceWhiteLabelSettingId:z.string().uuid().nullable().optional()}).strict(),
 applicants:z.array(applicant).min(1).max(2),addresses:z.array(z.object({applicantNumber:z.union([z.literal(1),z.literal(2)]),addressType:z.enum(['current','previous']),address:t,livingSituation:t,movedInDate:d,displayOrder:z.union([z.literal(0),z.literal(1)])}).strict()).max(4),employment:z.array(employment).min(1).max(2),
 assets:z.array(z.object({displayOrder:z.number().int().min(0).max(9),assetType:t,descriptionOrAddress:t,owner:t,currentValue:m,rentalOrOtherIncome:m,financialInstitution:t,loanBalance:m,monthlyRepayment:m,interestRate:p,maturityDate:d}).strict()).length(10),
 liabilities:z.array(z.object({displayOrder:z.number().int().min(0).max(7),liabilityType:t,lender:t,accountOrDescription:t,owner:t,limitOrOriginalAmount:m,currentBalance:m,monthlyRepayment:m,interestRate:p,remainingTerm:t,notes:t}).strict()).length(8),
 expenses:z.array(z.object({expenseKey:t,category:t,itemLabel:t,displayOrder:z.number().int().min(0).max(49),monthlyAmount:m,notes:t}).strict()).length(50),calculatedTotals:totals.optional(),syncToGhl:z.boolean().optional()}).strict().superRefine((v,c)=>{
 const a1=v.applicants.find(a=>a.applicantNumber===1); if(!a1?.firstName.trim())c.addIssue({code:'custom',path:['applicants'],message:'Primary first name is required'});if(!a1?.surname.trim())c.addIssue({code:'custom',path:['applicants'],message:'Primary surname is required'});
 const a2=v.applicants.find(a=>a.applicantNumber===2), supplied=a2&&Object.entries(a2).some(([k,x])=>!['applicantNumber','relationship'].includes(k)&&x!==''&&x!==null&&x!==0);if(supplied&&(!a2!.firstName.trim()||!a2!.surname.trim()))c.addIssue({code:'custom',path:['applicants'],message:'Applicant 2 first name and surname are required when details are supplied'});
 for(const [name,rows,count] of [['assets',v.assets,10],['liabilities',v.liabilities,8],['expenses',v.expenses,50]] as const)if(rows.some((r,i)=>r.displayOrder!==i)||new Set(rows.map(r=>r.displayOrder)).size!==count)c.addIssue({code:'custom',path:[name],message:'Rows must be in workbook order'});
 v.expenses.forEach((e,i)=>{if(e.expenseKey!==EXPENSE_KEYS[i])c.addIssue({code:'custom',path:['expenses',i,'expenseKey'],message:'Unknown or out-of-order expense key'});});
});
export const requestSchema=z.object({payload:payloadSchema}).strict();
