/**
 * Which engine an investment report is generated by — one rule, mirroring the
 * server.
 *
 * `generate-investment-report` decides this and nothing else may:
 *
 *     const rawTier = propertyDetails?.reportTier || 'compass';
 *     const isCompassTier = rawTier === 'compass' || rawTier === 'compass-40';
 *     const generationEngine = isCompassTier || requestedEngine === 'compass-40'
 *       ? 'compass-40' : 'legacy';
 *
 * The **tier is the authoritative boundary**: it is the data-minimisation
 * decision (a Compass report deliberately carries no purchase price, yield,
 * LVR, loan or ten-year cash flow — the Financial Analysis Report does), so an
 * engine preference must never be able to pull financial content into a
 * non-financial report, nor strip it out of a financial one. A caller
 * preference is read only where the tier leaves the question open.
 *
 * This module exists so a surface can *say* which engine will run without
 * re-deriving the rule. It mirrors the server rather than replacing it —
 * `generationEngineTruth.spec.ts` reads the edge function's own source and
 * fails when the two drift, the same guard `llmUsageBinding.pure.ts` carries
 * against the router.
 */

export type GenerationEngine = 'legacy' | 'compass-40';

/**
 * The tiers for which the engine is not a question. Spelled exactly as the
 * server spells them — `report_tier` is stored verbatim from the caller, and
 * the other production values (`snapshot`, `briefing`, `strategic`,
 * `financial`) are deliberately absent.
 */
export const COMPASS_TIERS: readonly string[] = ['compass', 'compass-40'];

/**
 * The server's `rawTier`: `propertyDetails?.reportTier || 'compass'`. An absent
 * tier is Compass, which is why the page that sends none always gets this
 * engine.
 *
 * Deliberately neither trimmed nor lower-cased. The server compares the raw
 * value with `===`, so ` compass ` resolves to the legacy engine there; a
 * defensive normalisation here would make this module kinder than the rule it
 * exists to report, which is the one way it could lie.
 */
const rawTier = (reportTier?: string | null): string =>
  (typeof reportTier === 'string' && reportTier ? reportTier : 'compass');

/** True when the report's tier settles the engine on its own — no preference can change it. */
export function engineIsFixedByTier(reportTier?: string | null): boolean {
  return COMPASS_TIERS.includes(rawTier(reportTier));
}

/**
 * The engine that will run for this report.
 *
 * `storedEngine` stands in for the server's `requestedEngine`: on a
 * continuation the server restores it from the row when the caller sends none,
 * so the row's value is what a preference-free call resolves against.
 */
export function resolveGenerationEngine(input: {
  reportTier?: string | null;
  storedEngine?: string | null;
}): GenerationEngine {
  if (engineIsFixedByTier(input.reportTier)) return 'compass-40';
  return input.storedEngine === 'compass-40' ? 'compass-40' : 'legacy';
}

/**
 * What each engine is called on screen.
 *
 * Compass is **Primary**, not "Compass-40 (Trimmed Legacy)" and not "Legacy
 * Compass — Stable": it is the engine every Investment Analysis is generated
 * by, and the only one the canonical section registry, the editorial
 * post-processor and the QA validator run under.
 */
export const ENGINE_LABEL: Record<GenerationEngine, string> = {
  'compass-40': 'Compass — Primary',
  legacy: 'Legacy Compass',
};
