/**
 * The catalogue's fifty designs, as the standard documents draw them —
 * GENERATED, do not hand-edit.
 *
 * Emitted by `scripts/template-library/investmentCompass/designCatalogue.ts`
 * from the approved families (`families.generated.ts`), the measured type
 * table (`family.ts`) and the manifest resolvers (`resolvers.ts`) — the same
 * three sources every master is built from, so a design cannot mean one thing
 * on a master and another on a standard document.
 *
 * `templateDesignCatalogue.spec.ts` derives these rows again and fails if this
 * file disagrees. Change a design in Claude Design, bring it through
 * `npm run templates:compass:generate`, then run
 * `npm run templates:design:generate` and read the diff.
 *
 * Pure data, no imports: it is read by edge functions and by the browser.
 */

export interface CatalogueVariantDesign {
  /** The approved catalogue code, e.g. `pb-01`. */
  readonly code: string;
  /** The approved design name, e.g. `Chancery`. */
  readonly name: string;
  readonly familyKey: string;
  readonly familyCode: string;
  readonly familyName: string;
  /** The variant axis, e.g. `A · reference`. */
  readonly axis: string;
  /** The ground the design was drawn on. The colourway decides the one printed. */
  readonly ground: 'light' | 'dark';
  readonly density: 'compact' | 'balanced' | 'spacious';
  /** How the cover is grounded, from the manifest's `cover_overlay`. */
  readonly cover: {
    readonly ground: 'field' | 'band' | 'paper';
    readonly frame: boolean;
    readonly rail: boolean;
  };
  /** A vertical rail down the binding edge of every page. */
  readonly rail: boolean;
  /** How a section announces itself, from `section_header_style`. */
  readonly sectionKind: 'eyebrow' | 'numeral' | 'bare' | 'band' | 'decimal' | 'standfirst';
  /** A drop capital opens the first paragraph of a section. */
  readonly dropCap: boolean;
  /** How a data table is ruled, from `table_style`. */
  readonly table: {
    readonly headerStyle: 'fill' | 'rule';
    readonly rowRule: boolean;
    readonly outerBorder: boolean;
    readonly gridLines: boolean;
    readonly stripe: boolean;
    readonly tight: boolean;
    readonly doubleRuleTotals: boolean;
  };
  /** Corner radius in points. Non-zero on one family only. */
  readonly radius: number;
  /** The four type roles, as the family's pages set them. */
  readonly fonts: {
    readonly display: string; readonly displayGeneric: string;
    readonly heading: string; readonly headingGeneric: string;
    readonly body: string; readonly bodyGeneric: string;
    readonly mono: string; readonly monoGeneric: string;
  };
  /** The measured cover title size at this design's density, in points. */
  readonly coverTitlePt: number;
  /** The family's default colourway id. */
  readonly defaultColourway: string;
}

export const CATALOGUE_VARIANT_DESIGNS: readonly CatalogueVariantDesign[] = [
  {
    code: 'pb-01',
    name: 'Chancery',
    familyKey: 'private_banking',
    familyCode: 'pb',
    familyName: 'Private Banking',
    axis: 'A · reference',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'eyebrow',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Cinzel',
      displayGeneric: 'serif',
      heading: 'Playfair Display',
      headingGeneric: 'serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 41,
    defaultColourway: 'pb-gold-on-obsidian',
  },
  {
    code: 'pb-02',
    name: 'Chancery Compact',
    familyKey: 'private_banking',
    familyCode: 'pb',
    familyName: 'Private Banking',
    axis: 'B · condensed',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'eyebrow',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: true,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Cinzel',
      displayGeneric: 'serif',
      heading: 'Playfair Display',
      headingGeneric: 'serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 33.5,
    defaultColourway: 'pb-gold-on-obsidian',
  },
  {
    code: 'pb-03',
    name: 'Sovereign Folio',
    familyKey: 'private_banking',
    familyCode: 'pb',
    familyName: 'Private Banking',
    axis: 'C · expansive',
    ground: 'light',
    density: 'spacious',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Cinzel',
      displayGeneric: 'serif',
      heading: 'Playfair Display',
      headingGeneric: 'serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 48.5,
    defaultColourway: 'pb-gold-on-obsidian',
  },
  {
    code: 'pb-04',
    name: 'Bullion Rail',
    familyKey: 'private_banking',
    familyCode: 'pb',
    familyName: 'Private Banking',
    axis: 'D · architecture',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: true,
    },
    rail: true,
    sectionKind: 'bare',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Cinzel',
      displayGeneric: 'serif',
      heading: 'Playfair Display',
      headingGeneric: 'serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 41,
    defaultColourway: 'pb-gold-on-obsidian',
  },
  {
    code: 'pb-05',
    name: 'Discretion Ledger',
    familyKey: 'private_banking',
    familyCode: 'pb',
    familyName: 'Private Banking',
    axis: 'E · presentation',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'eyebrow',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: true,
    },
    radius: 0,
    fonts: {
      display: 'Cinzel',
      displayGeneric: 'serif',
      heading: 'Playfair Display',
      headingGeneric: 'serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 41,
    defaultColourway: 'pb-gold-on-obsidian',
  },
  {
    code: 'ir-01',
    name: 'Exhibit',
    familyKey: 'institutional_research',
    familyCode: 'ir',
    familyName: 'Institutional Research',
    axis: 'A · reference',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Noto Serif',
      displayGeneric: 'serif',
      heading: 'Noto Serif',
      headingGeneric: 'serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 14,
    defaultColourway: 'ir-research-blue',
  },
  {
    code: 'ir-02',
    name: 'Exhibit Dense',
    familyKey: 'institutional_research',
    familyCode: 'ir',
    familyName: 'Institutional Research',
    axis: 'B · condensed',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: true,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Noto Serif',
      displayGeneric: 'serif',
      heading: 'Noto Serif',
      headingGeneric: 'serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 11.5,
    defaultColourway: 'ir-research-blue',
  },
  {
    code: 'ir-03',
    name: 'Coverage Note',
    familyKey: 'institutional_research',
    familyCode: 'ir',
    familyName: 'Institutional Research',
    axis: 'C · expansive',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'bare',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Noto Serif',
      displayGeneric: 'serif',
      heading: 'Noto Serif',
      headingGeneric: 'serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 11.5,
    defaultColourway: 'ir-research-blue',
  },
  {
    code: 'ir-04',
    name: 'Analyst Folio',
    familyKey: 'institutional_research',
    familyCode: 'ir',
    familyName: 'Institutional Research',
    axis: 'D · architecture',
    ground: 'light',
    density: 'spacious',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Noto Serif',
      displayGeneric: 'serif',
      heading: 'Noto Serif',
      headingGeneric: 'serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 16.5,
    defaultColourway: 'ir-research-blue',
  },
  {
    code: 'ir-05',
    name: 'Committee Brief',
    familyKey: 'institutional_research',
    familyCode: 'ir',
    familyName: 'Institutional Research',
    axis: 'E · presentation',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Noto Serif',
      displayGeneric: 'serif',
      heading: 'Noto Serif',
      headingGeneric: 'serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 14,
    defaultColourway: 'ir-research-blue',
  },
  {
    code: 'le-01',
    name: 'Atelier',
    familyKey: 'luxury_editorial',
    familyCode: 'le',
    familyName: 'Luxury Editorial',
    axis: 'A · reference',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'standfirst',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Noto Serif',
      displayGeneric: 'serif',
      heading: 'Noto Serif',
      headingGeneric: 'serif',
      body: 'Noto Serif',
      bodyGeneric: 'serif',
      mono: 'Noto Serif',
      monoGeneric: 'serif',
    },
    coverTitlePt: 40,
    defaultColourway: 'le-ivory-and-gold',
  },
  {
    code: 'le-02',
    name: 'Atelier Plate',
    familyKey: 'luxury_editorial',
    familyCode: 'le',
    familyName: 'Luxury Editorial',
    axis: 'B · condensed',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'standfirst',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Noto Serif',
      displayGeneric: 'serif',
      heading: 'Noto Serif',
      headingGeneric: 'serif',
      body: 'Noto Serif',
      bodyGeneric: 'serif',
      mono: 'Noto Serif',
      monoGeneric: 'serif',
    },
    coverTitlePt: 40,
    defaultColourway: 'le-ivory-and-gold',
  },
  {
    code: 'le-03',
    name: 'Grand Folio',
    familyKey: 'luxury_editorial',
    familyCode: 'le',
    familyName: 'Luxury Editorial',
    axis: 'C · expansive',
    ground: 'light',
    density: 'spacious',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Noto Serif',
      displayGeneric: 'serif',
      heading: 'Noto Serif',
      headingGeneric: 'serif',
      body: 'Noto Serif',
      bodyGeneric: 'serif',
      mono: 'Noto Serif',
      monoGeneric: 'serif',
    },
    coverTitlePt: 47.25,
    defaultColourway: 'le-ivory-and-gold',
  },
  {
    code: 'le-04',
    name: 'Frontispiece',
    familyKey: 'luxury_editorial',
    familyCode: 'le',
    familyName: 'Luxury Editorial',
    axis: 'D · architecture',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'paper',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'standfirst',
    dropCap: true,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Noto Serif',
      displayGeneric: 'serif',
      heading: 'Noto Serif',
      headingGeneric: 'serif',
      body: 'Noto Serif',
      bodyGeneric: 'serif',
      mono: 'Noto Serif',
      monoGeneric: 'serif',
    },
    coverTitlePt: 40,
    defaultColourway: 'le-ivory-and-gold',
  },
  {
    code: 'le-05',
    name: 'Monograph',
    familyKey: 'luxury_editorial',
    familyCode: 'le',
    familyName: 'Luxury Editorial',
    axis: 'E · presentation',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'paper',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'standfirst',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: true,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Noto Serif',
      displayGeneric: 'serif',
      heading: 'Noto Serif',
      headingGeneric: 'serif',
      body: 'Noto Serif',
      bodyGeneric: 'serif',
      mono: 'Noto Serif',
      monoGeneric: 'serif',
    },
    coverTitlePt: 40,
    defaultColourway: 'le-ivory-and-gold',
  },
  {
    code: 'mf-01',
    name: 'Signal',
    familyKey: 'modern_fintech',
    familyCode: 'mf',
    familyName: 'Modern Fintech',
    axis: 'A · reference',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'eyebrow',
    dropCap: false,
    table: {
      headerStyle: 'fill',
      rowRule: false,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 4,
    fonts: {
      display: 'Inter',
      displayGeneric: 'sans-serif',
      heading: 'Inter',
      headingGeneric: 'sans-serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 37,
    defaultColourway: 'mf-violet-signal',
  },
  {
    code: 'mf-02',
    name: 'Signal Compact',
    familyKey: 'modern_fintech',
    familyCode: 'mf',
    familyName: 'Modern Fintech',
    axis: 'B · condensed',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'eyebrow',
    dropCap: false,
    table: {
      headerStyle: 'fill',
      rowRule: false,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 4,
    fonts: {
      display: 'Inter',
      displayGeneric: 'sans-serif',
      heading: 'Inter',
      headingGeneric: 'sans-serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 30.25,
    defaultColourway: 'mf-violet-signal',
  },
  {
    code: 'mf-03',
    name: 'Console',
    familyKey: 'modern_fintech',
    familyCode: 'mf',
    familyName: 'Modern Fintech',
    axis: 'C · expansive',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'eyebrow',
    dropCap: false,
    table: {
      headerStyle: 'fill',
      rowRule: false,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 4,
    fonts: {
      display: 'Inter',
      displayGeneric: 'sans-serif',
      heading: 'Inter',
      headingGeneric: 'sans-serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 37,
    defaultColourway: 'mf-violet-signal',
  },
  {
    code: 'mf-04',
    name: 'Ribbon',
    familyKey: 'modern_fintech',
    familyCode: 'mf',
    familyName: 'Modern Fintech',
    axis: 'D · architecture',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'band',
    dropCap: false,
    table: {
      headerStyle: 'fill',
      rowRule: false,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 4,
    fonts: {
      display: 'Inter',
      displayGeneric: 'sans-serif',
      heading: 'Inter',
      headingGeneric: 'sans-serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 37,
    defaultColourway: 'mf-violet-signal',
  },
  {
    code: 'mf-05',
    name: 'Pulse',
    familyKey: 'modern_fintech',
    familyCode: 'mf',
    familyName: 'Modern Fintech',
    axis: 'E · presentation',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'eyebrow',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 4,
    fonts: {
      display: 'Inter',
      displayGeneric: 'sans-serif',
      heading: 'Inter',
      headingGeneric: 'sans-serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 37,
    defaultColourway: 'mf-violet-signal',
  },
  {
    code: 'ap-01',
    name: 'Drawing Set',
    familyKey: 'architectural_property',
    familyCode: 'ap',
    familyName: 'Architectural Property',
    axis: 'A · reference',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'paper',
      frame: true,
      rail: false,
    },
    rail: true,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Lato',
      displayGeneric: 'sans-serif',
      heading: 'Lato',
      headingGeneric: 'sans-serif',
      body: 'Lato',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 36,
    defaultColourway: 'ap-concrete',
  },
  {
    code: 'ap-02',
    name: 'Schedule',
    familyKey: 'architectural_property',
    familyCode: 'ap',
    familyName: 'Architectural Property',
    axis: 'B · condensed',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'paper',
      frame: true,
      rail: false,
    },
    rail: true,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: true,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Lato',
      displayGeneric: 'sans-serif',
      heading: 'Lato',
      headingGeneric: 'sans-serif',
      body: 'Lato',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 29.5,
    defaultColourway: 'ap-concrete',
  },
  {
    code: 'ap-03',
    name: 'Elevation',
    familyKey: 'architectural_property',
    familyCode: 'ap',
    familyName: 'Architectural Property',
    axis: 'C · expansive',
    ground: 'light',
    density: 'spacious',
    cover: {
      ground: 'paper',
      frame: true,
      rail: false,
    },
    rail: true,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Lato',
      displayGeneric: 'sans-serif',
      heading: 'Lato',
      headingGeneric: 'sans-serif',
      body: 'Lato',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 42.5,
    defaultColourway: 'ap-concrete',
  },
  {
    code: 'ap-04',
    name: 'Site Plan',
    familyKey: 'architectural_property',
    familyCode: 'ap',
    familyName: 'Architectural Property',
    axis: 'D · architecture',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'paper',
      frame: true,
      rail: false,
    },
    rail: true,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Lato',
      displayGeneric: 'sans-serif',
      heading: 'Lato',
      headingGeneric: 'sans-serif',
      body: 'Lato',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 36,
    defaultColourway: 'ap-concrete',
  },
  {
    code: 'ap-05',
    name: 'Datum',
    familyKey: 'architectural_property',
    familyCode: 'ap',
    familyName: 'Architectural Property',
    axis: 'E · presentation',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'paper',
      frame: true,
      rail: false,
    },
    rail: true,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Lato',
      displayGeneric: 'sans-serif',
      heading: 'Lato',
      headingGeneric: 'sans-serif',
      body: 'Lato',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 36,
    defaultColourway: 'ap-concrete',
  },
  {
    code: 'sm-01',
    name: 'Grid',
    familyKey: 'swiss_minimal',
    familyCode: 'sm',
    familyName: 'Swiss Minimal',
    axis: 'A · reference',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'paper',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: true,
      gridLines: true,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Inter',
      displayGeneric: 'sans-serif',
      heading: 'Inter',
      headingGeneric: 'sans-serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'Inter',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 52,
    defaultColourway: 'sm-red-accent',
  },
  {
    code: 'sm-02',
    name: 'Grid Tight',
    familyKey: 'swiss_minimal',
    familyCode: 'sm',
    familyName: 'Swiss Minimal',
    axis: 'B · condensed',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'paper',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: true,
      gridLines: true,
      stripe: false,
      tight: true,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Inter',
      displayGeneric: 'sans-serif',
      heading: 'Inter',
      headingGeneric: 'sans-serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'Inter',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 42.75,
    defaultColourway: 'sm-red-accent',
  },
  {
    code: 'sm-03',
    name: 'Objective',
    familyKey: 'swiss_minimal',
    familyCode: 'sm',
    familyName: 'Swiss Minimal',
    axis: 'C · expansive',
    ground: 'light',
    density: 'spacious',
    cover: {
      ground: 'paper',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: true,
      gridLines: true,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Inter',
      displayGeneric: 'sans-serif',
      heading: 'Inter',
      headingGeneric: 'sans-serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'Inter',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 61.25,
    defaultColourway: 'sm-red-accent',
  },
  {
    code: 'sm-04',
    name: 'Raster',
    familyKey: 'swiss_minimal',
    familyCode: 'sm',
    familyName: 'Swiss Minimal',
    axis: 'D · architecture',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'paper',
      frame: true,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: true,
      gridLines: true,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Inter',
      displayGeneric: 'sans-serif',
      heading: 'Inter',
      headingGeneric: 'sans-serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'Inter',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 52,
    defaultColourway: 'sm-red-accent',
  },
  {
    code: 'sm-05',
    name: 'Hairline',
    familyKey: 'swiss_minimal',
    familyCode: 'sm',
    familyName: 'Swiss Minimal',
    axis: 'E · presentation',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'paper',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Inter',
      displayGeneric: 'sans-serif',
      heading: 'Inter',
      headingGeneric: 'sans-serif',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'Inter',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 52,
    defaultColourway: 'sm-red-accent',
  },
  {
    code: 'ca-01',
    name: 'Board Pack',
    familyKey: 'corporate_advisory',
    familyCode: 'ca',
    familyName: 'Corporate Advisory',
    axis: 'A · reference',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'decimal',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Lato',
      displayGeneric: 'sans-serif',
      heading: 'Lato',
      headingGeneric: 'sans-serif',
      body: 'Noto Serif',
      bodyGeneric: 'serif',
      mono: 'Lato',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 27,
    defaultColourway: 'ca-slate-teal',
  },
  {
    code: 'ca-02',
    name: 'Board Pack Brief',
    familyKey: 'corporate_advisory',
    familyCode: 'ca',
    familyName: 'Corporate Advisory',
    axis: 'B · condensed',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'decimal',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: true,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Lato',
      displayGeneric: 'sans-serif',
      heading: 'Lato',
      headingGeneric: 'sans-serif',
      body: 'Noto Serif',
      bodyGeneric: 'serif',
      mono: 'Lato',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 22.25,
    defaultColourway: 'ca-slate-teal',
  },
  {
    code: 'ca-03',
    name: 'Engagement Note',
    familyKey: 'corporate_advisory',
    familyCode: 'ca',
    familyName: 'Corporate Advisory',
    axis: 'C · expansive',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'decimal',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Lato',
      displayGeneric: 'sans-serif',
      heading: 'Lato',
      headingGeneric: 'sans-serif',
      body: 'Noto Serif',
      bodyGeneric: 'serif',
      mono: 'Lato',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 27,
    defaultColourway: 'ca-slate-teal',
  },
  {
    code: 'ca-04',
    name: 'Committee Memo',
    familyKey: 'corporate_advisory',
    familyCode: 'ca',
    familyName: 'Corporate Advisory',
    axis: 'D · architecture',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'decimal',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Lato',
      displayGeneric: 'sans-serif',
      heading: 'Lato',
      headingGeneric: 'sans-serif',
      body: 'Noto Serif',
      bodyGeneric: 'serif',
      mono: 'Lato',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 22.25,
    defaultColourway: 'ca-slate-teal',
  },
  {
    code: 'ca-05',
    name: 'Advisory Letter',
    familyKey: 'corporate_advisory',
    familyCode: 'ca',
    familyName: 'Corporate Advisory',
    axis: 'E · presentation',
    ground: 'light',
    density: 'spacious',
    cover: {
      ground: 'paper',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'decimal',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Lato',
      displayGeneric: 'sans-serif',
      heading: 'Lato',
      headingGeneric: 'sans-serif',
      body: 'Noto Serif',
      bodyGeneric: 'serif',
      mono: 'Lato',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 31.75,
    defaultColourway: 'ca-slate-teal',
  },
  {
    code: 'wm-01',
    name: 'Statement',
    familyKey: 'wealth_management',
    familyCode: 'wm',
    familyName: 'Wealth Management',
    axis: 'A · reference',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'band',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Roboto',
      displayGeneric: 'sans-serif',
      heading: 'Roboto',
      headingGeneric: 'sans-serif',
      body: 'Roboto',
      bodyGeneric: 'sans-serif',
      mono: 'Roboto',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 34,
    defaultColourway: 'wm-obsidian-band',
  },
  {
    code: 'wm-02',
    name: 'Statement Compact',
    familyKey: 'wealth_management',
    familyCode: 'wm',
    familyName: 'Wealth Management',
    axis: 'B · condensed',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'band',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: true,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Roboto',
      displayGeneric: 'sans-serif',
      heading: 'Roboto',
      headingGeneric: 'sans-serif',
      body: 'Roboto',
      bodyGeneric: 'sans-serif',
      mono: 'Roboto',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 28,
    defaultColourway: 'wm-obsidian-band',
  },
  {
    code: 'wm-03',
    name: 'Portfolio Review',
    familyKey: 'wealth_management',
    familyCode: 'wm',
    familyName: 'Wealth Management',
    axis: 'C · expansive',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'band',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Roboto',
      displayGeneric: 'sans-serif',
      heading: 'Roboto',
      headingGeneric: 'sans-serif',
      body: 'Roboto',
      bodyGeneric: 'sans-serif',
      mono: 'Roboto',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 34,
    defaultColourway: 'wm-obsidian-band',
  },
  {
    code: 'wm-04',
    name: 'Client Pack',
    familyKey: 'wealth_management',
    familyCode: 'wm',
    familyName: 'Wealth Management',
    axis: 'D · architecture',
    ground: 'light',
    density: 'spacious',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'band',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Roboto',
      displayGeneric: 'sans-serif',
      heading: 'Roboto',
      headingGeneric: 'sans-serif',
      body: 'Roboto',
      bodyGeneric: 'sans-serif',
      mono: 'Roboto',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 40,
    defaultColourway: 'wm-obsidian-band',
  },
  {
    code: 'wm-05',
    name: 'Fiduciary',
    familyKey: 'wealth_management',
    familyCode: 'wm',
    familyName: 'Wealth Management',
    axis: 'E · presentation',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'band',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'Roboto',
      displayGeneric: 'sans-serif',
      heading: 'Roboto',
      headingGeneric: 'sans-serif',
      body: 'Roboto',
      bodyGeneric: 'sans-serif',
      mono: 'Roboto',
      monoGeneric: 'sans-serif',
    },
    coverTitlePt: 34,
    defaultColourway: 'wm-obsidian-band',
  },
  {
    code: 'da-01',
    name: 'Model',
    familyKey: 'data_analyst',
    familyCode: 'da',
    familyName: 'Data / Analyst',
    axis: 'A · reference',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: true,
      gridLines: true,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'IBM Plex Mono',
      displayGeneric: 'monospace',
      heading: 'IBM Plex Mono',
      headingGeneric: 'monospace',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 20.5,
    defaultColourway: 'da-paper-grid',
  },
  {
    code: 'da-02',
    name: 'Model Dense',
    familyKey: 'data_analyst',
    familyCode: 'da',
    familyName: 'Data / Analyst',
    axis: 'B · condensed',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: true,
      gridLines: true,
      stripe: false,
      tight: true,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'IBM Plex Mono',
      displayGeneric: 'monospace',
      heading: 'IBM Plex Mono',
      headingGeneric: 'monospace',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 20.5,
    defaultColourway: 'da-paper-grid',
  },
  {
    code: 'da-03',
    name: 'Worksheet',
    familyKey: 'data_analyst',
    familyCode: 'da',
    familyName: 'Data / Analyst',
    axis: 'C · expansive',
    ground: 'light',
    density: 'compact',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: true,
      gridLines: true,
      stripe: true,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'IBM Plex Mono',
      displayGeneric: 'monospace',
      heading: 'IBM Plex Mono',
      headingGeneric: 'monospace',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 20.5,
    defaultColourway: 'da-paper-grid',
  },
  {
    code: 'da-04',
    name: 'Dictionary',
    familyKey: 'data_analyst',
    familyCode: 'da',
    familyName: 'Data / Analyst',
    axis: 'D · architecture',
    ground: 'light',
    density: 'balanced',
    cover: {
      ground: 'band',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: true,
      gridLines: true,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'IBM Plex Mono',
      displayGeneric: 'monospace',
      heading: 'IBM Plex Mono',
      headingGeneric: 'monospace',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 25,
    defaultColourway: 'da-paper-grid',
  },
  {
    code: 'da-05',
    name: 'Terminal',
    familyKey: 'data_analyst',
    familyCode: 'da',
    familyName: 'Data / Analyst',
    axis: 'E · presentation',
    ground: 'dark',
    density: 'compact',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: false,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: true,
      gridLines: true,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'IBM Plex Mono',
      displayGeneric: 'monospace',
      heading: 'IBM Plex Mono',
      headingGeneric: 'monospace',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 20.5,
    defaultColourway: 'da-paper-grid',
  },
  {
    code: 'de-01',
    name: 'Obsidian',
    familyKey: 'dark_executive',
    familyCode: 'de',
    familyName: 'Dark Executive',
    axis: 'A · reference',
    ground: 'dark',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: true,
    sectionKind: 'bare',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'IBM Plex Mono',
      displayGeneric: 'monospace',
      heading: 'IBM Plex Mono',
      headingGeneric: 'monospace',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 33,
    defaultColourway: 'de-amber-obsidian',
  },
  {
    code: 'de-02',
    name: 'Obsidian Brief',
    familyKey: 'dark_executive',
    familyCode: 'de',
    familyName: 'Dark Executive',
    axis: 'B · condensed',
    ground: 'dark',
    density: 'compact',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: true,
    sectionKind: 'bare',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'IBM Plex Mono',
      displayGeneric: 'monospace',
      heading: 'IBM Plex Mono',
      headingGeneric: 'monospace',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 27,
    defaultColourway: 'de-amber-obsidian',
  },
  {
    code: 'de-03',
    name: 'Night Desk',
    familyKey: 'dark_executive',
    familyCode: 'de',
    familyName: 'Dark Executive',
    axis: 'C · expansive',
    ground: 'dark',
    density: 'spacious',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: true,
    sectionKind: 'bare',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'IBM Plex Mono',
      displayGeneric: 'monospace',
      heading: 'IBM Plex Mono',
      headingGeneric: 'monospace',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 39,
    defaultColourway: 'de-amber-obsidian',
  },
  {
    code: 'de-04',
    name: 'Signal Dark',
    familyKey: 'dark_executive',
    familyCode: 'de',
    familyName: 'Dark Executive',
    axis: 'D · architecture',
    ground: 'dark',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: false,
    },
    rail: true,
    sectionKind: 'bare',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: false,
      tight: true,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'IBM Plex Mono',
      displayGeneric: 'monospace',
      heading: 'IBM Plex Mono',
      headingGeneric: 'monospace',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 33,
    defaultColourway: 'de-amber-obsidian',
  },
  {
    code: 'de-05',
    name: 'Executive Rail',
    familyKey: 'dark_executive',
    familyCode: 'de',
    familyName: 'Dark Executive',
    axis: 'E · presentation',
    ground: 'dark',
    density: 'balanced',
    cover: {
      ground: 'field',
      frame: false,
      rail: true,
    },
    rail: true,
    sectionKind: 'numeral',
    dropCap: false,
    table: {
      headerStyle: 'rule',
      rowRule: true,
      outerBorder: false,
      gridLines: false,
      stripe: false,
      tight: false,
      doubleRuleTotals: false,
    },
    radius: 0,
    fonts: {
      display: 'IBM Plex Mono',
      displayGeneric: 'monospace',
      heading: 'IBM Plex Mono',
      headingGeneric: 'monospace',
      body: 'Inter',
      bodyGeneric: 'sans-serif',
      mono: 'IBM Plex Mono',
      monoGeneric: 'monospace',
    },
    coverTitlePt: 33,
    defaultColourway: 'de-amber-obsidian',
  },
];
