/**
 * S2 verification — the whole path, on frozen evidence, with nothing fetched.
 *
 * The repair was tested at the unit boundary. This exercises the JOURNEY the
 * defect actually lived in: acquire → narrative gate → persist → reload →
 * resume → score → render, twice over, plus the two cases that decide whether
 * it holds in the field.
 *
 * Everything here is deterministic and offline. The "acquisition" is a frozen
 * enrichment, so an uninterrupted run and a forced resume see the SAME
 * evidence and any difference between them is the code's, not the data's.
 * Persistence goes through `JSON.parse(JSON.stringify(...))`, which is what a
 * `jsonb` column does to an object: a key whose value is `undefined` is
 * dropped, which is exactly how the three readings disappeared.
 *
 * WHAT THE NUMBERS ARE. The market evidence and the location readings are a
 * FROZEN SYNTHETIC SET, not a measurement of any property. They exist to make
 * the methodology run end to end; the grade printed below is what the
 * methodology yields FOR THIS INPUT and is not a statement about any address.
 * No production row is read, written or regenerated by this script.
 *
 *   npx tsx scripts/reports/s2EndToEnd.mts
 */
import {
  ENRICHMENT_STAMP,
  assessEnrichmentReuse,
  nextAcquisitionAttempt,
  stampAcquisition,
  subjectKeyFor,
} from '../../supabase/functions/_shared/reports/location/locationEnrichmentReuse.pure.ts';
import { activateSafeGenerationInputs, DISOWNED_LOCATION_PATHS } from '../../supabase/functions/_shared/reports/contract/safeGenerationInputs.pure.ts';
import { verifiedLocationInputs } from '../../supabase/functions/_shared/reports/market/locationInputVerification.pure.ts';
import { scoreForProduction } from '../../supabase/functions/_shared/reports/market/scoringV2Production.pure.ts';

const SUBJECT = { address: '1 Frozen Street, Sampletown NSW 2000', postcode: '2000', state: 'NSW' };
const EVIDENCE_SUBJECT = {
  suburb: 'Sampletown', postcode: '2000', state: 'NSW',
  dwellingType: 'house' as const, resolvedFrom: 'coordinate' as const,
};
const NOW = new Date('2026-09-17T12:00:00.000Z');

/** A frozen point. Every field is what an open-data adapter writes. */
const point = (value: number, level: 'postcode' | 'state' | 'sa2', areaName: string) => ({
  value, level, areaName, dwellingType: 'house' as const, dwellingTypeMatched: true,
  provider: 'nsw_dcj_rent_sales' as const, asOf: '2026-03-31', sampleSize: 200,
  periodsAvailable: 4, method: 'calculated' as const,
  licensingStatus: 'open' as const, acquisition: 'open_public' as const, sourceNote: null,
});

/** FROZEN SYNTHETIC market evidence. Not a measurement of any property. */
const MARKET = {
  points: {
    medianPrice: { ...point(1_100_000, 'postcode', 'postcode 2000, NSW'), method: 'observed' as const },
    growth1Year: point(6.3, 'postcode', 'postcode 2000, NSW'),
    growth3YearCagr: point(4.4, 'postcode', 'postcode 2000, NSW'),
    growth5YearCagr: point(6.2, 'postcode', 'postcode 2000, NSW'),
    priceSeries: { ...point(1_100_000, 'postcode', 'postcode 2000, NSW'), method: 'observed' as const },
    salesCount: { ...point(162, 'postcode', 'postcode 2000, NSW'), method: 'observed' as const },
    benchmarkGrowth5YearCagr: point(7.6, 'state', 'NSW (all areas the publisher monitors)'),
    benchmarkMedianPrice: { ...point(980_000, 'state', 'NSW'), method: 'observed' as const },
    populationGrowth: { ...point(1.4, 'sa2', 'Sampletown - East'), provider: 'abs_erp' as const, asOf: '2025-06-30', sampleSize: null, periodsAvailable: 11 },
  },
  providersConsulted: ['nsw_dcj_rent_sales', 'abs_erp'] as const,
  providersUnavailable: [] as ReadonlyArray<{ provider: never; reason: string }>,
};

const PROPERTY = { price: 1_100_000, weeklyRent: 780, propertyType: 'House' };
const FINANCE = { lvr: 80, weeklyCashFlow: -540 };

/** FROZEN SYNTHETIC enrichment, in the exact shape the service builds. */
const acquire = (attempt: number, placesComplete = true) => stampAcquisition({
  coordinates: { lat: -33.7, lng: 150.9 },
  commute: { mode: 'driving', distanceKm: 31.2, durationMinutes: 42 },
  walkScore: placesComplete ? 61 : null,
  amenities: [{ category: 'Schools', count: 10, score: 100, nearest: 'A School', distance: 0.09 }],
  transport: { verdict: 'stops_nearby', stopsWithin1km: 117, radiusMetres: 1600, detailedStops: [] },
  schools: { nearestSchool: 'A School', distanceToSchool: 0.09, schoolsWithin3km: placesComplete ? 10 : null, topSchools: [] },
  healthcare: { nearestHospital: 'A Clinic', distanceToHospital: 0.15, facilitiesWithin5km: 10 },
  lifestyle: { shoppingCenters: 10, parks: 10, restaurants: 10, nearestShopping: 'A Shop', nearestPark: 'A Park' },
} as Record<string, unknown>, {
  subjectKey: subjectKeyFor(SUBJECT),
  acquiredAt: '2026-09-17T08:00:00.000Z',
  attempt,
  matchedAddress: 'Frozen Street, Sampletown, New South Wales, 2000, Australia',
  stages: {
    geocode: 'fetched',
    places: placesComplete ? 'complete' : 'partial',
    placesUnavailable: placesComplete ? [] : ['healthcare'],
    commute: 'measured',
    commuteProvider: 'osrm',
    amenitySources: {},
  },
});

/** `jsonb`. A key whose value is `undefined` does not survive. */
const persist = (o: unknown) => JSON.parse(JSON.stringify(o));

/** The generator's gate step, verbatim in shape: the narrative input. */
const gate = (enrichment: unknown) => {
  const r = activateSafeGenerationInputs({
    enhancedData: { locationIntelligence: enrichment },
    geography: null,
    geographyProvenance: { source: 'none', status: 'unresolved', absRequeried: false },
    cashRateTarget: null, cashRateMonthlyAverage: null, capturedAt: NOW.toISOString(),
  } as never);
  return (r.enhancedData as Record<string, unknown>).locationIntelligence;
};

/** `investment-scoring-service`'s own projection of the enrichment. */
const locationInputFor = (enrichment: any) => ({
  walkScore: enrichment?.walkScore ?? undefined,
  commuteTimeCBD: enrichment?.commute?.durationMinutes ?? undefined,
  schoolsNearby: enrichment?.schools?.schoolsWithin3km ?? undefined,
});

const scoreWith = (enrichment: unknown) => {
  const { verified } = verifiedLocationInputs(enrichment, SUBJECT);
  const record = scoreForProduction({
    subject: EVIDENCE_SUBJECT, market: MARKET as never,
    property: PROPERTY, finance: FINANCE,
    location: locationInputFor(enrichment), verifiedInputs: verified,
    evidenceWithheldReason: null, now: NOW,
  });
  return { verified, v2: record.v2 };
};

// ── the log ─────────────────────────────────────────────────────────────────
let failures = 0;
const check = (ok: boolean, label: string, detail = '') => {
  if (!ok) failures += 1;
  console.log(`  ${ok ? 'ok  ' : 'FAIL'}  ${label}${detail ? `  — ${detail}` : ''}`);
};
const readings = (e: any) => [
  `walkScore=${e?.walkScore ?? '(absent)'}`,
  `commute.durationMinutes=${e?.commute?.durationMinutes ?? '(absent)'}`,
  `schools.schoolsWithin3km=${e?.schools?.schoolsWithin3km ?? '(absent)'}`,
].join('  ');
const summarise = (label: string, r: ReturnType<typeof scoreWith>) => {
  const { v2 } = r as any;
  console.log(`      ${label}: grade=${v2.grade ?? '(withheld)'} score=${v2.score ?? '—'} `
    + `scoreGrade=${v2.scoreGrade ?? '—'} measured=${v2.dimensions.filter((d: any) => d.available).length}/${v2.dimensions.length} `
    + `coverage=${v2.evidenceCoverage != null ? `${Math.round(v2.evidenceCoverage * 100)}%` : '—'} `
    + `capped=${v2.gradeCapped} verified=[${r.verified.join(', ') || 'none'}]`);
};

// ═══ A · uninterrupted generation ═══════════════════════════════════════════
console.log('\nA · uninterrupted generation — acquire → gate → persist → score');
let acquisitions = 0;
const acquireCounted = (attempt: number, complete = true) => { acquisitions += 1; return acquire(attempt, complete); };

const fresh = acquireCounted(1);
const narrativeA = gate(fresh);
const storedA = persist(fresh);           // the repair: the MEASURED object is persisted
const scoredA = scoreWith(storedA);

console.log(`      acquired : ${readings(fresh)}`);
console.log(`      narrative: ${readings(narrativeA)}`);
console.log(`      persisted: ${readings(storedA)}`);
summarise('scored   ', scoredA);
check(DISOWNED_LOCATION_PATHS.every((p) => {
  const [h, t] = p.split('.');
  return (t === undefined ? (narrativeA as any)?.[h] : (narrativeA as any)?.[h]?.[t]) === undefined;
}), 'the narrative input still has every disowned path removed');
check((storedA as any).walkScore === 61 && (storedA as any).commute?.durationMinutes === 42
  && (storedA as any).schools?.schoolsWithin3km === 10, 'the persisted record kept all three measurements');
check(scoredA.verified.length === 3, 'all three Location inputs verify from the persisted record',
  scoredA.verified.join(', '));
check((scoredA.v2 as any).dimensions.find((d: any) => d.key === 'location')?.available === true,
  'Location is measured');

// ═══ B · forced resume, same frozen evidence ════════════════════════════════
console.log('\nB · forced resume — reload → reuse guard → score, nothing re-acquired');
const reloaded = persist(storedA);
const decisionB = assessEnrichmentReuse(reloaded, SUBJECT);
console.log(`      reuse: ${decisionB.reuse} (${decisionB.verdict})`);
const reusedEnrichment = decisionB.reuse
  ? reloaded
  : acquireCounted(nextAcquisitionAttempt(reloaded, SUBJECT));
const scoredB = scoreWith(reusedEnrichment);
summarise('scored   ', scoredB);
check(decisionB.reuse === true && decisionB.verdict === 'reusable', 'the resume reuses the stored enrichment');
check(acquisitions === 1, 'the resume bought no second acquisition', `acquisitions=${acquisitions}`);
check(JSON.stringify(scoredA.v2) === JSON.stringify(scoredB.v2),
  'the resume produces a byte-identical score to the uninterrupted run');

// ═══ C · a historically stripped row ════════════════════════════════════════
console.log('\nC · a row persisted before the repair — detect → re-acquire → reuse');
const legacyStored = persist(gate(acquire(1)));   // what the old code wrote
console.log(`      stored   : ${readings(legacyStored)}`);
const scoredLegacy = scoreWith(legacyStored);
summarise('if reused', scoredLegacy);
const decisionC1 = assessEnrichmentReuse(legacyStored, SUBJECT);
console.log(`      reuse: ${decisionC1.reuse} (${decisionC1.verdict})`);
check(decisionC1.reuse === false && decisionC1.verdict === 'readings_missing',
  'the stripped row is detected and refused');
check(scoredLegacy.verified.length === 0
  && (scoredLegacy.v2 as any).dimensions.find((d: any) => d.key === 'location')?.available === false,
  'and if it HAD been reused, Location would score nothing — the defect, reproduced');

const reacquired = acquire(nextAcquisitionAttempt(legacyStored, SUBJECT));
const storedC = persist(reacquired);
const decisionC2 = assessEnrichmentReuse(storedC, SUBJECT);
const scoredC = scoreWith(storedC);
console.log(`      after re-acquisition: ${readings(storedC)}  reuse=${decisionC2.reuse} (${decisionC2.verdict})`);
summarise('scored   ', scoredC);
check(decisionC2.reuse === true, 'the re-acquired row is reusable on the NEXT resume — one re-acquisition, not a loop');
check(JSON.stringify(scoredC.v2) === JSON.stringify(scoredA.v2), 'and scores identically to the uninterrupted run');

// ═══ D · a provider that did not answer ═════════════════════════════════════
console.log('\nD · an unavailable provider — honestly unmeasured, and no re-acquisition loop');
const partial = acquire(1, false);
const storedD = persist(partial);
console.log(`      stored   : ${readings(storedD)}  places=${(storedD as any).__acquisition.stages.places}`);
const scoredD = scoreWith(storedD);
summarise('scored   ', scoredD);
check((storedD as any).walkScore === null, 'a places run that did not complete stores null, never a measured zero');
// The PLACES readings must not verify — that is what `places: 'partial'`
// means. The commute is a different stage: it ran, its reading is present,
// and refusing it would punish a measurement nothing is wrong with.
check(!scoredD.verified.includes('walkScore') && !scoredD.verified.includes('schoolsNearby'),
  'neither places reading verifies from a partial acquisition',
  `verified=[${scoredD.verified.join(', ')}]`);
check(scoredD.verified.includes('commuteTimeCBD'),
  'while the commute, whose own stage completed, still does');
const verdicts: string[] = [];
let attempt = 1;
for (let resume = 1; resume <= 6; resume += 1) {
  const stored = persist(acquire(attempt, false));
  const d = assessEnrichmentReuse(stored, SUBJECT);
  verdicts.push(`${resume}:${d.reuse ? 'reuse' : 'refuse'}/${d.verdict}`);
  if (!d.reuse) attempt = nextAcquisitionAttempt(stored, SUBJECT);
}
console.log(`      six resumes: ${verdicts.join('  ')}`);
check(verdicts.some((v) => v.includes('reuse')), 'the partial retry is BOUNDED — it stops re-acquiring');
check(!verdicts.some((v) => v.includes('readings_missing')),
  'an honest partial is never mistaken for a stripped row');

console.log(`\n${failures === 0 ? 'ALL CHECKS PASSED' : `${failures} CHECK(S) FAILED`}\n`);
process.exitCode = failures === 0 ? 0 : 1;
