import { describe,expect,it } from 'vitest'; import { advancedClientCreationSchema } from './schema'; import { applicant } from './testFixtures'; import { zeroFactFind } from './testFixtures';
describe('Advanced payload validation',()=>{
 it('accepts dynamic assets and liabilities with the 50-row expense shape',()=>expect(advancedClientCreationSchema.safeParse(zeroFactFind()).success).toBe(true));
 it.each(['assets','liabilities'] as const)('requires at least one %s row',key=>{const p=zeroFactFind();p[key]=[];expect(advancedClientCreationSchema.safeParse(p).success).toBe(false)});
 it('still requires all expense rows',()=>{const p=zeroFactFind();p.expenses.pop();expect(advancedClientCreationSchema.safeParse(p).success).toBe(false)});
 it('rejects unknown and out-of-order expense keys',()=>{const p=zeroFactFind();p.expenses[0].expenseKey='unknown';expect(advancedClientCreationSchema.safeParse(p).success).toBe(false)});
 it('requires both Applicant 2 names when any details are supplied',()=>{const p=zeroFactFind();p.applicants.push({...applicant(2),email:'person@example.com'});expect(advancedClientCreationSchema.safeParse(p).success).toBe(false);p.applicants[1]!.firstName='Sam';p.applicants[1]!.surname='Smith';expect(advancedClientCreationSchema.safeParse(p).success).toBe(true)});
 it('rejects invalid email and colour',()=>{const p=zeroFactFind();p.applicants[0].email='bad';p.branding.primaryColour='blue';expect(advancedClientCreationSchema.safeParse(p).success).toBe(false)});
 it('rejects unknown payload properties',()=>{expect(advancedClientCreationSchema.safeParse({...zeroFactFind(),admin:true}).success).toBe(false)});
 it('rejects negative money and inconsistent positions',()=>{const p=zeroFactFind();p.assets[0].currentValue=-1;p.liabilities.reverse();expect(advancedClientCreationSchema.safeParse(p).success).toBe(false)});
 it.each(['Unemployed','Other','Astronaut'])('returns a clear error for unsupported populated Employment type %s',(employmentType)=>{const p=zeroFactFind();Object.assign(p.employment[0],{employmentType,employerOrBusiness:'Example'});const result=advancedClientCreationSchema.safeParse(p);expect(result.success).toBe(false);if(!result.success)expect(result.error.issues).toContainEqual(expect.objectContaining({path:['employment',0,'employmentType'],message:expect.stringContaining(`"${employmentType}" is not supported`)}))});
 it('skips a blank Employment row but requires Employer / Business for a populated row',()=>{expect(advancedClientCreationSchema.safeParse(zeroFactFind()).success).toBe(true);const p=zeroFactFind();p.employment[0].employmentType='Permanent';const result=advancedClientCreationSchema.safeParse(p);expect(result.success).toBe(false);if(!result.success)expect(result.error.issues).toContainEqual(expect.objectContaining({path:['employment',0,'employerOrBusiness'],message:'Employer / Business is required for an Employment record'}))});
});
