import { describe,expect,it,vi } from 'vitest';
import { createAdvancedDefaults, createEmptyAsset } from '@/components/clients/add-client/defaults';
import { isPropertyAsset,mapAdvancedToViewClient,normalizeEmploymentType,normalizePropertyType,saveAdvancedViewClientData } from './viewClientMapping';
describe('Advanced to View Client mapping',()=>{
 it('maps both applicants, addresses and employment without duplicate income records',()=>{const p=createAdvancedDefaults();Object.assign(p.applicants[0],{firstName:'Alex',surname:'Smith',middleName:'J',residencyStatus:'Citizen'});Object.assign(p.applicants[1]!,{firstName:'Taylor',surname:'Smith'});p.addresses[0].address='1 Main St';p.addresses[2].address='2 Other St';p.employment[0].employmentType='Permanent';p.employment[0].employerOrBusiness='Aurixa';p.employment[0].baseSalary=100000;const m=mapAdvancedToViewClient(p);expect(m.personal).toMatchObject({primary_first_name:'Alex',secondary_first_name:'Taylor',current_address:'1 Main St',secondary_current_address:'2 Other St'});expect(m.addresses).toHaveLength(2);expect(m.employment).toHaveLength(1);expect(m.employment[0]).toMatchObject({contact_type:'primary',gross_annual_salary:100000});expect(m).not.toHaveProperty('income')});
 it('classifies clear property assets and leaves ambiguous assets in Financials',()=>{const p=createAdvancedDefaults();p.assets.push(createEmptyAsset(1));Object.assign(p.assets[0],{assetType:'Investment Property',descriptionOrAddress:'3 Coast Rd',currentValue:900000,loanBalance:400000,monthlyRepayment:2200});Object.assign(p.assets[1],{assetType:'Shares',descriptionOrAddress:'Index fund',currentValue:50000});expect(isPropertyAsset(p.assets[0])).toBe(true);const m=mapAdvancedToViewClient(p);expect(m.properties[0]).toMatchObject({address:'3 Coast Rd',value:900000,loan_remaining:400000});expect(m.assets[0]).toMatchObject({description:'Index fund',value:50000})});
 it('maps debt current balance, meaningful expenses, and skips blank fixed rows',()=>{const p=createAdvancedDefaults();Object.assign(p.liabilities[0],{liabilityType:'Credit Card',limitOrOriginalAmount:10000,currentBalance:1200,lender:'Bank'});p.expenses[0].notes='Shared care';const m=mapAdvancedToViewClient(p);expect(m.liabilities).toHaveLength(1);expect(m.liabilities[0]).toMatchObject({current_balance:1200,credit_limit:10000});expect(m.assets).toHaveLength(0);expect(m.expenses).toHaveLength(1)});
 it.each([['Permanent','permanent'],['Full-time','permanent'],['Part-time','part_time'],['Self-employed','self_employed'],['Contractor','contract'],['Casual','casual']])('normalises imported employment type %s to an exact manual-form value', (input,expected)=>expect(normalizeEmploymentType(input)).toBe(expected));
 it.each(['Unemployed','Other','Astronaut'])('rejects imported employment type %s because it is absent from the manual contract',(input)=>expect(normalizeEmploymentType(input)).toBeNull());
 it('maps valid primary and secondary imported employment without the rejected work_arrangement column',()=>{const p=createAdvancedDefaults();Object.assign(p.employment[0],{employmentType:'Full-time',employerOrBusiness:'Aurixa',roleOrPosition:'Director',employerAddress:'1 Work St',startDate:'2020-01-01',baseSalary:100000,bonus:5,commission:6,overtime:7,otherTaxableIncome:8});Object.assign(p.employment[1]!,{employmentType:'Self-employed',employerOrBusiness:'Studio',baseSalary:90000});const rows=mapAdvancedToViewClient(p).employment;expect(rows).toHaveLength(2);expect(rows[0]).toEqual({contact_type:'primary',additional_contact_id:null,is_current:true,employment_type:'permanent',occupation_role:'Director',employer_name:'Aurixa',start_date:'2020-01-01',salary_amount:100000,salary_frequency:'annual',gross_annual_salary:100000,bonus:5,commission:6,overtime_essential:7,overtime_non_essential:0,allowance:0,other_taxable_income:8,workplace_address_line_1:'1 Work St',workplace_suburb:null,workplace_state:null,workplace_postcode:null,workplace_country:null});expect(rows[0]).not.toHaveProperty('work_arrangement');expect(rows[1]).toMatchObject({contact_type:'secondary',additional_contact_id:null,employment_type:'self_employed',employer_name:'Studio',salary_frequency:'annual'})});
 it('does not save blank or unsupported employment records',()=>{const p=createAdvancedDefaults();p.employment[0].employmentType='Astronaut';p.employment[0].employerOrBusiness='Space';p.employment[1]!.employmentType='Permanent';expect(mapAdvancedToViewClient(p).employment).toEqual([])});
 it.each([['Owner Occupied','owner_occupied'],['Principal Place of Residence','owner_occupied'],['Investment Property','investment'],['Rental Property','investment'],['SMSF Property','smsf']])('normalises property label %s', (label,expected)=>{const p=createAdvancedDefaults();p.assets[0].assetType=label;p.assets[0].descriptionOrAddress='1 Home St';expect(normalizePropertyType(p.assets[0])).toBe(expected)});
 it('maps imported property fields to the working property contract and excludes blank and financial assets',()=>{const p=createAdvancedDefaults();p.assets.push(createEmptyAsset(1));Object.assign(p.assets[0],{assetType:'Investment Property',descriptionOrAddress:'3 Coast Rd',currentValue:900000,loanBalance:400000,interestRate:6,monthlyRepayment:2200,rentalOrOtherIncome:3000});Object.assign(p.assets[1],{assetType:'Shares',descriptionOrAddress:'Index fund',currentValue:50000});const m=mapAdvancedToViewClient(p);expect(m.properties).toHaveLength(1);expect(m.properties[0]).toMatchObject({property_type:'investment',address:'3 Coast Rd',value:900000,loan_remaining:400000,interest_rate:6,ownership_percentage:100,monthly_interest_repayment:2200,repayment_type:'principal_and_interest',monthly_rental_income:3000,total_monthly_expenditure:2200,net_monthly_cashflow:800,sourced_by:'unknown'});expect(m.assets).toHaveLength(1)});
 it('saves through existing manage-client-data tables',async()=>{const p=createAdvancedDefaults();p.applicants[0].firstName='Alex';p.applicants[0].surname='Smith';p.assets[0].assetType='Savings';p.assets[0].currentValue=100;const invoke=vi.fn().mockResolvedValue({data:{success:true}});expect((await saveAdvancedViewClientData('client-1',p,invoke)).failures).toEqual([]);expect(invoke).toHaveBeenCalledWith('manage-client-data',expect.objectContaining({operation:'update',table:'clients',clientId:'client-1'}));expect(invoke).toHaveBeenCalledWith('manage-client-data',expect.objectContaining({operation:'create',table:'client_assets',clientId:'client-1'}))});
 it('returns safe backend reasons and retries only failed records',async()=>{const p=createAdvancedDefaults();Object.assign(p.employment[0],{employmentType:'Permanent',employerOrBusiness:'Aurixa'});Object.assign(p.assets[0],{assetType:'Owner Occupied',descriptionOrAddress:'1 Home St'});const invoke=vi.fn(async(_name,body:any)=>body.table==='client_employment'?{data:{success:false,error:'invalid employment type'}}:{data:{success:true}});const first=await saveAdvancedViewClientData('client-1',p,invoke);expect(first.failures).toEqual([{key:'client_employment:0',label:'Employment and Income',reason:'invalid employment type'}]);invoke.mockClear();invoke.mockResolvedValue({data:{success:true}});const retry=await saveAdvancedViewClientData('client-1',p,invoke,first.completed);expect(retry.failures).toEqual([]);expect(invoke).toHaveBeenCalledTimes(1);expect(invoke.mock.calls[0][1]).toMatchObject({table:'client_employment'})});
 it('submits clientId outside the Employment data contract and prefers safe backend details over a generic error',async()=>{const p=createAdvancedDefaults();Object.assign(p.employment[0],{employmentType:'Permanent',employerOrBusiness:'Aurixa'});const invoke=vi.fn(async(_name,body:any)=>body.table==='client_employment'?{data:{success:false,error:'Failed to create record',details:'employment type is not supported'}}:{data:{success:true}});const result=await saveAdvancedViewClientData('client-1',p,invoke);expect(result.failures).toContainEqual({key:'client_employment:0',label:'Employment and Income',reason:'employment type is not supported'});const call=invoke.mock.calls.find(([,body])=>body.table==='client_employment')!;expect(call[1].clientId).toBe('client-1');expect(call[1].data).not.toHaveProperty('client_id')});
});
