-- Versioned Advanced Client Fact Find persistence. All money is stored as integer AUD cents.
CREATE TABLE public.client_fact_finds (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), client_id uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
 status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','finalized','archived')), template_version text NOT NULL,
 revision integer NOT NULL DEFAULT 1 CHECK(revision>0), total_assets_cents bigint NOT NULL DEFAULT 0 CHECK(total_assets_cents>=0),
 total_asset_linked_debt_cents bigint NOT NULL DEFAULT 0 CHECK(total_asset_linked_debt_cents>=0), total_other_liabilities_cents bigint NOT NULL DEFAULT 0 CHECK(total_other_liabilities_cents>=0),
 total_debt_cents bigint NOT NULL DEFAULT 0 CHECK(total_debt_cents>=0), net_position_cents bigint NOT NULL DEFAULT 0,
 applicant_1_annual_income_cents bigint NOT NULL DEFAULT 0 CHECK(applicant_1_annual_income_cents>=0), applicant_2_annual_income_cents bigint NOT NULL DEFAULT 0 CHECK(applicant_2_annual_income_cents>=0),
 total_monthly_living_expenses_cents bigint NOT NULL DEFAULT 0 CHECK(total_monthly_living_expenses_cents>=0), created_by uuid NOT NULL, updated_by uuid NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(client_id,revision)
);
CREATE TABLE public.client_fact_find_brand_snapshots (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fact_find_id uuid NOT NULL UNIQUE REFERENCES public.client_fact_finds(id) ON DELETE CASCADE,
 organisation_name text NOT NULL DEFAULT '', trading_name text NOT NULL DEFAULT '', tagline text NOT NULL DEFAULT '', primary_colour text NOT NULL CHECK(primary_colour ~ '^#[0-9A-Fa-f]{6}$'), accent_colour text NOT NULL CHECK(accent_colour ~ '^#[0-9A-Fa-f]{6}$'),
 website text NOT NULL DEFAULT '', email text NOT NULL DEFAULT '', phone text NOT NULL DEFAULT '', business_address text NOT NULL DEFAULT '', document_title text NOT NULL DEFAULT '', confidentiality_label text NOT NULL DEFAULT '', prepared_by text NOT NULL DEFAULT '',
 logo_reference text NOT NULL DEFAULT '', version text NOT NULL DEFAULT '', source_white_label_setting_id uuid REFERENCES public.whitelabel_settings(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.client_fact_find_applicants (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fact_find_id uuid NOT NULL REFERENCES public.client_fact_finds(id) ON DELETE CASCADE, applicant_number smallint NOT NULL CHECK(applicant_number IN(1,2)),
 relationship text NOT NULL CHECK((applicant_number=1 AND relationship='primary_client') OR (applicant_number=2 AND relationship='secondary_contact')),
 title text NOT NULL DEFAULT '', first_name text NOT NULL DEFAULT '', middle_name text NOT NULL DEFAULT '', surname text NOT NULL DEFAULT '', date_of_birth date, gender text NOT NULL DEFAULT '', marital_status text NOT NULL DEFAULT '', residency_status text NOT NULL DEFAULT '', number_of_dependants integer CHECK(number_of_dependants>=0), mobile text NOT NULL DEFAULT '', email text NOT NULL DEFAULT '', UNIQUE(fact_find_id,applicant_number)
);
CREATE TABLE public.client_fact_find_addresses (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fact_find_id uuid NOT NULL REFERENCES public.client_fact_finds(id) ON DELETE CASCADE, applicant_number smallint NOT NULL CHECK(applicant_number IN(1,2)), address_type text NOT NULL CHECK(address_type IN('current','previous')),
 address text NOT NULL DEFAULT '', living_situation text NOT NULL DEFAULT '', moved_in_date date, display_order smallint NOT NULL CHECK(display_order IN(0,1)), UNIQUE(fact_find_id,applicant_number,address_type), UNIQUE(fact_find_id,applicant_number,display_order)
);
CREATE TABLE public.client_fact_find_employment (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fact_find_id uuid NOT NULL REFERENCES public.client_fact_finds(id) ON DELETE CASCADE, applicant_number smallint NOT NULL CHECK(applicant_number IN(1,2)), employment_type text NOT NULL DEFAULT '', employer_or_business text NOT NULL DEFAULT '', role_or_position text NOT NULL DEFAULT '', employer_address text NOT NULL DEFAULT '', start_date date,
 base_salary_cents bigint NOT NULL DEFAULT 0 CHECK(base_salary_cents>=0), bonus_cents bigint NOT NULL DEFAULT 0 CHECK(bonus_cents>=0), commission_cents bigint NOT NULL DEFAULT 0 CHECK(commission_cents>=0), overtime_cents bigint NOT NULL DEFAULT 0 CHECK(overtime_cents>=0), other_taxable_income_cents bigint NOT NULL DEFAULT 0 CHECK(other_taxable_income_cents>=0), UNIQUE(fact_find_id,applicant_number)
);
CREATE TABLE public.client_fact_find_assets (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fact_find_id uuid NOT NULL REFERENCES public.client_fact_finds(id) ON DELETE CASCADE, display_order smallint NOT NULL CHECK(display_order BETWEEN 0 AND 9), asset_type text NOT NULL DEFAULT '', description_or_address text NOT NULL DEFAULT '', owner text NOT NULL DEFAULT '',
 current_value_cents bigint NOT NULL DEFAULT 0 CHECK(current_value_cents>=0), rental_or_other_income_cents bigint NOT NULL DEFAULT 0 CHECK(rental_or_other_income_cents>=0), financial_institution text NOT NULL DEFAULT '', loan_balance_cents bigint NOT NULL DEFAULT 0 CHECK(loan_balance_cents>=0), monthly_repayment_cents bigint NOT NULL DEFAULT 0 CHECK(monthly_repayment_cents>=0), interest_rate numeric(7,4) NOT NULL DEFAULT 0 CHECK(interest_rate BETWEEN 0 AND 100), maturity_date date, UNIQUE(fact_find_id,display_order)
);
CREATE TABLE public.client_fact_find_liabilities (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fact_find_id uuid NOT NULL REFERENCES public.client_fact_finds(id) ON DELETE CASCADE, display_order smallint NOT NULL CHECK(display_order BETWEEN 0 AND 7), liability_type text NOT NULL DEFAULT '', lender text NOT NULL DEFAULT '', account_or_description text NOT NULL DEFAULT '', owner text NOT NULL DEFAULT '', limit_or_original_amount_cents bigint NOT NULL DEFAULT 0 CHECK(limit_or_original_amount_cents>=0), current_balance_cents bigint NOT NULL DEFAULT 0 CHECK(current_balance_cents>=0), monthly_repayment_cents bigint NOT NULL DEFAULT 0 CHECK(monthly_repayment_cents>=0), interest_rate numeric(7,4) NOT NULL DEFAULT 0 CHECK(interest_rate BETWEEN 0 AND 100), remaining_term text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '', UNIQUE(fact_find_id,display_order)
);
CREATE TABLE public.client_fact_find_expenses (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fact_find_id uuid NOT NULL REFERENCES public.client_fact_finds(id) ON DELETE CASCADE, expense_key text NOT NULL, workbook_category text NOT NULL, workbook_item_label text NOT NULL, display_order smallint NOT NULL CHECK(display_order BETWEEN 0 AND 49), monthly_amount_cents bigint NOT NULL DEFAULT 0 CHECK(monthly_amount_cents>=0), notes text NOT NULL DEFAULT '', UNIQUE(fact_find_id,expense_key), UNIQUE(fact_find_id,display_order)
);
CREATE TABLE public.client_fact_find_outputs (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fact_find_id uuid NOT NULL REFERENCES public.client_fact_finds(id) ON DELETE CASCADE, template_version text NOT NULL, branding_snapshot_id uuid NOT NULL REFERENCES public.client_fact_find_brand_snapshots(id) ON DELETE RESTRICT, generated_at timestamptz, storage_path text, output_hash text CHECK(output_hash IS NULL OR output_hash ~ '^[0-9a-f]{64}$'), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX client_fact_finds_client_idx ON public.client_fact_finds(client_id,revision DESC);
CREATE INDEX client_fact_find_assets_fact_idx ON public.client_fact_find_assets(fact_find_id);
CREATE INDEX client_fact_find_liabilities_fact_idx ON public.client_fact_find_liabilities(fact_find_id);
CREATE INDEX client_fact_find_expenses_fact_idx ON public.client_fact_find_expenses(fact_find_id);

CREATE OR REPLACE FUNCTION public.can_access_client_fact_find(_fact_find_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT EXISTS(SELECT 1 FROM public.client_fact_finds f JOIN public.clients c ON c.id=f.client_id WHERE f.id=_fact_find_id AND (c.created_by=auth.uid() OR c.assigned_team_user_id=auth.uid() OR public.has_role(auth.uid(),'superadmin')))
$$;
REVOKE ALL ON FUNCTION public.can_access_client_fact_find(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_access_client_fact_find(uuid) TO authenticated, service_role;

ALTER TABLE public.client_fact_finds ENABLE ROW LEVEL SECURITY; ALTER TABLE public.client_fact_find_brand_snapshots ENABLE ROW LEVEL SECURITY; ALTER TABLE public.client_fact_find_applicants ENABLE ROW LEVEL SECURITY; ALTER TABLE public.client_fact_find_addresses ENABLE ROW LEVEL SECURITY; ALTER TABLE public.client_fact_find_employment ENABLE ROW LEVEL SECURITY; ALTER TABLE public.client_fact_find_assets ENABLE ROW LEVEL SECURITY; ALTER TABLE public.client_fact_find_liabilities ENABLE ROW LEVEL SECURITY; ALTER TABLE public.client_fact_find_expenses ENABLE ROW LEVEL SECURITY; ALTER TABLE public.client_fact_find_outputs ENABLE ROW LEVEL SECURITY;
CREATE POLICY fact_finds_select ON public.client_fact_finds FOR SELECT TO authenticated USING(public.can_access_client_fact_find(id));
CREATE POLICY fact_find_brand_select ON public.client_fact_find_brand_snapshots FOR SELECT TO authenticated USING(public.can_access_client_fact_find(fact_find_id));
CREATE POLICY fact_find_applicant_select ON public.client_fact_find_applicants FOR SELECT TO authenticated USING(public.can_access_client_fact_find(fact_find_id));
CREATE POLICY fact_find_address_select ON public.client_fact_find_addresses FOR SELECT TO authenticated USING(public.can_access_client_fact_find(fact_find_id));
CREATE POLICY fact_find_employment_select ON public.client_fact_find_employment FOR SELECT TO authenticated USING(public.can_access_client_fact_find(fact_find_id));
CREATE POLICY fact_find_asset_select ON public.client_fact_find_assets FOR SELECT TO authenticated USING(public.can_access_client_fact_find(fact_find_id));
CREATE POLICY fact_find_liability_select ON public.client_fact_find_liabilities FOR SELECT TO authenticated USING(public.can_access_client_fact_find(fact_find_id));
CREATE POLICY fact_find_expense_select ON public.client_fact_find_expenses FOR SELECT TO authenticated USING(public.can_access_client_fact_find(fact_find_id));
CREATE POLICY fact_find_output_select ON public.client_fact_find_outputs FOR SELECT TO authenticated USING(public.can_access_client_fact_find(fact_find_id));
REVOKE ALL ON public.client_fact_finds,public.client_fact_find_brand_snapshots,public.client_fact_find_applicants,public.client_fact_find_addresses,public.client_fact_find_employment,public.client_fact_find_assets,public.client_fact_find_liabilities,public.client_fact_find_expenses,public.client_fact_find_outputs FROM anon,authenticated;
GRANT SELECT ON public.client_fact_finds,public.client_fact_find_brand_snapshots,public.client_fact_find_applicants,public.client_fact_find_addresses,public.client_fact_find_employment,public.client_fact_find_assets,public.client_fact_find_liabilities,public.client_fact_find_expenses,public.client_fact_find_outputs TO authenticated;
GRANT ALL ON public.client_fact_finds,public.client_fact_find_brand_snapshots,public.client_fact_find_applicants,public.client_fact_find_addresses,public.client_fact_find_employment,public.client_fact_find_assets,public.client_fact_find_liabilities,public.client_fact_find_expenses,public.client_fact_find_outputs TO service_role;

CREATE OR REPLACE FUNCTION public.create_advanced_client_fact_find(_actor_id uuid,_client jsonb,_payload jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE cid uuid; fid uuid; bid uuid; computed jsonb; supplied jsonb:=_payload->'calculatedTotals';
BEGIN
 IF _actor_id IS NULL OR _payload IS NULL OR _client IS NULL THEN RAISE EXCEPTION 'invalid request'; END IF;
 IF jsonb_array_length(_payload->'assets')<>10 OR jsonb_array_length(_payload->'liabilities')<>8 OR jsonb_array_length(_payload->'expenses')<>50 THEN RAISE EXCEPTION 'workbook row counts are invalid'; END IF;
 IF nullif(btrim(_client->>'primary_first_name'),'') IS NULL OR nullif(btrim(_client->>'primary_surname'),'') IS NULL THEN RAISE EXCEPTION 'primary name required'; END IF;
 INSERT INTO public.clients(primary_first_name,primary_surname,primary_email,primary_mobile,secondary_first_name,secondary_surname,secondary_email,secondary_mobile,current_address,ghl_sync_status,total_portfolio_value,total_debt,net_monthly_cash_flow,created_by)
 VALUES(btrim(_client->>'primary_first_name'),btrim(_client->>'primary_surname'),nullif(btrim(_client->>'primary_email'),''),nullif(btrim(_client->>'primary_mobile'),''),nullif(btrim(_client->>'secondary_first_name'),''),nullif(btrim(_client->>'secondary_surname'),''),nullif(btrim(_client->>'secondary_email'),''),nullif(btrim(_client->>'secondary_mobile'),''),nullif(btrim(_client->>'current_address'),''),CASE WHEN coalesce((_payload->>'syncToGhl')::boolean,false) THEN 'pending' END,0,0,0,_actor_id) RETURNING id INTO cid;
 INSERT INTO public.client_fact_finds(client_id,template_version,created_by,updated_by) VALUES(cid,_payload->>'templateVersion',_actor_id,_actor_id) RETURNING id INTO fid;
 INSERT INTO public.client_fact_find_brand_snapshots(fact_find_id,organisation_name,trading_name,tagline,primary_colour,accent_colour,website,email,phone,business_address,document_title,confidentiality_label,prepared_by,logo_reference,version,source_white_label_setting_id)
 VALUES(fid,_payload#>>'{branding,organisationName}',_payload#>>'{branding,tradingName}',_payload#>>'{branding,tagline}',_payload#>>'{branding,primaryColour}',_payload#>>'{branding,accentColour}',_payload#>>'{branding,website}',_payload#>>'{branding,email}',_payload#>>'{branding,phone}',_payload#>>'{branding,businessAddress}',_payload#>>'{branding,documentTitle}',_payload#>>'{branding,confidentialityLabel}',_payload#>>'{branding,preparedBy}',_payload#>>'{branding,logoReference}',_payload#>>'{branding,version}',nullif(_payload#>>'{branding,sourceWhiteLabelSettingId}','')::uuid) RETURNING id INTO bid;
 INSERT INTO public.client_fact_find_applicants(fact_find_id,applicant_number,relationship,title,first_name,middle_name,surname,date_of_birth,gender,marital_status,residency_status,number_of_dependants,mobile,email)
 SELECT fid,x."applicantNumber",x.relationship,x.title,x."firstName",x."middleName",x.surname,nullif(x."dateOfBirth",'')::date,x.gender,x."maritalStatus",x."residencyStatus",x."numberOfDependants",x.mobile,x.email FROM jsonb_to_recordset(_payload->'applicants') x("applicantNumber" smallint,relationship text,title text,"firstName" text,"middleName" text,surname text,"dateOfBirth" text,gender text,"maritalStatus" text,"residencyStatus" text,"numberOfDependants" integer,mobile text,email text);
 INSERT INTO public.client_fact_find_addresses(fact_find_id,applicant_number,address_type,address,living_situation,moved_in_date,display_order) SELECT fid,x."applicantNumber",x."addressType",x.address,x."livingSituation",nullif(x."movedInDate",'')::date,x."displayOrder" FROM jsonb_to_recordset(_payload->'addresses') x("applicantNumber" smallint,"addressType" text,address text,"livingSituation" text,"movedInDate" text,"displayOrder" smallint);
 INSERT INTO public.client_fact_find_employment(fact_find_id,applicant_number,employment_type,employer_or_business,role_or_position,employer_address,start_date,base_salary_cents,bonus_cents,commission_cents,overtime_cents,other_taxable_income_cents)
 SELECT fid,x."applicantNumber",x."employmentType",x."employerOrBusiness",x."roleOrPosition",x."employerAddress",nullif(x."startDate",'')::date,round(coalesce(x."baseSalary",0)*100),round(coalesce(x.bonus,0)*100),round(coalesce(x.commission,0)*100),round(coalesce(x.overtime,0)*100),round(coalesce(x."otherTaxableIncome",0)*100) FROM jsonb_to_recordset(_payload->'employment') x("applicantNumber" smallint,"employmentType" text,"employerOrBusiness" text,"roleOrPosition" text,"employerAddress" text,"startDate" text,"baseSalary" numeric,bonus numeric,commission numeric,overtime numeric,"otherTaxableIncome" numeric);
 INSERT INTO public.client_fact_find_assets(fact_find_id,display_order,asset_type,description_or_address,owner,current_value_cents,rental_or_other_income_cents,financial_institution,loan_balance_cents,monthly_repayment_cents,interest_rate,maturity_date)
 SELECT fid,x."displayOrder",x."assetType",x."descriptionOrAddress",x.owner,round(coalesce(x."currentValue",0)*100),round(coalesce(x."rentalOrOtherIncome",0)*100),x."financialInstitution",round(coalesce(x."loanBalance",0)*100),round(coalesce(x."monthlyRepayment",0)*100),coalesce(x."interestRate",0),nullif(x."maturityDate",'')::date FROM jsonb_to_recordset(_payload->'assets') x("displayOrder" smallint,"assetType" text,"descriptionOrAddress" text,owner text,"currentValue" numeric,"rentalOrOtherIncome" numeric,"financialInstitution" text,"loanBalance" numeric,"monthlyRepayment" numeric,"interestRate" numeric,"maturityDate" text);
 INSERT INTO public.client_fact_find_liabilities(fact_find_id,display_order,liability_type,lender,account_or_description,owner,limit_or_original_amount_cents,current_balance_cents,monthly_repayment_cents,interest_rate,remaining_term,notes)
 SELECT fid,x."displayOrder",x."liabilityType",x.lender,x."accountOrDescription",x.owner,round(coalesce(x."limitOrOriginalAmount",0)*100),round(coalesce(x."currentBalance",0)*100),round(coalesce(x."monthlyRepayment",0)*100),coalesce(x."interestRate",0),x."remainingTerm",x.notes FROM jsonb_to_recordset(_payload->'liabilities') x("displayOrder" smallint,"liabilityType" text,lender text,"accountOrDescription" text,owner text,"limitOrOriginalAmount" numeric,"currentBalance" numeric,"monthlyRepayment" numeric,"interestRate" numeric,"remainingTerm" text,notes text);
 INSERT INTO public.client_fact_find_expenses(fact_find_id,expense_key,workbook_category,workbook_item_label,display_order,monthly_amount_cents,notes)
 SELECT fid,x."expenseKey",x.category,x."itemLabel",x."displayOrder",round(coalesce(x."monthlyAmount",0)*100),x.notes FROM jsonb_to_recordset(_payload->'expenses') x("expenseKey" text,category text,"itemLabel" text,"displayOrder" smallint,"monthlyAmount" numeric,notes text);
 SELECT jsonb_build_object('totalAssetsCents',coalesce((SELECT sum(current_value_cents) FROM public.client_fact_find_assets WHERE fact_find_id=fid),0),'totalAssetLinkedDebtCents',coalesce((SELECT sum(loan_balance_cents) FROM public.client_fact_find_assets WHERE fact_find_id=fid),0),'totalOtherLiabilitiesCents',coalesce((SELECT sum(current_balance_cents) FROM public.client_fact_find_liabilities WHERE fact_find_id=fid),0),'applicant1AnnualIncomeCents',coalesce((SELECT base_salary_cents+bonus_cents+commission_cents+overtime_cents+other_taxable_income_cents FROM public.client_fact_find_employment WHERE fact_find_id=fid AND applicant_number=1),0),'applicant2AnnualIncomeCents',coalesce((SELECT base_salary_cents+bonus_cents+commission_cents+overtime_cents+other_taxable_income_cents FROM public.client_fact_find_employment WHERE fact_find_id=fid AND applicant_number=2),0),'totalMonthlyLivingExpensesCents',coalesce((SELECT sum(monthly_amount_cents) FROM public.client_fact_find_expenses WHERE fact_find_id=fid),0)) INTO computed;
 computed:=computed||jsonb_build_object('totalDebtCents',(computed->>'totalAssetLinkedDebtCents')::bigint+(computed->>'totalOtherLiabilitiesCents')::bigint,'netPositionCents',(computed->>'totalAssetsCents')::bigint-(computed->>'totalAssetLinkedDebtCents')::bigint-(computed->>'totalOtherLiabilitiesCents')::bigint,'clientFormOutputLivingExpensesCents',(computed->>'totalMonthlyLivingExpensesCents')::bigint);
 IF supplied IS NOT NULL AND supplied<>computed THEN RAISE EXCEPTION 'client totals do not match server calculations'; END IF;
 UPDATE public.client_fact_finds SET total_assets_cents=(computed->>'totalAssetsCents')::bigint,total_asset_linked_debt_cents=(computed->>'totalAssetLinkedDebtCents')::bigint,total_other_liabilities_cents=(computed->>'totalOtherLiabilitiesCents')::bigint,total_debt_cents=(computed->>'totalDebtCents')::bigint,net_position_cents=(computed->>'netPositionCents')::bigint,applicant_1_annual_income_cents=(computed->>'applicant1AnnualIncomeCents')::bigint,applicant_2_annual_income_cents=(computed->>'applicant2AnnualIncomeCents')::bigint,total_monthly_living_expenses_cents=(computed->>'totalMonthlyLivingExpensesCents')::bigint WHERE id=fid;
 INSERT INTO public.client_fact_find_outputs(fact_find_id,template_version,branding_snapshot_id) VALUES(fid,_payload->>'templateVersion',bid);
 RETURN jsonb_build_object('clientId',cid,'factFindId',fid,'totals',computed);
END $$;
REVOKE ALL ON FUNCTION public.create_advanced_client_fact_find(uuid,jsonb,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_advanced_client_fact_find(uuid,jsonb,jsonb) TO service_role;
