-- Retire the Investment Compass pilot, and give the format a global master.
--
-- ## What was measured
--
-- `resolve_report_template('investment_compass')` returned
-- **"Investment Compass — WeasyPrint Pilot"**, and that row's `engine` is
-- `jspdf`. `routeReportThroughTemplate` skips any resolution whose engine is
-- not `weasyprint` and the caller falls through to the legacy generator
-- (`docs/reports/TEMPLATE_SELECTION.md`, "A chosen template that will not be
-- drawn has to say so"). So on 2026-08-16 the position in production was:
--
--   * one globally-active investment_compass row, engine `jspdf`, is_default,
--     no `libraryLineage` — it came from no catalogue entry, which is why no
--     re-activation could ever refresh it, and 61 pages of schema nothing has
--     rendered since 6 Aug;
--   * one WeasyPrint master, "Data / Analyst — Dictionary", `scope = 'user'`
--     and therefore invisible to the ranking (`rank_source` is NULL for a
--     user-scoped row when no user id is passed);
--   * exactly one stored selection for the format, belonging to that same
--     user.
--
-- Everyone else's Investment Compass resolved the pilot, was refused at the
-- engine gate, and came out of the legacy generator. The design system was
-- reachable only by an explicit per-user choice.
--
-- ## And the four non-Compass tiers had nothing at all
--
-- `getReportType` now answers `investment` for the snapshot, briefing,
-- strategic and financial tiers — 63 stored reports — where it used to fall
-- through to `report_scope` and answer `address`, which matches no adapter.
-- Fixing that spelling was necessary and not sufficient: `report_templates`
-- has never held an active row under `investment` either, and
-- `resolve_report_template` matches the raw column with an equality, so those
-- 63 reports resolved nothing and still fell back.
--
-- `investment` and `investment_compass` are ONE format to everything that
-- normalises (`REPORT_TYPE_ALIASES`), and TWO to the resolver, which is why
-- this file writes a row under each. Both spellings are already in
-- `PRODUCTION_REPORT_TEMPLATE_TYPES`, so neither is a new activatable type.
--
-- ## Which master
--
-- The same one `20260814190000` gave the other eight formats: Private
-- Banking, variant A — "Chancery", the drawn reference of the catalogue's
-- leading family, published, production-ready, `weasyprint`, authored palette
-- unbaked. The `investment` row is copied from the same entry; its
-- `report_type` is the only field that does not come from the entry verbatim,
-- because the entry is catalogued under `investment_compass` and the resolver
-- needs the other spelling to exist as a row.
--
-- ## The rules this file keeps
--
-- 1. **Idempotent.** The pilot is deactivated by id AND name AND engine, so it
--    matches nothing on a second run; each insert is skipped when an active
--    global WeasyPrint row already exists for that spelling.
-- 2. **The pilot is deactivated, never deleted.** Its schema, its four render
--    jobs and its audit trail stay readable, and re-activating it is one
--    UPDATE if this turns out to be wrong.
-- 3. **No user-scoped row is touched.** "Data / Analyst — Dictionary" and the
--    selection pointing at it are left exactly as they are: a stored selection
--    beats the ranking, so that user's documents do not change at all.
-- 4. **All or nothing.** One DO block is one statement.
--
-- Behavioural consequence, stated plainly: an Investment Compass generated by
-- somebody with no stored selection now routes through the design system
-- instead of the legacy generator. That is the change being asked for. Every
-- failure path inside the template route still falls back to legacy, and
-- deactivating the two new rows returns the format to exactly its previous
-- behaviour.

do $$
declare
  spellings constant text[] := array['investment_compass', 'investment'];
  spelling text;
  e record;
  n integer;
  created_id uuid;
begin
  -- Assert the master before writing anything.
  select count(*) into n
  from public.template_library_entries t
  where t.slug = 'investment-compass-pb-01-chancery'
    and t.status = 'published'
    and t.production_ready = true
    and t.engine = 'weasyprint';
  if n <> 1 then
    raise exception
      'retire_compass_pilot: expected exactly one published, production-ready investment-compass-pb-01-chancery, found %', n;
  end if;

  select * into strict e
  from public.template_library_entries t
  where t.slug = 'investment-compass-pb-01-chancery';

  -- 1. Retire the pilot. Matched on all three of id, name and engine so this
  --    cannot touch a row that has since been rebuilt under the same id.
  update public.report_templates
  set is_active = false,
      is_default = false,
      updated_at = now()
  where id = 'd5cbb393-f856-42bc-9a39-477bdc09d5ba'
    and name = 'Investment Compass — WeasyPrint Pilot'
    and engine = 'jspdf'
    and is_active = true;

  if found then
    insert into public.template_audit_log (template_id, actor_id, action, summary, metadata)
    values (
      'd5cbb393-f856-42bc-9a39-477bdc09d5ba',
      null,
      'deactivated',
      'Retired: engine jspdf, so routeReportThroughTemplate refused it and every Investment Compass '
        || 'with no stored selection fell back to the legacy generator. Replaced by the catalogue master '
        || '(seed 20260816160000).',
      jsonb_build_object('seed', '20260816160000_retire_compass_pilot_and_activate_investment_masters')
    );
  end if;

  -- 2. One global master per raw spelling the adapter can emit.
  foreach spelling in array spellings loop
    if exists (
      select 1 from public.report_templates rt
      where rt.report_type = spelling
        and rt.is_active = true
        and coalesce(rt.scope, 'global') = 'global'
        and rt.engine = 'weasyprint'
    ) then
      raise notice 'retire_compass_pilot: % already has an active global WeasyPrint template — leaving it alone', spelling;
      continue;
    end if;

    insert into public.report_templates (
      name, description, schema, config, custom_css,
      report_type, tier, variant, engine, version,
      is_active, is_default, is_draft, approval_status, locked_for_review,
      priority, parent_template_id, created_by, scope, owner_user_id, agency_id, active_theme
    ) values (
      'Private Banking — Chancery',
      e.description,
      e.schema,
      coalesce(e.config, '{}'::jsonb) || jsonb_build_object(
        'libraryLineage', jsonb_build_object(
          'entryId', e.id,
          'entrySlug', e.slug,
          'entryVersion', e.version,
          'familyKey', e.design_meta->>'familyKey',
          'familyName', e.design_meta->>'familyName',
          'templateCode', e.design_meta->>'templateCode',
          'variantAxis', e.design_meta->>'variantAxis',
          'density', e.design_meta->>'density',
          'colourway', null,
          'colourwayName', null,
          'ground', null
        )
      ),
      e.custom_css,
      spelling,        -- the ONE field not taken from the entry: see the header
      e.tier,
      null,            -- variant NULL = the ranking's global catch-all
      e.engine,
      1,
      true,
      true,
      false,
      'approved',
      false,
      0,
      null,
      null,
      'global',
      null,
      null,
      'light'
    )
    returning id into created_id;

    insert into public.template_library_instantiations (
      entry_id, entry_version_at_copy, template_id, created_by_user_id
    ) values (e.id, e.version, created_id, null);

    insert into public.template_audit_log (template_id, actor_id, action, summary, metadata)
    values (
      created_id,
      null,
      'library_instantiated',
      format(
        'Activated as the %s production default from library master "%s" v%s (seed 20260816160000)',
        spelling, e.name, e.version
      ),
      jsonb_build_object(
        'entry_id', e.id,
        'entry_version', e.version,
        'entry_slug', e.slug,
        'report_type', spelling,
        'seed', '20260816160000_retire_compass_pilot_and_activate_investment_masters'
      )
    );

    raise notice 'retire_compass_pilot: seeded % from % as template %', spelling, e.slug, created_id;
  end loop;
end $$;
