-- ═══════════════════════════════════════════════════════════════════════
-- AML obligations reach the Reminders hub, and the review cycle is annual
-- ═══════════════════════════════════════════════════════════════════════
--
-- Two changes, both additive, and one repair.
--
-- ── 1 · `client_reminders.source_ref` ─────────────────────────────────
-- A scheduled AML review lived in `aml.existing_customer_reviews` and on one
-- card at the foot of Stage 10. The Command Centre's Reminders hub reads
-- `client_reminders`, client follow-ups and deal milestones — and AML
-- reviews appeared in none of them, so the one obligation with a statutory
-- character and a multi-year horizon was the one nobody would see coming.
--
-- Writing to `client_reminders` puts it where reminders already are. What
-- was missing was a way to write the SAME reminder twice without creating a
-- second row: `source_ref` carries the id of the thing the reminder is about
-- (a review, an attestation), and the partial unique index below makes
-- re-running the operation an update rather than a duplicate.
--
-- The column is nullable and the index is partial, so a reminder somebody
-- typed by hand — every row that exists today — is untouched and can never
-- collide with a generated one.
--
-- ── 2 · The annual review cycle ───────────────────────────────────────
-- `review_interval_config` defaulted to `{high: 12, medium: 24, low: 36}`.
-- Under that, a low-risk customer's identity, screening and circumstances
-- went THREE YEARS without review while their screening refresh fell due at
-- two — two obligations on one customer running on different clocks, with
-- the slower one attached to the more searching question.
--
-- The programme's policy is a review at least annually. AUSTRAC fixes no
-- interval (ongoing CDD is risk-based), so this is a programme parameter and
-- the programme now states it: `reviewSchedule.pure.ts` holds the table and
-- the ceiling. A rating may make the cycle TIGHTER — `prohibited` stays at
-- three months — and never longer.
--
-- ── 3 · The repair ────────────────────────────────────────────────────
-- Existing scheduled reviews were booked under the old table and would
-- otherwise sit at their old dates for years. A periodic review that is not
-- yet complete is a FORWARD-LOOKING obligation, not a historical record, so
-- bringing it forward to the policy is correct and loses nothing.
--
-- It only ever moves a due date EARLIER, only for open periodic reviews, and
-- never touches a completed review, a trigger review, or a case whose
-- relationship has ended. `original_due_at` is left exactly as it was — the
-- date the review was first booked for is history.

-- ── 1 · the column, the vocabulary, and the idempotency index ─────────
--
-- `reminder_type` is CHECK-constrained to a closed list, and the AML kinds
-- were not in it — so every write this feature makes would have been
-- rejected at the column while looking, from the edge function, exactly like
-- a write that had not been attempted. (The same class as
-- `template_library_entries_category_check`: the column decides.) The list is
-- widened rather than the values bent into `review`, because what kind of
-- reminder this is is precisely what this column is for, and the hub filters
-- and icons on it.
alter table public.client_reminders
  drop constraint if exists client_reminders_reminder_type_check;

alter table public.client_reminders
  add constraint client_reminders_reminder_type_check
  check (reminder_type = any (array[
    'follow_up', 'review', 'call', 'meeting', 'document', 'other',
    'task', 'settlement', 'finance', 'admin',
    -- AML/CTF obligations, written by `_shared/aml/complianceReminders.ts`.
    'aml_periodic_review', 'aml_trigger_review', 'aml_passport_issued'
  ]));

alter table public.client_reminders
  add column if not exists source_ref text;

comment on column public.client_reminders.source_ref is
  'The id of the record this reminder is about, for reminders generated by a '
  'system (an AML review, an issued attestation). NULL for a reminder a person '
  'created. Paired with reminder_type it makes generation idempotent: writing '
  'the same reminder twice updates one row rather than creating a second.';

create unique index if not exists client_reminders_source_ref_key
  on public.client_reminders (client_id, reminder_type, source_ref)
  where source_ref is not null;

-- ── 2 · pull open periodic reviews onto the annual cycle ──────────────
do $$
declare
  v_review   record;
  v_new_due  timestamptz;
  v_moved    integer := 0;
begin
  for v_review in
    select r.id, r.case_id, r.due_at, r.original_due_at, c.risk_rating::text as rating,
           c.monitoring_status
      from aml.existing_customer_reviews r
      join aml.cases c on c.id = r.case_id
     where r.classification = 'periodic'
       and r.status in ('queued', 'in_progress', 'remediation_required')
       and coalesce(c.monitoring_status, 'active') <> 'ended'
  loop
    -- Annual from the date the cycle started, which is the date this review
    -- was first booked for minus its old interval — unknowable here. The
    -- honest anchor is the review's own creation: a review booked today
    -- under a 36-month cycle becomes one due a year from today.
    v_new_due := least(
      v_review.due_at,
      (select coalesce(r2.created_at, now()) + interval '12 months'
         from aml.existing_customer_reviews r2 where r2.id = v_review.id)
    );

    -- `prohibited` is already tighter than annual; never loosen it.
    if v_review.rating = 'prohibited' then
      v_new_due := least(v_new_due,
        (select coalesce(r2.created_at, now()) + interval '3 months'
           from aml.existing_customer_reviews r2 where r2.id = v_review.id));
    end if;

    continue when v_new_due >= v_review.due_at;

    update aml.existing_customer_reviews
       set due_at = v_new_due
     where id = v_review.id;

    update aml.cases
       set next_periodic_review_at = v_new_due
     where id = v_review.case_id
       and (next_periodic_review_at is null or next_periodic_review_at > v_new_due);

    v_moved := v_moved + 1;
    raise notice 'periodic review % pulled forward: % -> %',
      v_review.id, v_review.due_at, v_new_due;
  end loop;

  raise notice 'annual review cycle: % open periodic review(s) rescheduled', v_moved;
end $$;

-- A case carrying a scheduled date with no open review row is repaired the
-- same way: the sweep raises the review when the date arrives, so the date
-- is what has to move.
update aml.cases c
   set next_periodic_review_at = c.updated_at + interval '12 months'
 where c.next_periodic_review_at is not null
   and coalesce(c.monitoring_status, 'active') <> 'ended'
   and c.next_periodic_review_at > c.updated_at + interval '12 months'
   and not exists (
         select 1 from aml.existing_customer_reviews r
          where r.case_id = c.id and r.classification = 'periodic'
            and r.status in ('queued', 'in_progress', 'remediation_required'));

-- ── 4 · backfill the reminders for reviews already scheduled ──────────
-- Every open review created before this existed has no reminder, so the
-- Reminders hub would stay silent about it until it was next re-scheduled —
-- which for a periodic review is a year away. Idempotent by the index above:
-- running it twice writes one row.
insert into public.client_reminders
  (client_id, title, description, due_date, priority, status, reminder_type,
   reminder_scope, source_ref)
select
  c.client_id,
  case when r.classification = 'periodic'
       then 'AML/CTF periodic review due — ' || coalesce(c.case_reference, 'compliance case')
       else 'AML/CTF trigger review — ' || coalesce(c.case_reference, 'compliance case') end,
  case when r.classification = 'periodic'
       then 'Ongoing customer due diligence review falls due '
            || to_char(r.due_at at time zone 'Australia/Sydney', 'DD/MM/YYYY')
            || '. Open the case''s Ongoing CDD stage to complete it.'
       else 'An out-of-cycle review is due '
            || to_char(r.due_at at time zone 'Australia/Sydney', 'DD/MM/YYYY')
            || '. Open the case''s Ongoing CDD stage to complete it.' end,
  r.due_at,
  case when r.priority in ('high', 'urgent') then 'high' else 'medium' end,
  'pending',
  case when r.classification = 'periodic' then 'aml_periodic_review'
       else 'aml_trigger_review' end,
  'client',
  r.id::text
from aml.existing_customer_reviews r
join aml.cases c on c.id = r.case_id
where r.status in ('queued', 'in_progress', 'remediation_required')
  and r.classification in ('periodic', 'trigger_based')
  and c.client_id is not null
  and coalesce(c.monitoring_status, 'active') <> 'ended'
  -- `not exists` rather than `on conflict`: inferring a PARTIAL unique index
  -- as the arbiter needs its predicate restated, and a guard that reads as
  -- the rule ("only where there is not one already") survives an index
  -- being renamed.
  and not exists (
        select 1 from public.client_reminders cr
         where cr.client_id = c.client_id
           and cr.source_ref = r.id::text
           and cr.reminder_type in ('aml_periodic_review', 'aml_trigger_review'));
