/**
 * Investment Compass design families — GENERATED, do not hand-edit.
 *
 * Emitted by `scripts/template-library/investmentCompass/generate.ts` from
 * `source.json`, a verbatim evaluation of `FAMILIES` in the approved Claude
 * Design catalogue. Ten families, five structural variants each.
 *
 * A family is a `base` manifest plus, per variant, a sparse override object;
 * the resolved manifest is `Object.assign({}, base, overrides)`, which is
 * exactly how the catalogue itself resolves it. `resolveManifest()` in
 * `family.ts` is that operation.
 *
 * `investmentCompassSource.spec.ts` compares this file against
 * `source.json` and fails if they disagree.
 */
import type { DesignFamily } from './family';

/** 01 — Private Banking. Gold on obsidian, editorial ledger, restrained accent. */
export const PRIVATE_BANKING: DesignFamily = {
  key: 'private_banking',
  code: 'pb',
  ordinal: '01',
  name: 'Private Banking',
  note: 'Gold on obsidian, editorial ledger, restrained accent',
  faces: 'Cinzel · Playfair · Inter · Plex Mono',
  base: {
    design_family: 'private_banking',
    typography_preset: 'cinzel_playfair_inter',
    numeric_typography: 'playfair_lining_tabular',
    cover_overlay: 'obsidian_full',
    section_header_style: 'eyebrow_rule_display',
    kpi_layout: 'four_column_ruled',
    callout_style: 'tinted_gold_bar',
    table_style: 'ledger_hairline',
    chart_style: 'line_editorial',
    navigation_style: 'print_only',
    risk_display: 'rated_table',
    recommendation_style: 'obsidian_card',
    radius: '0',
    border_treatment: 'hairline',
    spacing_scale: 'generous',
    page_margin_preset: '20mm',
    toc_style: 'none',
    footer_style: 'rule_page_number',
    density: 'balanced',
    print_density: 'standard',
  },
  variants: [
    {
      name: 'Chancery',
      code: 'pb-01',
      ground: 'light',
      density: 'balanced',
      architecture: 'band',
      use: 'Client-facing flagship for private clients',
      description:
        'The reference expression: obsidian cover, four ruled KPI columns, gold used once per page.',
      overrides: {},
    },
    {
      name: 'Chancery Compact',
      code: 'pb-02',
      ground: 'light',
      density: 'compact',
      architecture: 'grid',
      use: 'Portfolio reviews covering several properties',
      description:
        'Six KPI columns and tight ledger rules fit two properties per spread without losing the hierarchy.',
      overrides: {
        density: 'compact',
        page_margin_preset: '16mm',
        kpi_layout: 'six_column_ruled',
        spacing_scale: 'tight',
        table_style: 'ledger_tight',
        print_density: 'dense',
      },
    },
    {
      name: 'Sovereign Folio',
      code: 'pb-03',
      ground: 'light',
      density: 'spacious',
      architecture: 'bleed',
      use: 'Single-asset pitch and presentation',
      description:
        'Full-bleed portrait cover, oversized section numerals, KPIs paired two by two at display size.',
      overrides: {
        density: 'spacious',
        cover_overlay: 'obsidian_bleed_portrait',
        section_header_style: 'full_bleed_numeral',
        kpi_layout: 'two_by_two_display',
        spacing_scale: 'luxurious',
        page_margin_preset: '26mm',
      },
    },
    {
      name: 'Bullion Rail',
      code: 'pb-04',
      ground: 'light',
      density: 'balanced',
      architecture: 'rail',
      use: 'Long reports where orientation matters',
      description:
        'A gold rail carries part number and section name down every page; KPIs stack against it.',
      overrides: {
        navigation_style: 'vertical_rail',
        section_header_style: 'rail_marker',
        kpi_layout: 'stacked_rail',
        footer_style: 'rail_number',
        cover_overlay: 'obsidian_rail',
      },
    },
    {
      name: 'Discretion Ledger',
      code: 'pb-05',
      ground: 'light',
      density: 'balanced',
      architecture: 'stack',
      use: 'Clients who read the numbers first',
      description:
        'Statement rules with double-rule totals, severity bars for risk, and recommendations set as a ruled statement.',
      overrides: {
        table_style: 'double_rule_statement',
        kpi_layout: 'ledger_rows',
        risk_display: 'severity_bars',
        callout_style: 'margin_note',
        chart_style: 'stepped_area',
        recommendation_style: 'ruled_statement',
      },
    },
  ],
};

/** 02 — Institutional Research. Numbered exhibits, masthead, coverage-note discipline. */
export const INSTITUTIONAL_RESEARCH: DesignFamily = {
  key: 'institutional_research',
  code: 'ir',
  ordinal: '02',
  name: 'Institutional Research',
  note: 'Numbered exhibits, masthead, coverage-note discipline',
  faces: 'Noto Serif · IBM Plex Mono',
  base: {
    design_family: 'institutional_research',
    typography_preset: 'noto_serif_plex',
    numeric_typography: 'plex_tabular',
    cover_overlay: 'masthead_rule',
    section_header_style: 'numbered_exhibit',
    kpi_layout: 'exhibit_strip',
    callout_style: 'boxed_note',
    table_style: 'exhibit_ruled',
    chart_style: 'panel_multiples',
    navigation_style: 'masthead',
    risk_display: 'rating_table',
    recommendation_style: 'boxed_verdict',
    radius: '0',
    border_treatment: 'rule_2px',
    spacing_scale: 'regular',
    page_margin_preset: '18mm',
    toc_style: 'numbered_list',
    footer_style: 'rule_page_number',
    density: 'balanced',
    print_density: 'standard',
  },
  variants: [
    {
      name: 'Exhibit',
      code: 'ir-01',
      ground: 'light',
      density: 'balanced',
      architecture: 'band',
      use: 'Research-grade reports for professional readers',
      description:
        'Every figure is a numbered exhibit with its own note. Masthead on each page, blue used only for exhibit numbers.',
      overrides: {},
    },
    {
      name: 'Exhibit Dense',
      code: 'ir-02',
      ground: 'light',
      density: 'compact',
      architecture: 'grid',
      use: 'Data-heavy coverage where space is scarce',
      description:
        'Exhibit panels tighten to three per page with running heads and no decorative space.',
      overrides: {
        density: 'compact',
        page_margin_preset: '15mm',
        spacing_scale: 'tight',
        chart_style: 'panel_multiples_dense',
        table_style: 'exhibit_tight',
        print_density: 'dense',
      },
    },
    {
      name: 'Coverage Note',
      code: 'ir-03',
      ground: 'light',
      density: 'compact',
      architecture: 'stack',
      use: 'Two-page updates between full reports',
      description:
        'Front-page verdict and thesis, one exhibit page. Deep analysis moves to the appendix.',
      overrides: {
        density: 'compact',
        cover_overlay: 'note_header',
        section_header_style: 'inline_heading',
        kpi_layout: 'inline_strip',
        toc_style: 'none',
        chart_style: 'single_panel',
      },
    },
    {
      name: 'Analyst Folio',
      code: 'ir-04',
      ground: 'light',
      density: 'spacious',
      architecture: 'bleed',
      use: 'Annual or thematic research with room to breathe',
      description:
        'Exhibit plates run full width with generous margins and a numbered plate list at the front.',
      overrides: {
        density: 'spacious',
        page_margin_preset: '24mm',
        spacing_scale: 'generous',
        chart_style: 'full_width_plate',
        toc_style: 'plate_list',
        section_header_style: 'plate_number',
      },
    },
    {
      name: 'Committee Brief',
      code: 'ir-05',
      ground: 'light',
      density: 'balanced',
      architecture: 'split',
      use: 'Investment committee papers',
      description:
        'A decision box leads page one; every section closes with a stated finding rather than a chart.',
      overrides: {
        cover_overlay: 'decision_box',
        recommendation_style: 'decision_box',
        risk_display: 'finding_rows',
        chart_style: 'minimal_line',
        callout_style: 'finding_note',
        kpi_layout: 'decision_strip',
      },
    },
  ],
};

/** 03 — Luxury Editorial. Serif throughout, photographic plates, justified columns. */
export const LUXURY_EDITORIAL: DesignFamily = {
  key: 'luxury_editorial',
  code: 'le',
  ordinal: '03',
  name: 'Luxury Editorial',
  note: 'Serif throughout, photographic plates, justified columns',
  faces: 'Noto Serif',
  base: {
    design_family: 'luxury_editorial',
    typography_preset: 'noto_serif_only',
    numeric_typography: 'serif_lining_tabular',
    cover_overlay: 'photographic_scrim',
    section_header_style: 'standfirst_italic',
    kpi_layout: 'ruled_four',
    callout_style: 'italic_aside',
    table_style: 'ruled_rows',
    chart_style: 'line_minimal',
    navigation_style: 'print_only',
    risk_display: 'rated_table',
    recommendation_style: 'obsidian_card',
    radius: '0',
    border_treatment: 'hairline',
    spacing_scale: 'generous',
    page_margin_preset: '24mm',
    toc_style: 'none',
    footer_style: 'rule_page_number',
    image_slots: 'four_briefed',
    density: 'balanced',
    print_density: 'standard',
  },
  variants: [
    {
      name: 'Atelier',
      code: 'le-01',
      ground: 'light',
      density: 'balanced',
      architecture: 'plate',
      use: 'Premium reports where photography is available',
      description:
        'Four briefed image slots, justified columns with a drop cap, italic standfirsts and captions.',
      overrides: {},
    },
    {
      name: 'Atelier Plate',
      code: 'le-02',
      ground: 'light',
      density: 'balanced',
      architecture: 'bleed',
      use: 'Reports built around a strong image set',
      description:
        'Six slots including two full-bleed plates; text yields to imagery on narrative pages.',
      overrides: {
        image_slots: 'six_with_bleed',
        cover_overlay: 'photographic_bleed',
        section_header_style: 'plate_standfirst',
        chart_style: 'line_over_plate',
      },
    },
    {
      name: 'Grand Folio',
      code: 'le-03',
      ground: 'light',
      density: 'spacious',
      architecture: 'bleed',
      use: 'Flagship single-asset publications',
      description:
        '28mm margins, display-size openers, one idea per spread. The most generous template in the collection.',
      overrides: {
        density: 'spacious',
        page_margin_preset: '28mm',
        spacing_scale: 'luxurious',
        kpi_layout: 'two_by_two_display',
        section_header_style: 'full_bleed_numeral',
      },
    },
    {
      name: 'Frontispiece',
      code: 'le-04',
      ground: 'light',
      density: 'balanced',
      architecture: 'split',
      use: 'Reports that open with a statement, not a photograph',
      description:
        'A typographic title page carries the verdict; imagery starts on the narrative pages.',
      overrides: {
        cover_overlay: 'typographic_frontispiece',
        image_slots: 'three_interior',
        section_header_style: 'drop_cap_opener',
        recommendation_style: 'ruled_statement',
      },
    },
    {
      name: 'Monograph',
      code: 'le-05',
      ground: 'light',
      density: 'balanced',
      architecture: 'stack',
      use: 'Text-first reports with no photography',
      description:
        'Editorial typography without image slots. Empty plates never print as holes because there are none.',
      overrides: {
        image_slots: 'none',
        cover_overlay: 'typographic_plain',
        table_style: 'ruled_rows_tight',
        chart_style: 'line_minimal',
        density: 'balanced',
      },
    },
  ],
};

/** 04 — Modern Fintech. Inter, dark data ribbon, chips and tabs, violet accent. */
export const MODERN_FINTECH: DesignFamily = {
  key: 'modern_fintech',
  code: 'mf',
  ordinal: '04',
  name: 'Modern Fintech',
  note: 'Inter, dark data ribbon, chips and tabs, violet accent',
  faces: 'Inter',
  base: {
    design_family: 'modern_fintech',
    typography_preset: 'inter_only',
    numeric_typography: 'inter_tabular',
    cover_overlay: 'dark_data_ribbon',
    section_header_style: 'chip_label',
    kpi_layout: 'card_row_four',
    callout_style: 'tinted_violet',
    table_style: 'zebra_soft',
    chart_style: 'bar_solid',
    navigation_style: 'tab_strip',
    risk_display: 'chip_matrix',
    recommendation_style: 'panel_dark',
    radius: '4px',
    border_treatment: 'soft_rule',
    spacing_scale: 'regular',
    page_margin_preset: '18mm',
    toc_style: 'chip_index',
    footer_style: 'thin_rule',
    density: 'balanced',
    print_density: 'standard',
  },
  variants: [
    {
      name: 'Signal',
      code: 'mf-01',
      ground: 'light',
      density: 'balanced',
      architecture: 'band',
      use: 'Digital-first reports read on screen',
      description:
        'Dark data ribbon across the cover, four KPI cards, chip labels for sections and tabs for scenarios.',
      overrides: {},
    },
    {
      name: 'Signal Compact',
      code: 'mf-02',
      ground: 'light',
      density: 'compact',
      architecture: 'grid',
      use: 'Mobile and tablet reading',
      description:
        'Six-up KPI grid, tighter cards, tab strip becomes a scroll rail. Print stays A4-correct.',
      overrides: {
        density: 'compact',
        kpi_layout: 'grid_six',
        page_margin_preset: '15mm',
        spacing_scale: 'tight',
        navigation_style: 'scroll_rail',
        print_density: 'dense',
      },
    },
    {
      name: 'Console',
      code: 'mf-03',
      ground: 'light',
      density: 'balanced',
      architecture: 'split',
      use: 'Dashboard-led reading where numbers come first',
      description:
        'The dashboard is the cover. Narrative sits behind progressive disclosure.',
      overrides: {
        cover_overlay: 'dashboard_cover',
        kpi_layout: 'console_twelve',
        navigation_style: 'sticky_tabs',
        chart_style: 'sparkline_dense',
        section_header_style: 'chip_inline',
      },
    },
    {
      name: 'Ribbon',
      code: 'mf-04',
      ground: 'light',
      density: 'balanced',
      architecture: 'stack',
      use: 'Sequential reading with strong section breaks',
      description:
        'Every section opens on its own dark ribbon, so scanning finds the section not the page.',
      overrides: {
        section_header_style: 'dark_ribbon',
        cover_overlay: 'ribbon_stack',
        callout_style: 'ribbon_note',
        recommendation_style: 'ribbon_verdict',
        toc_style: 'ribbon_index',
      },
    },
    {
      name: 'Pulse',
      code: 'mf-05',
      ground: 'light',
      density: 'balanced',
      architecture: 'grid',
      use: 'Reports where the charts carry the argument',
      description:
        'Chart-led pages with sparklines in every table row and a driver tornado on the sensitivity page.',
      overrides: {
        chart_style: 'sparkline_plus_tornado',
        table_style: 'sparkline_rows',
        kpi_layout: 'card_row_with_trend',
        risk_display: 'trend_chips',
        callout_style: 'chart_note',
      },
    },
  ],
};

/** 05 — Architectural Property. Lato light, monochrome, measured drawings and schedules. */
export const ARCHITECTURAL_PROPERTY: DesignFamily = {
  key: 'architectural_property',
  code: 'ap',
  ordinal: '05',
  name: 'Architectural Property',
  note: 'Lato light, monochrome, measured drawings and schedules',
  faces: 'Lato',
  base: {
    design_family: 'architectural_property',
    typography_preset: 'lato_light',
    numeric_typography: 'lato_tabular',
    cover_overlay: 'hairline_frame_plan',
    section_header_style: 'schedule_number',
    kpi_layout: 'schedule_rows',
    callout_style: 'caption_rail',
    table_style: 'schedule_rules',
    chart_style: 'measured_line',
    navigation_style: 'caption_rail',
    risk_display: 'rated_schedule',
    recommendation_style: 'ruled_note',
    radius: '0',
    border_treatment: 'hairline',
    spacing_scale: 'generous',
    page_margin_preset: '22mm',
    toc_style: 'figure_list',
    footer_style: 'figure_number',
    density: 'balanced',
    print_density: 'standard',
  },
  variants: [
    {
      name: 'Drawing Set',
      code: 'ap-01',
      ground: 'light',
      density: 'balanced',
      architecture: 'frame',
      use: 'Property-led reports for design-literate readers',
      description:
        'Hairline frame, dimensioned allotment plan, numbered schedules and a caption rail for figure notes.',
      overrides: {},
    },
    {
      name: 'Schedule',
      code: 'ap-02',
      ground: 'light',
      density: 'compact',
      architecture: 'grid',
      use: 'Reports dominated by measured data',
      description:
        'Nine schedules per page at 16mm margins. The caption rail narrows to 22mm.',
      overrides: {
        density: 'compact',
        page_margin_preset: '16mm',
        spacing_scale: 'tight',
        table_style: 'schedule_tight',
        navigation_style: 'narrow_rail',
        print_density: 'dense',
      },
    },
    {
      name: 'Elevation',
      code: 'ap-03',
      ground: 'light',
      density: 'spacious',
      architecture: 'bleed',
      use: 'Presentation-grade property reports',
      description:
        'Full-width plates with measured captions and one schedule per page.',
      overrides: {
        density: 'spacious',
        page_margin_preset: '26mm',
        spacing_scale: 'luxurious',
        image_slots: 'four_measured',
        chart_style: 'plate_line',
      },
    },
    {
      name: 'Site Plan',
      code: 'ap-04',
      ground: 'light',
      density: 'balanced',
      architecture: 'split',
      use: 'Reports where location does the arguing',
      description:
        'A dimensioned site and context plan leads, with amenity distances drawn rather than tabulated.',
      overrides: {
        cover_overlay: 'site_plan_cover',
        chart_style: 'distance_diagram',
        kpi_layout: 'plan_callouts',
        section_header_style: 'plan_reference',
      },
    },
    {
      name: 'Datum',
      code: 'ap-05',
      ground: 'light',
      density: 'balanced',
      architecture: 'stack',
      use: 'Numeric readers who want the drawing discipline',
      description:
        'Figures set at display size against hairline rules; captions reduced to source references.',
      overrides: {
        numeric_typography: 'lato_display_tabular',
        kpi_layout: 'datum_rows',
        callout_style: 'source_reference',
        chart_style: 'measured_line_bare',
        table_style: 'datum_rules',
      },
    },
  ],
};

/** 06 — Swiss Minimal. Strict grid, flat blocks, single red accent, no ornament. */
export const SWISS_MINIMAL: DesignFamily = {
  key: 'swiss_minimal',
  code: 'sm',
  ordinal: '06',
  name: 'Swiss Minimal',
  note: 'Strict grid, flat blocks, single red accent, no ornament',
  faces: 'Inter',
  base: {
    design_family: 'swiss_minimal',
    typography_preset: 'inter_grotesk',
    numeric_typography: 'inter_tabular',
    cover_overlay: 'flat_grid',
    section_header_style: 'grid_number',
    kpi_layout: 'grid_cells_four',
    callout_style: 'flat_block',
    table_style: 'grid_lines_light',
    chart_style: 'bar_flat',
    navigation_style: 'grid_index',
    risk_display: 'flat_matrix',
    recommendation_style: 'flat_block',
    radius: '0',
    border_treatment: 'thin_grid',
    spacing_scale: 'strict',
    page_margin_preset: '18mm',
    toc_style: 'grid_index',
    footer_style: 'grid_number',
    density: 'balanced',
    print_density: 'standard',
  },
  variants: [
    {
      name: 'Grid',
      code: 'sm-01',
      ground: 'light',
      density: 'balanced',
      architecture: 'grid',
      use: 'Readers who want structure and nothing else',
      description:
        'Twelve-column grid, flat blocks, red reserved for negative figures and nothing decorative.',
      overrides: {},
    },
    {
      name: 'Grid Tight',
      code: 'sm-02',
      ground: 'light',
      density: 'compact',
      architecture: 'grid',
      use: 'Maximum information at strict alignment',
      description:
        'The same grid at 15mm margins with every module one step smaller.',
      overrides: {
        density: 'compact',
        page_margin_preset: '15mm',
        spacing_scale: 'compressed',
        kpi_layout: 'grid_cells_six',
        table_style: 'grid_lines_tight',
        print_density: 'dense',
      },
    },
    {
      name: 'Objective',
      code: 'sm-03',
      ground: 'light',
      density: 'spacious',
      architecture: 'stack',
      use: 'Short, high-clarity summaries',
      description:
        'Three modules per page at most. What is left out is the design decision.',
      overrides: {
        density: 'spacious',
        page_margin_preset: '24mm',
        spacing_scale: 'open',
        kpi_layout: 'grid_cells_two',
        chart_style: 'bar_flat_large',
      },
    },
    {
      name: 'Raster',
      code: 'sm-04',
      ground: 'light',
      density: 'balanced',
      architecture: 'frame',
      use: 'Reports where the grid should be visible',
      description:
        'Module boundaries print as light rules, so the reader can see the system.',
      overrides: {
        border_treatment: 'visible_module_grid',
        cover_overlay: 'raster_cover',
        section_header_style: 'module_marker',
        table_style: 'module_cells',
        callout_style: 'module_block',
      },
    },
    {
      name: 'Hairline',
      code: 'sm-05',
      ground: 'light',
      density: 'balanced',
      architecture: 'stack',
      use: 'Print-first reports with no filled areas',
      description:
        'Rules only, no blocks and no tints. Emphasis comes from rule weight and position.',
      overrides: {
        border_treatment: 'hairline_only',
        callout_style: 'rule_note',
        kpi_layout: 'hairline_rows',
        table_style: 'hairline_rows',
        recommendation_style: 'rule_statement',
        chart_style: 'line_hairline',
      },
    },
  ],
};

/** 07 — Corporate Advisory. Decimal numbering, letterhead band, signed notes. */
export const CORPORATE_ADVISORY: DesignFamily = {
  key: 'corporate_advisory',
  code: 'ca',
  ordinal: '07',
  name: 'Corporate Advisory',
  note: 'Decimal numbering, letterhead band, signed notes',
  faces: 'Lato',
  base: {
    design_family: 'corporate_advisory',
    typography_preset: 'lato_sans',
    numeric_typography: 'lato_tabular',
    cover_overlay: 'letterhead_band',
    section_header_style: 'decimal_numbered',
    kpi_layout: 'summary_table',
    callout_style: 'indented_note',
    table_style: 'board_ruled',
    chart_style: 'line_plain',
    navigation_style: 'decimal_toc',
    risk_display: 'numbered_register',
    recommendation_style: 'signed_note',
    radius: '0',
    border_treatment: 'rule',
    spacing_scale: 'regular',
    page_margin_preset: '20mm',
    toc_style: 'decimal_toc',
    footer_style: 'reference_page',
    density: 'balanced',
    print_density: 'standard',
  },
  variants: [
    {
      name: 'Board Pack',
      code: 'ca-01',
      ground: 'light',
      density: 'balanced',
      architecture: 'band',
      use: 'Papers going to a board or trustee meeting',
      description:
        'Decimal section numbering, cross-references, a summary table instead of KPI cards, and a signed recommendation.',
      overrides: {},
    },
    {
      name: 'Board Pack Brief',
      code: 'ca-02',
      ground: 'light',
      density: 'compact',
      architecture: 'grid',
      use: 'Consent agendas and short papers',
      description:
        'Two-level numbering only, condensed tables, appendices carry everything else.',
      overrides: {
        density: 'compact',
        page_margin_preset: '16mm',
        spacing_scale: 'tight',
        section_header_style: 'two_level_decimal',
        table_style: 'board_tight',
        print_density: 'dense',
      },
    },
    {
      name: 'Engagement Note',
      code: 'ca-03',
      ground: 'light',
      density: 'balanced',
      architecture: 'stack',
      use: 'Scope, assumptions and reliance up front',
      description:
        'Opens with the engagement basis and reliance statement, then the analysis.',
      overrides: {
        cover_overlay: 'engagement_letterhead',
        section_header_style: 'clause_numbered',
        callout_style: 'reliance_block',
        recommendation_style: 'engagement_terms',
        toc_style: 'clause_index',
      },
    },
    {
      name: 'Committee Memo',
      code: 'ca-04',
      ground: 'light',
      density: 'compact',
      architecture: 'split',
      use: 'Single-decision memoranda',
      description:
        'A memo header carries to, from, date and decision required. One page of analysis, one of evidence.',
      overrides: {
        density: 'compact',
        cover_overlay: 'memo_header',
        kpi_layout: 'decision_summary',
        recommendation_style: 'decision_required',
        chart_style: 'single_line',
        toc_style: 'none',
      },
    },
    {
      name: 'Advisory Letter',
      code: 'ca-05',
      ground: 'light',
      density: 'spacious',
      architecture: 'stack',
      use: 'Client-addressed advice on letterhead',
      description:
        'Set as a letter with the analysis as numbered schedules behind the signature.',
      overrides: {
        density: 'spacious',
        cover_overlay: 'letter_first_page',
        section_header_style: 'schedule_letter',
        page_margin_preset: '24mm',
        table_style: 'schedule_ruled',
        recommendation_style: 'letter_close',
      },
    },
  ],
};

/** 08 — Wealth Management. Roboto, obsidian bands, statement rules, capital framing. */
export const WEALTH_MANAGEMENT: DesignFamily = {
  key: 'wealth_management',
  code: 'wm',
  ordinal: '08',
  name: 'Wealth Management',
  note: 'Roboto, obsidian bands, statement rules, capital framing',
  faces: 'Roboto',
  base: {
    design_family: 'wealth_management',
    typography_preset: 'roboto_only',
    numeric_typography: 'roboto_tabular',
    cover_overlay: 'obsidian_band',
    section_header_style: 'band_header',
    kpi_layout: 'statement_rows',
    callout_style: 'band_note',
    table_style: 'statement_rules',
    chart_style: 'bar_stacked',
    navigation_style: 'band_index',
    risk_display: 'rated_rows',
    recommendation_style: 'band_card',
    radius: '0',
    border_treatment: 'rule',
    spacing_scale: 'regular',
    page_margin_preset: '20mm',
    toc_style: 'band_index',
    footer_style: 'rule_page_number',
    capital_framing: 'total_committed',
    density: 'balanced',
    print_density: 'standard',
  },
  variants: [
    {
      name: 'Statement',
      code: 'wm-01',
      ground: 'light',
      density: 'balanced',
      architecture: 'band',
      use: 'Client packs where total capital is the point',
      description:
        'Every page opens on an obsidian band. Statement rules with single subtotals and double totals.',
      overrides: {},
    },
    {
      name: 'Statement Compact',
      code: 'wm-02',
      ground: 'light',
      density: 'compact',
      architecture: 'grid',
      use: 'Quarterly reviews across a portfolio',
      description:
        'Bands reduce to headers, statements tighten, and the capital summary fits one page.',
      overrides: {
        density: 'compact',
        section_header_style: 'band_strip',
        page_margin_preset: '16mm',
        spacing_scale: 'tight',
        table_style: 'statement_tight',
        print_density: 'dense',
      },
    },
    {
      name: 'Portfolio Review',
      code: 'wm-03',
      ground: 'light',
      density: 'balanced',
      architecture: 'split',
      use: 'Multi-asset reviews where this property is one holding',
      description:
        'A holdings statement leads, with the property analysis as a section rather than the whole document.',
      overrides: {
        cover_overlay: 'holdings_band',
        kpi_layout: 'holdings_rows',
        chart_style: 'allocation_bars',
        section_header_style: 'holding_header',
        toc_style: 'holdings_index',
      },
    },
    {
      name: 'Client Pack',
      code: 'wm-04',
      ground: 'light',
      density: 'spacious',
      architecture: 'stack',
      use: 'Advice packs sent to the client to keep',
      description:
        'Opens with a cover letter, closes with a review schedule and the adviser signature block.',
      overrides: {
        density: 'spacious',
        cover_overlay: 'letter_then_band',
        page_margin_preset: '24mm',
        recommendation_style: 'signed_band',
        toc_style: 'contents_page',
        footer_style: 'client_reference',
      },
    },
    {
      name: 'Fiduciary',
      code: 'wm-05',
      ground: 'light',
      density: 'balanced',
      architecture: 'stack',
      use: 'Advice requiring full disclosure on the page',
      description:
        'Suitability, exclusions, conflicts and assumptions print in full rather than in an appendix.',
      overrides: {
        risk_display: 'disclosure_blocks',
        recommendation_style: 'suitability_statement',
        callout_style: 'disclosure_note',
        toc_style: 'disclosure_index',
        print_density: 'standard',
      },
    },
  ],
};

/** 09 — Data / Analyst. Mono figures on cell gridlines, field keys printed beside values. */
export const DATA_ANALYST: DesignFamily = {
  key: 'data_analyst',
  code: 'da',
  ordinal: '09',
  name: 'Data / Analyst',
  note: 'Mono figures on cell gridlines, field keys printed beside values',
  faces: 'IBM Plex Mono · Inter',
  base: {
    design_family: 'data_analyst',
    typography_preset: 'plex_mono_inter',
    numeric_typography: 'plex_mono_tabular',
    cover_overlay: 'model_header_bar',
    section_header_style: 'sheet_number',
    kpi_layout: 'field_cells_four',
    callout_style: 'mono_caption',
    table_style: 'full_gridlines',
    chart_style: 'small_multiples',
    navigation_style: 'sheet_tabs',
    risk_display: 'validation_suite',
    recommendation_style: 'model_read',
    radius: '0',
    border_treatment: 'cell_grid',
    spacing_scale: 'tight',
    page_margin_preset: '15mm',
    toc_style: 'field_index',
    footer_style: 'sheet_number',
    field_keys: 'printed',
    density: 'compact',
    print_density: 'dense',
  },
  variants: [
    {
      name: 'Model',
      code: 'da-01',
      ground: 'light',
      density: 'compact',
      architecture: 'grid',
      use: 'Analysts and accountants who audit the numbers',
      description:
        'Field keys print beside every value, cell gridlines throughout, and risk is a 13-check validation suite.',
      overrides: {},
    },
    {
      name: 'Model Dense',
      code: 'da-02',
      ground: 'light',
      density: 'compact',
      architecture: 'grid',
      use: 'Full ten-year grids for every scenario',
      description:
        'All three scenario grids on one sheet at 12mm margins. The densest template in the collection.',
      overrides: {
        page_margin_preset: '12mm',
        spacing_scale: 'compressed',
        table_style: 'gridlines_micro',
        chart_style: 'sparklines_only',
        print_density: 'maximum',
      },
    },
    {
      name: 'Worksheet',
      code: 'da-03',
      ground: 'light',
      density: 'compact',
      architecture: 'frame',
      use: 'Reports handed to a client with the workings shown',
      description:
        'Every derivation prints as arithmetic beside its result, in the order the model computes it.',
      overrides: {
        section_header_style: 'step_number',
        callout_style: 'derivation_note',
        kpi_layout: 'derivation_rows',
        table_style: 'worksheet_grid',
        chart_style: 'single_multiple',
      },
    },
    {
      name: 'Dictionary',
      code: 'da-04',
      ground: 'light',
      density: 'balanced',
      architecture: 'stack',
      use: 'Handover to an internal data or engineering team',
      description:
        'The field contract leads: name, type, value, derivation and provenance for every canonical field.',
      overrides: {
        density: 'balanced',
        cover_overlay: 'contract_header',
        toc_style: 'field_contract',
        kpi_layout: 'field_table',
        risk_display: 'validation_plus_schema',
        footer_style: 'field_reference',
      },
    },
    {
      name: 'Terminal',
      code: 'da-05',
      ground: 'dark',
      density: 'compact',
      architecture: 'grid',
      use: 'Screen reading in a dark working environment',
      description:
        'The same grid inverted, mono throughout, with amber reserved for the base case.',
      overrides: {
        cover_overlay: 'dark_model_bar',
        border_treatment: 'dark_cell_grid',
        callout_style: 'amber_caption',
        chart_style: 'small_multiples_dark',
        recommendation_style: 'terminal_read',
      },
    },
  ],
};

/** 10 — Dark Executive. Mono on obsidian, vertical rail, amber for the base case. */
export const DARK_EXECUTIVE: DesignFamily = {
  key: 'dark_executive',
  code: 'de',
  ordinal: '10',
  name: 'Dark Executive',
  note: 'Mono on obsidian, vertical rail, amber for the base case',
  faces: 'IBM Plex Mono · Inter',
  base: {
    design_family: 'dark_executive',
    typography_preset: 'plex_mono_only',
    numeric_typography: 'plex_mono_tabular',
    cover_overlay: 'obsidian_verdict_box',
    section_header_style: 'vertical_rail',
    kpi_layout: 'position_strip_five',
    callout_style: 'amber_bar',
    table_style: 'dark_rules',
    chart_style: 'line_amber',
    navigation_style: 'vertical_rail',
    risk_display: 'rating_map',
    recommendation_style: 'verdict_box',
    radius: '0',
    border_treatment: 'dark_hairline',
    spacing_scale: 'regular',
    page_margin_preset: '18mm',
    toc_style: 'rail_index',
    footer_style: 'rail_number',
    density: 'balanced',
    print_density: 'standard',
  },
  variants: [
    {
      name: 'Obsidian',
      code: 'de-01',
      ground: 'dark',
      density: 'balanced',
      architecture: 'rail',
      use: 'Executive readers who want one sheet per decision',
      description:
        'Obsidian on all seven sheets, verdict box on the cover, four scored tests on the dashboard.',
      overrides: {},
    },
    {
      name: 'Obsidian Brief',
      code: 'de-02',
      ground: 'dark',
      density: 'compact',
      architecture: 'grid',
      use: 'Board-level summaries of three pages or fewer',
      description:
        'Position strip, tests and recommendation on one sheet. Everything else is an appendix.',
      overrides: {
        density: 'compact',
        page_margin_preset: '15mm',
        spacing_scale: 'tight',
        kpi_layout: 'position_strip_eight',
        toc_style: 'none',
        print_density: 'dense',
      },
    },
    {
      name: 'Night Desk',
      code: 'de-03',
      ground: 'dark',
      density: 'spacious',
      architecture: 'stack',
      use: 'Screen reading at length',
      description:
        'Wider measure, larger figures and one argument per sheet.',
      overrides: {
        density: 'spacious',
        page_margin_preset: '24mm',
        spacing_scale: 'open',
        kpi_layout: 'position_pairs',
        chart_style: 'line_amber_large',
      },
    },
    {
      name: 'Signal Dark',
      code: 'de-04',
      ground: 'dark',
      density: 'balanced',
      architecture: 'split',
      use: 'Reports where the charts carry the argument',
      description:
        'Six small multiples on the analysis sheet with amber reserved for the base series.',
      overrides: {
        chart_style: 'small_multiples_amber',
        kpi_layout: 'chart_led_strip',
        table_style: 'dark_rules_tight',
        risk_display: 'rating_map_plus_bars',
      },
    },
    {
      name: 'Executive Rail',
      code: 'de-05',
      ground: 'dark',
      density: 'balanced',
      architecture: 'rail',
      use: 'Long dark reports that must stay navigable',
      description:
        'The rail carries part number, section name and progress on every sheet, including the cover.',
      overrides: {
        navigation_style: 'rail_with_progress',
        cover_overlay: 'rail_cover',
        section_header_style: 'rail_marker_numbered',
        footer_style: 'rail_progress',
        toc_style: 'rail_index_detailed',
      },
    },
  ],
};

/** The ten approved families, in catalogue order. */
export const DESIGN_FAMILIES: readonly DesignFamily[] = [
  PRIVATE_BANKING,
  INSTITUTIONAL_RESEARCH,
  LUXURY_EDITORIAL,
  MODERN_FINTECH,
  ARCHITECTURAL_PROPERTY,
  SWISS_MINIMAL,
  CORPORATE_ADVISORY,
  WEALTH_MANAGEMENT,
  DATA_ANALYST,
  DARK_EXECUTIVE,
];
