/**
 * The mcp edge function's import map must cover every `npm:` specifier its
 * generated entrypoint emits — with the same version on both sides.
 *
 * Why this is a standing contract and not a one-off fix:
 *
 * `supabase/functions/mcp/index.ts` is REGENERATED by @lovable.dev/mcp-js's
 * Vite plugin and hardcodes `npm:` specifiers. The hand-written `deno.json`
 * beside it remaps them to esm.sh, which is the only thing that keeps the
 * bundle deployable (0.69 MB via esm.sh against 26 MB via npm resolution —
 * Supabase's API refuses the latter with 413 "request entity too large").
 *
 * An import-map key that does not exactly match the specifier in the file is
 * SILENTLY IGNORED. On 2026-09-05 the plugin regenerated index.ts from
 * 0.26.3 to 0.28.0, the map's keys stayed at 0.26.3, and every fleet deploy
 * for the next 24 hours failed on this one function — thirteen consecutive
 * red runs of deploy-supabase-functions, each `failed to deploy: mcp`, while
 * `deno check` stayed green because types resolve either way. Nothing in CI
 * judged the pairing; this spec is that judge.
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const FN_DIR = resolve(__dirname, '../../../supabase/functions/mcp');
const entry = readFileSync(resolve(FN_DIR, 'index.ts'), 'utf8');
const config = JSON.parse(readFileSync(resolve(FN_DIR, 'deno.json'), 'utf8')) as {
  imports?: Record<string, string>;
};
const imports = config.imports ?? {};

/** Every npm: specifier the generated entrypoint imports from. */
const specifiers = [...entry.matchAll(/from\s+["'](npm:[^"']+)["']/g)].map((m) => m[1]);

describe('mcp function import map', () => {
  it('the generated entrypoint still imports npm: specifiers (else this spec and the map are dead)', () => {
    expect(specifiers.length).toBeGreaterThan(0);
  });

  it('every npm: specifier in index.ts has an exactly matching import-map key', () => {
    for (const spec of specifiers) {
      expect(
        Object.keys(imports),
        `\`${spec}\` has no exact key in supabase/functions/mcp/deno.json — Deno will silently ` +
          'resolve it from npm (159 packages, 26 MB) and the deploy fails with 413. ' +
          'The plugin was likely upgraded: move every key and its esm.sh URL to the new version, ' +
          'then re-verify with `deno info --config deno.json index.ts` (expect no npm:/ modules).',
      ).toContain(spec);
    }
  });

  it('each mapped URL carries the same package version as its key', () => {
    for (const [key, url] of Object.entries(imports)) {
      const versioned = key.match(/^npm:(@?[^@]+(?:\/[^@/]+)?)@([^/]+)/);
      if (!versioned) continue;
      const [, pkg, version] = versioned;
      // `^3.25.76`-style ranges are mapped to a concrete release; require the
      // URL to sit inside the range's major.minor.patch floor at least.
      const concrete = version.replace(/^[\^~]/, '');
      expect(url, `map key ${key} points at a URL for a different version`).toContain(
        `esm.sh/${pkg}@${concrete}`,
      );
    }
  });

  it('every mapping resolves to esm.sh — the point of the map is to bypass npm tarballs', () => {
    for (const [key, url] of Object.entries(imports)) {
      expect(url, `${key} must map to esm.sh`).toMatch(/^https:\/\/esm\.sh\//);
    }
  });

  it('no deno.lock is committed beside the function', () => {
    // The repo's esm.sh imports are unpinned by convention; a lockfile here
    // would fail the deploy on any esm.sh rebuild — a new failure mode for
    // the one function whose entire problem was that it could not deploy.
    expect(() => readFileSync(resolve(FN_DIR, 'deno.lock'))).toThrow();
  });
});
